package main

import (
	"fmt"
	"testing"
	"time"

	"github.com/google/uuid"
)

// The click history is the one part of the demo that two runs can disagree
// about: `lctl demo --reset` writes a month of backfilled traffic anchored to
// the clock, so whichever run happens second reads a different clock.
//
// TestDemoSeederShowsEveryFeatureItClaimsTo asserts the consequence — seed
// twice, count the same — and it failed roughly one run in three or four, with
// deltas of 4, 8, 21, 67, 127, 152 and 252 clicks, one of them negative
// (F71, F74). The deltas were unequal and unbounded because a discarded click
// used to consume fewer draws from the shared PRNG than a kept one, so a single
// click falling on the far side of the cutoff re-rolled every link and every day
// generated after it.
//
// The two tests below assert the property on the generator instead of on the
// database. That is the whole reason the generation was split out of demoClicks:
// a flake measured through a twenty-second integration test costs hundreds of
// runs to say anything about, and these cost milliseconds. The integration
// assertion stays exactly where it was, and now means what it says.

// demoClickTestIDs gives every catalogue entry a stable id, so comparing two
// generated histories compares the generation rather than whatever uuids the
// links happened to be given.
func demoClickTestIDs(cat []demoLink) map[int]uuid.UUID {
	ids := make(map[int]uuid.UUID, len(cat))
	for i := range cat {
		ids[i] = uuid.NewSHA1(uuid.NameSpaceOID, fmt.Appendf(nil, "demo-link-%d", i))
	}
	return ids
}

// demoClickID is a generated click reduced to everything that reaches the
// database, and comparable, so two histories can be compared as multisets
// without formatting a string per row. The row's own id is deliberately not part
// of it: demoClicks mints a fresh uuid.NewV7 at COPY time and nothing reads it.
type demoClickID struct {
	linkID                                       uuid.UUID
	at                                           int64
	hash                                         string
	country, device, browser, os, lang, referrer string
	isBot                                        bool
	latency                                      int32
}

func demoClickKey(r demoClickRow) demoClickID {
	return demoClickID{
		linkID: r.linkID, at: r.at.UnixNano(), hash: string(r.hash),
		country: r.country, device: r.device, browser: r.browser, os: r.os,
		lang: r.lang, referrer: r.referrer, isBot: r.isBot, latency: r.latency,
	}
}

func demoClickCounts(rows []demoClickRow) map[demoClickID]int {
	seen := make(map[demoClickID]int, len(rows))
	for _, r := range rows {
		seen[demoClickKey(r)]++
	}
	return seen
}

// demoClickCatalogues is both seeded workspaces: the main catalogue and the
// second workspace's. `lctl demo --reset` generates a history for each, and the
// idempotency assertion counts click_events across both.
func demoClickCatalogues() map[string][]demoLink {
	return map[string][]demoLink{
		"catalogue":        demoCatalogue(),
		"second-workspace": demoWorkspace2Catalogue(),
	}
}

// demoClickTestOptions are the flags `make demo-update` and the coverage test
// both run with. Deliberately not a smaller dataset: thirty days at volume 4 is
// the arrangement the failures were observed in.
func demoClickTestOptions() demoOptions {
	return demoOptions{days: 30, volume: 4, prng: 1}
}

// TestDemoClickHistoryDoesNotMoveWithinTheHour is the property `make demo-update`
// and the coverage test both depend on: two runs minutes apart write the same
// history.
//
// Four hours rather than all twenty-four, because the assertion is about the
// generator ignoring everything below the hour and one hour proves that as well
// as a sweep does. The hours chosen are the quiet end of the night, the two ends
// of the business-hours weighting in demoHours, and the last hour of the day.
func TestDemoClickHistoryDoesNotMoveWithinTheHour(t *testing.T) {
	opt := demoClickTestOptions()
	offsets := []time.Duration{
		time.Second,
		37 * time.Second,
		59*time.Minute + 59*time.Second,
	}

	for name, cat := range demoClickCatalogues() {
		ids := demoClickTestIDs(cat)
		for _, hour := range []int{0, 9, 14, 23} {
			// A Wednesday, so the weekday factor is the ordinary one.
			at := time.Date(2026, 8, 5, hour, 0, 0, 0, time.UTC)
			want := demoClickRows(cat, ids, opt, at)
			if hour == 14 && len(want) == 0 {
				t.Fatalf("%s: no clicks generated by mid-afternoon; the fixture is "+
					"wrong, not the code under test", name)
			}
			for _, off := range offsets {
				got := demoClickRows(cat, ids, opt, at.Add(off))
				if len(got) != len(want) {
					t.Errorf("%s: %s generated %d clicks and %s generated %d. "+
						"Two runs in the same hour must write the same history, or "+
						"`lctl demo --reset` is not idempotent.",
						name, at.Format(time.TimeOnly), len(want),
						at.Add(off).Format(time.TimeOnly), len(got))
					continue
				}
				for i := range got {
					if demoClickKey(got[i]) != demoClickKey(want[i]) {
						t.Errorf("%s: click %d differs between %s and %s:\n %+v\n %+v",
							name, i, at.Format(time.TimeOnly),
							at.Add(off).Format(time.TimeOnly),
							demoClickKey(want[i]), demoClickKey(got[i]))
						break
					}
				}
			}
		}
	}
}

// TestDemoClickHistoryOnlyGainsTheHourThatPassed is the assertion that catches a
// desynchronized PRNG, which is what made the failures above unbounded and
// sometimes negative.
//
// Two hours going by must add the clicks that fell in those two hours and change
// nothing else. A generator whose draw count depends on whether a click was
// discarded fails this on the first step: every link and day after the discard is
// re-rolled, so the earlier history stops being a subset of the later one at all.
func TestDemoClickHistoryOnlyGainsTheHourThatPassed(t *testing.T) {
	opt := demoClickTestOptions()
	const step = 2 * time.Hour

	for name, cat := range demoClickCatalogues() {
		ids := demoClickTestIDs(cat)
		midnight := time.Date(2026, 8, 5, 0, 0, 0, 0, time.UTC)
		prev := demoClickCounts(demoClickRows(cat, ids, opt, midnight))

		for at := midnight.Add(step); at.Day() == midnight.Day(); at = at.Add(step) {
			rows := demoClickRows(cat, ids, opt, at)
			now := demoClickCounts(rows)

			for key, n := range prev {
				if now[key] < n {
					t.Fatalf("%s: by %s the history had lost a click it held at %s "+
						"(%d, was %d):\n %+v\n"+
						"Time passing may only add clicks. Losing one means the PRNG "+
						"stream moved, and every link and day after it was re-rolled.",
						name, at.Format(time.TimeOnly),
						at.Add(-step).Format(time.TimeOnly), now[key], n, key)
				}
			}

			// And every click it gained belongs to the window that just passed.
			window := at.Add(-step)
			for _, r := range rows {
				key := demoClickKey(r)
				if now[key] <= prev[key] {
					continue
				}
				if r.at.Before(window) || !r.at.Before(at) {
					t.Fatalf("%s: by %s the history had gained a click timed %s, "+
						"outside the window that passed (%s to %s)",
						name, at.Format(time.TimeOnly), r.at.Format(time.TimeOnly),
						window.Format(time.TimeOnly), at.Format(time.TimeOnly))
				}
			}
			prev = now
		}
	}
}
