//go:build integration

package addon

import (
	"crypto/tls"
	"crypto/x509"
	"errors"
	"net/http"
	"net/netip"
)

// This file exists only under the `integration` build tag, so no binary this
// project ships contains a line of it. `go build ./cmd/...`, `make check`, the
// container image and every release compile the package without it; `go test
// -tags=integration` is the one build that does.
//
// # Why there has to be a seam at all
//
// M69's acceptance test signs a person in through a real OpenID Provider running
// in a container (docker-compose.integration.yml). Two bounds this host enforces
// make that unreachable from a test, and neither of them is wrong:
//
//   - **The address policy.** [refuseAddress] dials globally-routable unicast
//     space and nothing else, so loopback is refused — which is the whole of
//     M68.5 and is exactly what it is for. A container published on 127.0.0.1 is
//     therefore unreachable, and so is one on a docker bridge, which is RFC 1918
//     and carved out. The only way to give a local provider an address this
//     policy dials is to take a range of somebody else's public space and route
//     it to a bridge, on the developer's machine and on the CI runner; that is a
//     larger and less reviewable thing to do than this file.
//   - **The trust store.** A fetch is https-only — the host refuses cleartext and
//     the OIDC add-on refuses a non-https issuer independently — so the provider
//     serves TLS, and the certificate it serves is generated by
//     `scripts/idp.sh` and signed by nobody a public root store knows.
//
// # What it does not relax
//
// The seam is two narrow functions and neither takes a policy. [Host.TestReach]
// takes *addresses*, and every address it was not given still goes through
// [refuseAddress] unchanged; [Host.TestTrust] *adds* a root to the system pool
// rather than replacing it. Everything else about the door is untouched: https
// only, GET or form-encoded POST, no add-on-chosen request header, the origin
// allowlist, the redirect rule, the size caps, the timeouts. The address policy's
// own coverage is in fetch_test.go, which asserts it address by address and
// leaves `allowAddr` alone precisely so the wiring is exercised for real.

// TestReach permits these exact addresses, and changes nothing about any other.
//
// It is additive: an address not in the list is still put through
// [refuseAddress], so a fetch that wanders anywhere the test did not name is
// refused with the same rule and the same log line it would be refused with on an
// instance.
//
// It reaches the add-on fetcher only. M68.6's install fetcher is a separate
// client with its own bounds and is left alone, because a URL install is a
// different door and no test here comes through it.
func (h *Host) TestReach(addrs ...netip.Addr) {
	if h == nil || h.fetcher == nil {
		return
	}
	allowed := make([]netip.Addr, len(addrs))
	copy(allowed, addrs)
	base := h.fetcher.allowAddr
	h.fetcher.allowAddr = func(ip netip.Addr) error {
		for _, a := range allowed {
			if a == ip.Unmap() {
				return nil
			}
		}
		return base(ip)
	}
}

// TestTrust adds one PEM certificate to the roots the add-on fetcher verifies
// against, on top of the system pool.
//
// The system pool is copied rather than discarded, so a fetch to anywhere else
// still has to present a certificate a public root signed. A PEM that holds no
// certificate is an error rather than a silently empty pool — an empty pool
// refuses everything, and a test that got one would report a connection failure
// and send whoever reads it looking at the provider.
func (h *Host) TestTrust(pem []byte) error {
	if h == nil || h.fetcher == nil {
		return errors.New("this host has no fetcher")
	}
	pool, err := x509.SystemCertPool()
	if err != nil {
		pool = x509.NewCertPool()
	}
	if !pool.AppendCertsFromPEM(pem) {
		return errors.New("those bytes hold no PEM certificate")
	}
	tr, ok := h.fetcher.client.Transport.(*http.Transport)
	if !ok {
		return errors.New("this host's fetcher is not driving an *http.Transport")
	}
	tr.TLSClientConfig = &tls.Config{RootCAs: pool, MinVersion: tls.VersionTLS12}
	return nil
}
