#!/usr/bin/env bash
#
# The two development instances: demo and test.
#
# They are separate compose projects, so they have separate containers, separate
# volumes and separate ports, and nothing done to one can reach the other. The
# alternative — one stack that gets reset when a test needs a clean database —
# is why a demo instance worth showing anybody never survived a week.
#
#   demo   long-lived. Refreshed after a milestone is validated, never during
#          one. `make demo-update` is the only thing that should write to it.
#   test   disposable. Rebuilt whenever it is convenient; every default in the
#          Makefile points here so that a mistyped target lands on this one.
#
# See docs/dev-notes/instances.md.
#
# Usage: scripts/instance.sh <command> [instance] [detail]
#
#   init <instance>          create .env.<instance> if it is not there
#   env <instance>           print the env file path, failing if it is missing
#   project <instance>       print the compose project name
#   guard <instance> <what>  refuse a destructive operation on demo
#   list                     both instances, and whether they are up
set -euo pipefail

cd "$(dirname "$0")/.."

# Ports. The demo keeps the familiar numbers from the single-stack era, because
# it is the one opened in a browser; test sits one above on each so both can run
# at once. Postgres and Redis are bound to loopback by the compose override, not
# here.
demo_http=8080  demo_pg=55432  demo_redis=56379  demo_metrics=9090
test_http=8081  test_pg=55433  test_redis=56380  test_metrics=9091

# Restart policy. The demo should be there whenever the browser is pointed at
# it, including after a reboot. The test instance should not: it is stopped when
# idle by scripts/idle-stop.sh, and `no` keeps a reboot from bringing back a
# stack nothing is using.
demo_restart=unless-stopped
test_restart=no

die() { printf '%s\n' "$*" >&2; exit 1; }

# An unknown name must fail loudly. Defaulting it would mean `make down
# INSTANCE=dmeo` silently building a third stack, and the typo would look like
# the demo instance having lost its data.
require_instance() {
	case "${1:-}" in
		demo|test) : ;;
		"") die "instance is required: demo or test" ;;
		*) die "unknown instance '$1'; expected demo or test" ;;
	esac
}

env_file() { printf '.env.%s' "$1"; }
project()  { printf 'linkctrl-%s' "$1"; }

cmd_init() {
	local inst="$1" file http pg redis metrics restart level extra
	file="$(env_file "$inst")"
	if [ -e "$file" ]; then
		printf '%s already exists, leaving it alone\n' "$file" >&2
		return 0
	fi

	command -v openssl >/dev/null 2>&1 ||
		die "openssl is needed to generate the secrets for $file"

	if [ "$inst" = demo ]; then
		http=$demo_http pg=$demo_pg redis=$demo_redis metrics=$demo_metrics
		restart=$demo_restart level=info
		extra='# The demo runs the image built at the last validated milestone, so it does
# not move while a milestone is in progress. make demo-update retags it.'
	else
		http=$test_http pg=$test_pg redis=$test_redis metrics=$test_metrics
		restart=$test_restart level=debug
		extra='LINKCTRL_SERVER_TIMING=true    # Server-Timing headers, for reading the hot path'
	fi

	# umask rather than a later chmod: the secrets are in the file from the first
	# write, and a window where they are world-readable is a window.
	( umask 077
	cat > "$file" <<EOF
# LinkCtrl — the $inst instance. Generated by scripts/instance.sh; not committed.
#
# Delete this file and run \`make env INSTANCE=$inst\` to regenerate it. That mints
# new secrets, and POSTGRES_PASSWORD must match what the volume was initialised
# with, so regenerating means recreating the volume too:
#
#   make down INSTANCE=$inst$([ "$inst" = demo ] && printf ' CONFIRM=demo')
#
# Only the settings that differ per instance are here. Everything else takes the
# binary's default; .env.example documents the full set with its reasoning.

# ─── Identity ────────────────────────────────────────────────────────────────
# Read by docker-compose.yml. LINKCTRL_ENV_PATH is what makes the container load
# this file rather than .env — see the comment on env_file in docker-compose.yml.
LINKCTRL_ENV_PATH=$file
COMPOSE_PROJECT_NAME=$(project "$inst")
LINKCTRL_IMAGE=linkctrl
LINKCTRL_TAG=$inst

# ─── Ports ───────────────────────────────────────────────────────────────────
# All but the first are published to 127.0.0.1 only, by the compose override.
LINKCTRL_BASE_URL=http://localhost:$http
LINKCTRL_HTTP_PORT=$http
POSTGRES_PORT=$pg
REDIS_PORT=$redis
LINKCTRL_METRICS_PORT=$metrics

# ─── Lifecycle ───────────────────────────────────────────────────────────────
LINKCTRL_RESTART=$restart

# ─── Secrets ─────────────────────────────────────────────────────────────────
LINKCTRL_API_KEY_PEPPER=$(openssl rand -base64 48 | tr -d '\n')
POSTGRES_PASSWORD=$(openssl rand -base64 36 | tr -dc 'A-Za-z0-9' | cut -c1-40)

# ─── Local ───────────────────────────────────────────────────────────────────
LINKCTRL_APP_ENV=development
LINKCTRL_SECURE_COOKIES=false  # __Host- cookies need TLS; this is http://localhost
LINKCTRL_LOG_FORMAT=text
LINKCTRL_LOG_LEVEL=$level
LINKCTRL_MIGRATE_ON_START=true
$extra
EOF
	)
	printf 'wrote %s (mode 600): http://localhost:%s, postgres %s, redis %s\n' \
		"$file" "$http" "$pg" "$redis" >&2
}

# The password is URL-safe by construction above, because the Makefile assembles
# it into a DSN and a percent-encoding bug there reads as an authentication
# failure several steps from its cause.
cmd_env() {
	local file
	file="$(env_file "$1")"
	[ -f "$file" ] || die "$file does not exist; run: make env INSTANCE=$1"
	printf '%s\n' "$file"
}

# Every destructive target routes through this. CONFIRM is deliberately awkward:
# the demo instance is the one holding a month of history somebody is looking at,
# and `make down` is two characters from `make up`.
cmd_guard() {
	local inst="$1" what="${2:-this operation}"
	[ "$inst" = demo ] || return 0
	[ "${CONFIRM:-}" = demo ] && return 0
	cat >&2 <<EOF
Refusing: $what would destroy or overwrite data on the demo instance.

The demo holds the workspace you look at between milestones. If you mean it:

  make $what INSTANCE=demo CONFIRM=demo
  task $what INSTANCE=demo CONFIRM=demo

To refresh the demo with a new build and a fresh month of history instead, which
is what a validated milestone calls for:

  make demo-update
EOF
	exit 1
}

cmd_list() {
	local inst file state ports
	printf '%-6s %-16s %-22s %s\n' INSTANCE PROJECT URL STATE
	for inst in demo test; do
		file="$(env_file "$inst")"
		if [ ! -f "$file" ]; then
			printf '%-6s %-16s %-22s %s\n' \
				"$inst" "$(project "$inst")" "-" "no env file"
			continue
		fi
		ports="$(sed -n 's/^LINKCTRL_HTTP_PORT=//p' "$file" | tr -d '\r' | head -1)"
		state="$(docker compose -p "$(project "$inst")" --env-file "$file" ps \
			--format '{{.Service}}:{{.State}}' 2>/dev/null | tr '\n' ' ')"
		[ -n "$state" ] || state="down"
		printf '%-6s %-16s %-22s %s\n' \
			"$inst" "$(project "$inst")" "http://localhost:$ports" "$state"
	done
}

main() {
	local cmd="${1:-}"
	shift || true
	case "$cmd" in
		init)    require_instance "${1:-}"; cmd_init "$1" ;;
		env)     require_instance "${1:-}"; cmd_env "$1" ;;
		project) require_instance "${1:-}"; project "$1"; printf '\n' ;;
		guard)   require_instance "${1:-}"; cmd_guard "$1" "${2:-}" ;;
		list)    cmd_list ;;
		*)       die "usage: scripts/instance.sh {init|env|project|guard|list} [instance]" ;;
	esac
}

main "$@"
