// Code generated by internal/addon/abi/gen. DO NOT EDIT.
// Edit internal/addon/abi and run `make abi-sdk`.

package sdk

import "errors"

// ABIVersion is the ABI version this SDK was generated from. An add-on's
// manifest declares ABIGeneration in its abi_version field; the host
// refuses a module built against a generation it does not implement, before
// instantiating it.
const ABIVersion = "0.1.0"

// ABIGeneration is the integer a manifest's abi_version field must carry
// for a module built against this SDK.
const ABIGeneration = 1

// The errors a host function can answer with. Every one is comparable with
// errors.Is, and a status this SDK does not know arrives as an unwrapped
// error naming the number — which is what a module built against an older
// SDK sees when a newer host refuses it for a reason that did not exist
// yet.
var (
	// The host failed at something that is not the add-on's fault; it has
	// logged the detail.
	ErrInternal = errors.New("linkctrl: the host failed at something that is not the add-on's fault; it has logged the detail")
	// This ABI declares the function and this host does not implement it yet.
	ErrNotAvailable = errors.New("linkctrl: this ABI declares the function and this host does not implement it yet")
	// The add-on did not declare this capability, or declared it and may not
	// have it.
	ErrDenied = errors.New("linkctrl: the add-on did not declare this capability, or declared it and may not have it")
	// A well-formed request for something that is not there.
	ErrNotFound = errors.New("linkctrl: a well-formed request for something that is not there")
	// The arguments were the add-on's fault: a length outside its memory, text
	// that is not UTF-8, or a value outside the vocabulary.
	ErrInvalid = errors.New("linkctrl: the arguments were the add-on's fault: a length outside its memory, text that is not UTF-8, or a value outside the vocabulary")
)

// The levels Log accepts. Anything else is ErrInvalid.
const (
	LevelDebug = "debug"
	LevelInfo  = "info"
	LevelWarn  = "warn"
	LevelError = "error"
)

// statusError maps a negative return value onto one of the errors above.
func statusError(n int32) error {
	switch n {
	case -1:
		return ErrInternal
	case -2:
		return ErrNotAvailable
	case -3:
		return ErrDenied
	case -4:
		return ErrNotFound
	case -5:
		return ErrInvalid
	}
	return errors.New("linkctrl: the host refused with a status this SDK does not know")
}
