// Code generated by internal/addon/abi/gen. DO NOT EDIT.
// Edit internal/addon/abi and run `make abi-sdk`.

//go:build !(wasip1 && wasm)

package sdk

// HostABIVersion is the ABI version of the host this module is running in.
// A module's manifest declares the generation it was built against and the
// host refuses a mismatch before instantiation, so this is not how a module
// checks compatibility — it is how one logs what it is talking to, and
// how it decides whether a function added in a later patch is worth probing
// for.
//
// ABI: linkctrl.abi_version, since 0.1.0; implemented since this version.
func HostABIVersion() (string, error) {
	return "", errNotWasm
}

// Log writes one line to the host's logger, attributed to this add-on. It
// is the only way out: a module's stdout and stderr are discarded, because
// routing them into an operator's log is a capability and the host grants
// none it was not asked for. The host adds the add-on's name; a message
// that repeats it is noise. An unknown level is ErrInvalid rather than a
// silent default, so a typo does not become a line nobody greps for. The
// message is neutralized before it is written and bounded at 4 KiB, and the
// rule is stated as what survives rather than as what is caught: a graphic
// character reaches the line as itself, in any script, and everything else
// becomes its escape — a newline, a control character, an ANSI escape,
// every format and bidirectional control, every unassigned or private-use
// code point, and the few characters that are graphic by category and
// render as nothing. So an invisible code point appears in the line rather
// than acting on whoever reads it, and a code point Unicode adds after the
// host was built is escaped rather than let through. One graphic character
// does not reach the line as itself: a backslash is doubled, so that the
// two characters \ and n cannot be mistaken for an escaped newline, and a
// module cannot spell the host's own truncation mark. The named exceptions
// run the other way: Unicode's prepended concatenation marks — the
// Arabic, Syriac and Kaithi signs that scope the digits after them — are
// left alone, read from Unicode's property rather than from a list, so a
// host built against a newer revision carries the marks it added. Nothing
// is refused for any of it, and a message that needed none arrives as it
// was written, backslashes aside.
//
// level is one of the Level constants; message is the line, without a
// trailing newline.
//
// ABI: linkctrl.log, since 0.1.0; implemented since this version.
func Log(level string, message string) error {
	return errNotWasm
}

// ConfigGet reads one of this add-on's own settings. The key must be one
// the add-on's manifest declares; anything else is ErrDenied, which is what
// scopes the function to the add-on rather than to the instance — there
// is no way to ask for another add-on's setting or for one of this
// product's own configuration values. A declared setting with no value yet
// answers with the default the manifest gave it, and ErrNotFound only when
// it declared none. Values are edited in the Add-on manager; until a host
// implements that, every answer is a declared default.
//
// key is the name of a setting this add-on's manifest declares.
//
// ABI: linkctrl.config_get, since 0.1.0; implemented since this version.
//
// Requires the config.read permission, declared in this add-on's manifest.
// A module that did not declare it gets ErrDenied, whether or not the host
// implements the function.
func ConfigGet(key string) (string, error) {
	return "", errNotWasm
}

// StorageQuery runs a read against the Postgres schema this add-on owns.
// The schema boundary is the whole of the permission: an add-on names no
// database, no connection and no search_path, and a statement that reaches
// outside its own schema is refused rather than executed — ErrDenied,
// which is distinguishable from ErrInvalid so that a module can tell
// confinement from its own mistake. One statement per call: the host parses
// through the extended protocol, so a payload carrying two is refused. The
// read is a read at the server, in a READ ONLY transaction, so this
// function cannot be used to write. Arguments are a JSON array of strings,
// numbers, booleans and nulls; pass JSON as a string and cast it. Rows come
// back as a JSON array of objects keyed by column name, and a result with
// two columns of one name is refused rather than collapsed.
//
// sql is a statement against this add-on's own schema; args is positional
// arguments, as a JSON array.
//
// ABI: linkctrl.storage_query, since 0.1.0; implemented since this version.
//
// Requires the storage.own_schema permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func StorageQuery(sql string, args []byte) ([]byte, error) {
	return nil, errNotWasm
}

// StorageExec runs a write against the Postgres schema this add-on owns.
// Migrations are not this function: the host runs an add-on's migrations,
// which is what keeps *DDL is additive within a minor version* a promise
// somebody can keep — the add-on ships them in its own `migrations/`
// directory and names each with its digest in the manifest, and the host
// applies them at load inside the same schema this function writes to.
// Everything StorageQuery says about the boundary, the single statement and
// the arguments applies here too; what differs is that the transaction is
// not read-only.
//
// sql is a statement against this add-on's own schema; args is positional
// arguments, as a JSON array.
//
// ABI: linkctrl.storage_exec, since 0.1.0; implemented since this version.
//
// Requires the storage.own_schema permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func StorageExec(sql string, args []byte) error {
	return errNotWasm
}

// HTTPRequestRead reads the request that reached one of this add-on's
// routes. It answers ErrNotFound outside a request, which is what a module
// calling it from package initialization gets. A host that does not
// implement it yet answers ErrNotAvailable.
//
// ABI: linkctrl.http_request_read, since 0.1.0; declared, and not
// implemented by every host: a host without it answers ErrNotAvailable,
// which a module may branch on.
//
// Requires the routes.own_prefix permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func HTTPRequestRead() ([]byte, error) {
	return nil, errNotWasm
}

// HTTPResponseWrite answers the request that reached one of this add-on's
// routes. Called twice for one request it is ErrInvalid: a response is one
// record, not a stream, because a module that can hold a connection open is
// a module that can hold every connection open. A host that does not
// implement it yet answers ErrNotAvailable.
//
// response is the response, as an HTTPResponse record.
//
// ABI: linkctrl.http_response_write, since 0.1.0; declared, and not
// implemented by every host: a host without it answers ErrNotAvailable,
// which a module may branch on.
//
// Requires the routes.own_prefix permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func HTTPResponseWrite(response []byte) error {
	return errNotWasm
}

// TemplateRender renders one of this add-on's own templates through the
// host's renderer, so a page an add-on draws inherits the product's
// escaping, its theme tokens and its Content-Security-Policy. It is also
// how an add-on reaches the page without bringing a front-end toolchain: it
// renders nothing itself. A host that does not implement it yet answers
// ErrNotAvailable.
//
// name is a template this add-on shipped; data is the template's data, as a
// JSON object.
//
// ABI: linkctrl.template_render, since 0.1.0; declared, and not implemented
// by every host: a host without it answers ErrNotAvailable, which a module
// may branch on.
//
// Requires the routes.own_prefix permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func TemplateRender(name string, data []byte) ([]byte, error) {
	return nil, errNotWasm
}

// SessionMint tells the host that this add-on authenticated somebody, and
// asks for a session. The add-on does not make a session and never sees a
// token: it makes an assertion, the host decides whether an account exists
// for it and what the session may do, and the cookie is written by the
// host. That split is what keeps the host, and not an add-on, the authority
// over who is signed in. What comes back is a MintedSession, and it is
// enumerated for the same reason the claim is: an answer described only as
// "a JSON object" is an answer the credential assertion over this surface
// cannot read. A host that does not implement it yet answers
// ErrNotAvailable.
//
// claim is who authenticated, as a SessionClaim record.
//
// ABI: linkctrl.session_mint, since 0.1.0; declared, and not implemented by
// every host: a host without it answers ErrNotAvailable, which a module may
// branch on.
//
// Requires the session.mint permission, declared in this add-on's manifest.
// A module that did not declare it gets ErrDenied, whether or not the host
// implements the function.
func SessionMint(claim []byte) ([]byte, error) {
	return nil, errNotWasm
}

// RedirectEventRead reads the redirect this add-on is observing. What it
// carries is at most what click_events may carry — prefix-derived and
// country-level, and no client address in any form. The grant it costs is
// redirect.observe, which is out-of-band observation and nothing more:
// running inside the redirect path itself is redirect.inline, a separate
// declaration no host grants yet, so a module cannot reach the path by
// holding this. A host that does not implement it yet answers
// ErrNotAvailable.
//
// ABI: linkctrl.redirect_event_read, since 0.1.0; declared, and not
// implemented by every host: a host without it answers ErrNotAvailable,
// which a module may branch on.
//
// Requires the redirect.observe permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func RedirectEventRead() ([]byte, error) {
	return nil, errNotWasm
}
