// Code generated by internal/addon/abi/gen. DO NOT EDIT.
// Edit internal/addon/abi and run `make abi-sdk`.

//go:build wasip1 && wasm

package sdk

import (
	"runtime"
	"unsafe"
)

//go:wasmimport linkctrl abi_version
//go:noescape
func wasmHostABIVersion(versionPtr unsafe.Pointer, versionLen uint32) int32

//go:wasmimport linkctrl log
//go:noescape
func wasmLog(levelPtr unsafe.Pointer, levelLen uint32, messagePtr unsafe.Pointer, messageLen uint32) int32

//go:wasmimport linkctrl config_get
//go:noescape
func wasmConfigGet(keyPtr unsafe.Pointer, keyLen uint32, valuePtr unsafe.Pointer, valueLen uint32) int32

//go:wasmimport linkctrl storage_query
//go:noescape
func wasmStorageQuery(sqlPtr unsafe.Pointer, sqlLen uint32, argsPtr unsafe.Pointer, argsLen uint32, rowsPtr unsafe.Pointer, rowsLen uint32) int32

//go:wasmimport linkctrl storage_exec
//go:noescape
func wasmStorageExec(sqlPtr unsafe.Pointer, sqlLen uint32, argsPtr unsafe.Pointer, argsLen uint32) int32

//go:wasmimport linkctrl http_request_read
//go:noescape
func wasmHTTPRequestRead(requestPtr unsafe.Pointer, requestLen uint32) int32

//go:wasmimport linkctrl http_response_write
//go:noescape
func wasmHTTPResponseWrite(responsePtr unsafe.Pointer, responseLen uint32) int32

//go:wasmimport linkctrl template_render
//go:noescape
func wasmTemplateRender(namePtr unsafe.Pointer, nameLen uint32, dataPtr unsafe.Pointer, dataLen uint32, htmlPtr unsafe.Pointer, htmlLen uint32) int32

//go:wasmimport linkctrl session_context
//go:noescape
func wasmSessionContextRead(contextPtr unsafe.Pointer, contextLen uint32) int32

//go:wasmimport linkctrl session_mint
//go:noescape
func wasmSessionMint(claimPtr unsafe.Pointer, claimLen uint32, sessionPtr unsafe.Pointer, sessionLen uint32) int32

//go:wasmimport linkctrl redirect_event_read
//go:noescape
func wasmRedirectEventRead(eventPtr unsafe.Pointer, eventLen uint32) int32

// HostABIVersion is the ABI version of the host this module is running in.
// A module's manifest declares the generation it was built against and the
// host refuses a mismatch before instantiation, so this is not how a module
// checks compatibility — it is how one logs what it is talking to, and
// how it decides whether a function added in a later patch is worth probing
// for.
//
// ABI: linkctrl.abi_version, since 0.1.0; implemented since this version.
func HostABIVersion() (string, error) {
	buf := make([]byte, initialBuffer)
	for attempt := 0; attempt < growthAttempts; attempt++ {
		n := wasmHostABIVersion(bytesPtr(buf), uint32(len(buf)))
		runtime.KeepAlive(buf)
		if n < 0 {
			return "", statusError(n)
		}
		if int(n) <= len(buf) {
			return string(buf[:n]), nil
		}
		buf = make([]byte, n)
	}
	return "", ErrInternal
}

// Log writes one line to the host's logger, attributed to this add-on. It
// is the only way out: a module's stdout and stderr are discarded, because
// routing them into an operator's log is a capability and the host grants
// none it was not asked for. The host adds the add-on's name; a message
// that repeats it is noise. An unknown level is ErrInvalid rather than a
// silent default, so a typo does not become a line nobody greps for. The
// message is neutralized before it is written and bounded at 4 KiB, and the
// rule is stated as what survives rather than as what is caught: a graphic
// character reaches the line as itself, in any script, and everything else
// becomes its escape — a newline, a control character, an ANSI escape,
// every format and bidirectional control, every unassigned or private-use
// code point, and the 268 graphic code points this host treats as
// invisible: the 267 graphic members of Unicode's derived
// Default_Ignorable_Code_Point, which the host computes rather than reads
// because Go ships only the residue property the derivation subtracts from,
// plus U+2800 BRAILLE PATTERN BLANK, the one blank that is not whitespace.
// One class is deleted rather than escaped, and it is the only one: every
// variation selector is removed from the message. So a heart written as
// U+2764 U+FE0F arrives as U+2764 and is still a heart, an emoji that
// carries no selector is untouched, and a selector hung off a letter, a
// space, an ideograph or a block element takes nothing with it when it
// goes. There is no exemption and no base list: a selector after a
// character the reader's renderer does not vary is invisible, and no
// property tells the host which those are. That set is a published property
// and not the set of characters that render as nothing, because Unicode
// publishes no such property: eight combining marks it annotates as not
// visibly rendered — U+2D7F, U+17D2, U+10A3F, U+1107F, U+11A47, U+11A99,
// U+11F42 and U+16FE4 — reach the line as themselves, as do seventeen
// space characters and the prepended concatenation marks named below. What
// bounds that residue is that this log is write-only to you: Log declares
// no out-parameter, no function in this ABI hands log content back, your
// module gets no preopened file and its stdout and stderr are discarded,
// and your storage is a schema this log does not live in. So a character
// that survives is one an operator can still see; it is not a channel you
// can read back. A code point Unicode adds after the host was built is
// escaped rather than let through. One graphic character does not reach the
// line as itself: a backslash is doubled, so that the two characters \ and
// n cannot be mistaken for an escaped newline, and a module cannot spell
// the host's own truncation mark. The named exceptions run the other way:
// Unicode's prepended concatenation marks — the Arabic, Syriac and Kaithi
// signs that scope the digits after them — are left alone, read from
// Unicode's property rather than from a list, so a host built against a
// newer revision carries the marks it added. Nothing is refused for any of
// it, and a message that needed none arrives as it was written, backslashes
// aside.
//
// level is one of the Level constants; message is the line, without a
// trailing newline.
//
// ABI: linkctrl.log, since 0.1.0; implemented since this version.
func Log(level string, message string) error {
	n := wasmLog(stringPtr(level), uint32(len(level)), stringPtr(message), uint32(len(message)))
	runtime.KeepAlive(level)
	runtime.KeepAlive(message)
	if n < 0 {
		return statusError(n)
	}
	return nil
}

// ConfigGet reads one of this add-on's own settings. The key must be one
// the add-on's manifest declares; anything else is ErrDenied, which is what
// scopes the function to the add-on rather than to the instance — there
// is no way to ask for another add-on's setting or for one of this
// product's own configuration values. A declared setting with no value yet
// answers with the default the manifest gave it, and ErrNotFound only when
// it declared none. An operator sets a value with
// LINKCTRL_ADDON_<NAME>_<SETTING> and it outranks the manifest's default;
// editing them in the Add-on manager is M68's, and until that lands the
// environment is the only way to set one.
//
// key is the name of a setting this add-on's manifest declares.
//
// ABI: linkctrl.config_get, since 0.1.0; implemented since this version.
//
// Requires the config.read permission, declared in this add-on's manifest.
// A module that did not declare it gets ErrDenied, whether or not the host
// implements the function.
func ConfigGet(key string) (string, error) {
	buf := make([]byte, initialBuffer)
	for attempt := 0; attempt < growthAttempts; attempt++ {
		n := wasmConfigGet(stringPtr(key), uint32(len(key)), bytesPtr(buf), uint32(len(buf)))
		runtime.KeepAlive(key)
		runtime.KeepAlive(buf)
		if n < 0 {
			return "", statusError(n)
		}
		if int(n) <= len(buf) {
			return string(buf[:n]), nil
		}
		buf = make([]byte, n)
	}
	return "", ErrInternal
}

// StorageQuery runs a read against the Postgres schema this add-on owns.
// The schema boundary is the whole of the permission: an add-on names no
// database, no connection and no search_path, and a statement that reaches
// outside its own schema is refused rather than executed — ErrDenied,
// which is distinguishable from ErrInvalid so that a module can tell
// confinement from its own mistake. One statement per call: the host parses
// through the extended protocol, so a payload carrying two is refused. The
// read is a read at the server, in a READ ONLY transaction, so this
// function cannot be used to write. Arguments are a JSON array of strings,
// numbers, booleans and nulls; pass JSON as a string and cast it. Rows come
// back as a JSON array of objects keyed by column name, and a result with
// two columns of one name is refused rather than collapsed.
//
// sql is a statement against this add-on's own schema; args is positional
// arguments, as a JSON array.
//
// ABI: linkctrl.storage_query, since 0.1.0; implemented since this version.
//
// Requires the storage.own_schema permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func StorageQuery(sql string, args []byte) ([]byte, error) {
	buf := make([]byte, initialBuffer)
	for attempt := 0; attempt < growthAttempts; attempt++ {
		n := wasmStorageQuery(stringPtr(sql), uint32(len(sql)), bytesPtr(args), uint32(len(args)), bytesPtr(buf), uint32(len(buf)))
		runtime.KeepAlive(sql)
		runtime.KeepAlive(args)
		runtime.KeepAlive(buf)
		if n < 0 {
			return nil, statusError(n)
		}
		if int(n) <= len(buf) {
			return buf[:n:n], nil
		}
		buf = make([]byte, n)
	}
	return nil, ErrInternal
}

// StorageExec runs a write against the Postgres schema this add-on owns.
// Migrations are not this function: the host runs an add-on's migrations,
// which is what keeps *DDL is additive within a minor version* a promise
// somebody can keep — the add-on ships them in its own `migrations/`
// directory and names each with its digest in the manifest, and the host
// applies them at load inside the same schema this function writes to.
// Everything StorageQuery says about the boundary, the single statement and
// the arguments applies here too; what differs is that the transaction is
// not read-only.
//
// sql is a statement against this add-on's own schema; args is positional
// arguments, as a JSON array.
//
// ABI: linkctrl.storage_exec, since 0.1.0; implemented since this version.
//
// Requires the storage.own_schema permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func StorageExec(sql string, args []byte) error {
	n := wasmStorageExec(stringPtr(sql), uint32(len(sql)), bytesPtr(args), uint32(len(args)))
	runtime.KeepAlive(sql)
	runtime.KeepAlive(args)
	if n < 0 {
		return statusError(n)
	}
	return nil
}

// HTTPRequestRead reads the request that reached one of this add-on's
// routes. It answers ErrNotFound outside a request, which is what a module
// calling it from package initialization gets — an instance is made per
// request and its initialization runs before the request is attached, so
// this is the ordinary answer during init rather than an edge case. Read
// twice in one request it answers the same record twice: the host holds it,
// the guest does not consume it.
//
// ABI: linkctrl.http_request_read, since 0.1.0; implemented since this
// version.
//
// Requires the routes.own_prefix permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func HTTPRequestRead() ([]byte, error) {
	buf := make([]byte, initialBuffer)
	for attempt := 0; attempt < growthAttempts; attempt++ {
		n := wasmHTTPRequestRead(bytesPtr(buf), uint32(len(buf)))
		runtime.KeepAlive(buf)
		if n < 0 {
			return nil, statusError(n)
		}
		if int(n) <= len(buf) {
			return buf[:n:n], nil
		}
		buf = make([]byte, n)
	}
	return nil, ErrInternal
}

// HTTPResponseWrite answers the request that reached one of this add-on's
// routes. Called twice for one request it is ErrInvalid: a response is one
// record, not a stream, because a module that can hold a connection open is
// a module that can hold every connection open. What the record may carry
// is bounded by the host and not by the module: `content_type` is a closed
// vocabulary that does not include text/html, because the host wraps a page
// and an add-on that could choose the type could choose markup; `location`
// is answered 302 and never a permanent redirect; and `set_cookie` is
// bounded by the prefixes the manifest declares and by a `max_age` of at
// most 400 days, with the host's own Secure, HttpOnly and SameSite
// attributes applied. Each of those is ErrInvalid rather than a silently
// corrected response. The cookies themselves are carried in one cookie of
// the host's rather than written individually, so what an add-on occupies
// in a browser does not grow with what it sets or with how often it is
// visited — a set too large to pack into one is ErrInvalid at this call.
//
// response is the response, as an HTTPResponse record.
//
// ABI: linkctrl.http_response_write, since 0.1.0; implemented since this
// version.
//
// Requires the routes.own_prefix permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func HTTPResponseWrite(response []byte) error {
	n := wasmHTTPResponseWrite(bytesPtr(response), uint32(len(response)))
	runtime.KeepAlive(response)
	if n < 0 {
		return statusError(n)
	}
	return nil
}

// TemplateRender renders one of this add-on's own templates through the
// host's renderer, so a page an add-on draws inherits the product's
// escaping, its theme tokens and its Content-Security-Policy. It is also
// how an add-on reaches the page without bringing a front-end toolchain: it
// renders nothing itself. A host that does not implement it yet answers
// ErrNotAvailable.
//
// name is a template this add-on shipped; data is the template's data, as a
// JSON object.
//
// ABI: linkctrl.template_render, since 0.1.0; declared, and not implemented
// by every host: a host without it answers ErrNotAvailable, which a module
// may branch on.
//
// Requires the routes.own_prefix permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func TemplateRender(name string, data []byte) ([]byte, error) {
	buf := make([]byte, initialBuffer)
	for attempt := 0; attempt < growthAttempts; attempt++ {
		n := wasmTemplateRender(stringPtr(name), uint32(len(name)), bytesPtr(data), uint32(len(data)), bytesPtr(buf), uint32(len(buf)))
		runtime.KeepAlive(name)
		runtime.KeepAlive(data)
		runtime.KeepAlive(buf)
		if n < 0 {
			return nil, statusError(n)
		}
		if int(n) <= len(buf) {
			return buf[:n:n], nil
		}
		buf = make([]byte, n)
	}
	return nil, ErrInternal
}

// SessionContextRead asks the host who is signed in on the request this
// add-on is answering. It is the *read* half of the session boundary and
// the whole of it: what comes back is an identity and where it is working,
// never a cookie, a token or a session row, so an add-on can draw a page
// for the person in front of it and cannot act as them anywhere else.
// Nobody signed in is not an error — add-on routes are reachable without
// a session, because a sign-in flow could not otherwise begin — so the
// record's `signed_in` is false and every other field is empty. Outside a
// request it is ErrNotFound, which is what a module calling it from package
// initialization gets. Minting a session is session_mint and is a different
// grant.
//
// ABI: linkctrl.session_context, since 0.1.0; implemented since this
// version.
//
// Requires the session.context permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func SessionContextRead() ([]byte, error) {
	buf := make([]byte, initialBuffer)
	for attempt := 0; attempt < growthAttempts; attempt++ {
		n := wasmSessionContextRead(bytesPtr(buf), uint32(len(buf)))
		runtime.KeepAlive(buf)
		if n < 0 {
			return nil, statusError(n)
		}
		if int(n) <= len(buf) {
			return buf[:n:n], nil
		}
		buf = make([]byte, n)
	}
	return nil, ErrInternal
}

// SessionMint tells the host that this add-on authenticated somebody, and
// asks for a session. The add-on does not make a session and never sees a
// token: it makes an assertion, the host decides whether an account exists
// for it and what the session may do, and the cookie is written by the
// host. That split is what keeps the host, and not an add-on, the authority
// over who is signed in. What comes back is a MintedSession, and it is
// enumerated for the same reason the claim is: an answer described only as
// "a JSON object" is an answer the credential assertion over this surface
// cannot read. A host that does not implement it yet answers
// ErrNotAvailable.
//
// claim is who authenticated, as a SessionClaim record.
//
// ABI: linkctrl.session_mint, since 0.1.0; declared, and not implemented by
// every host: a host without it answers ErrNotAvailable, which a module may
// branch on.
//
// Requires the session.mint permission, declared in this add-on's manifest.
// A module that did not declare it gets ErrDenied, whether or not the host
// implements the function.
func SessionMint(claim []byte) ([]byte, error) {
	buf := make([]byte, initialBuffer)
	for attempt := 0; attempt < growthAttempts; attempt++ {
		n := wasmSessionMint(bytesPtr(claim), uint32(len(claim)), bytesPtr(buf), uint32(len(buf)))
		runtime.KeepAlive(claim)
		runtime.KeepAlive(buf)
		if n < 0 {
			return nil, statusError(n)
		}
		if int(n) <= len(buf) {
			return buf[:n:n], nil
		}
		buf = make([]byte, n)
	}
	return nil, ErrInternal
}

// RedirectEventRead reads the redirect this add-on is observing. What it
// carries is at most what click_events may carry — prefix-derived and
// country-level, and no client address in any form. The grant it costs is
// redirect.observe, which is out-of-band observation and nothing more:
// running inside the redirect path itself is redirect.inline, a separate
// declaration no host grants yet, so a module cannot reach the path by
// holding this. A host that does not implement it yet answers
// ErrNotAvailable.
//
// ABI: linkctrl.redirect_event_read, since 0.1.0; declared, and not
// implemented by every host: a host without it answers ErrNotAvailable,
// which a module may branch on.
//
// Requires the redirect.observe permission, declared in this add-on's
// manifest. A module that did not declare it gets ErrDenied, whether or not
// the host implements the function.
func RedirectEventRead() ([]byte, error) {
	buf := make([]byte, initialBuffer)
	for attempt := 0; attempt < growthAttempts; attempt++ {
		n := wasmRedirectEventRead(bytesPtr(buf), uint32(len(buf)))
		runtime.KeepAlive(buf)
		if n < 0 {
			return nil, statusError(n)
		}
		if int(n) <= len(buf) {
			return buf[:n:n], nil
		}
		buf = make([]byte, n)
	}
	return nil, ErrInternal
}
