// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addonauth.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAddonIdentityLink = `-- name: CreateAddonIdentityLink :one
INSERT INTO addon_identity_links (id, user_id, addon, issuer, subject)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (addon, issuer, subject) DO NOTHING
RETURNING id, user_id, addon, issuer, subject, created_at, last_used_at
`

type CreateAddonIdentityLinkParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Addon   string
	Issuer  string
	Subject string
}

// Connect a provider to the account of the person who is signed in.
//
// **The only writer, and it takes a user id the caller resolved from a session.**
// That is the deliberate half of the linking flow: nothing an add-on asserts
// reaches this statement, so an add-on cannot create the mapping it will later be
// believed on. `ON CONFLICT DO NOTHING` on the unique key makes a second attempt
// at the same connection idempotent rather than an error page; a conflict with a
// *different* account returns no row, and the caller reports that the subject is
// already connected somewhere else rather than moving it.
func (q *Queries) CreateAddonIdentityLink(ctx context.Context, arg CreateAddonIdentityLinkParams) (AddonIdentityLink, error) {
	row := q.db.QueryRow(ctx, createAddonIdentityLink,
		arg.ID,
		arg.UserID,
		arg.Addon,
		arg.Issuer,
		arg.Subject,
	)
	var i AddonIdentityLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Addon,
		&i.Issuer,
		&i.Subject,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const resolveAddonIdentityLink = `-- name: ResolveAddonIdentityLink :one
SELECT l.id,
       l.user_id,
       u.email,
       u.name,
       u.status,
       u.locked_until,
       u.mfa_enabled_at
  FROM addon_identity_links l
  JOIN users u ON u.id = l.user_id
 WHERE l.addon = $1
   AND l.issuer = $2
   AND l.subject = $3
   AND u.deleted_at IS NULL
`

type ResolveAddonIdentityLinkParams struct {
	Addon   string
	Issuer  string
	Subject string
}

type ResolveAddonIdentityLinkRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Email        string
	Name         string
	Status       string
	LockedUntil  *time.Time
	MfaEnabledAt *time.Time
}

// The only statement in this product that turns an add-on's assertion into an
// account, and the whole of what "linking is explicit" enforces.
//
// Three columns in the predicate and no fourth. There is deliberately no variant
// of this keyed on the email address an assertion carries: that is the
// account-takeover shape m65.md names, and the way it stays absent is that the
// statement which would perform it does not exist.
//
// The user's own row comes back with it, so the caller decides about status and
// lockout from one read rather than from a second lookup that could disagree with
// this one about which account it is talking about.
func (q *Queries) ResolveAddonIdentityLink(ctx context.Context, arg ResolveAddonIdentityLinkParams) (ResolveAddonIdentityLinkRow, error) {
	row := q.db.QueryRow(ctx, resolveAddonIdentityLink, arg.Addon, arg.Issuer, arg.Subject)
	var i ResolveAddonIdentityLinkRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.LockedUntil,
		&i.MfaEnabledAt,
	)
	return i, err
}

const touchAddonIdentityLink = `-- name: TouchAddonIdentityLink :exec
UPDATE addon_identity_links SET last_used_at = now() WHERE id = $1
`

// Record that this link minted a session. Best-effort at the call site: a session
// that exists and a timestamp that did not move is a worse outcome than the
// reverse, so the caller logs a failure here rather than failing the sign-in.
func (q *Queries) TouchAddonIdentityLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAddonIdentityLink, id)
	return err
}
