// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countClickEvents = `-- name: CountClickEvents :one
SELECT count(*) FROM click_events WHERE workspace_id = $1
`

func (q *Queries) CountClickEvents(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClickEvents, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSalt = `-- name: CreateSalt :one
INSERT INTO analytics_salts (valid_on, salt, purge_at)
VALUES ($1, $2, $3)
ON CONFLICT (valid_on) DO NOTHING
RETURNING salt
`

type CreateSaltParams struct {
	ValidOn time.Time
	Salt    []byte
	PurgeAt time.Time
}

// ON CONFLICT DO NOTHING returns no row when another replica inserted first,
// which the caller detects and re-reads. Two replicas using different salts
// for the same day would split every visitor in two.
func (q *Queries) CreateSalt(ctx context.Context, arg CreateSaltParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createSalt, arg.ValidOn, arg.Salt, arg.PurgeAt)
	var salt []byte
	err := row.Scan(&salt)
	return salt, err
}

const getLinkDimensions = `-- name: GetLinkDimensions :many
SELECT value, sum(clicks)::bigint AS clicks, sum(unique_visitors)::bigint AS unique_visitors
FROM link_dimension_daily
WHERE link_id = $1
  AND dimension = $2
  AND day >= $3::date
  AND day <= $4::date
GROUP BY value
ORDER BY clicks DESC, value
LIMIT $5
`

type GetLinkDimensionsParams struct {
	LinkID    uuid.UUID
	Dimension string
	FromDay   time.Time
	ToDay     time.Time
	RowLimit  int32
}

type GetLinkDimensionsRow struct {
	Value          string
	Clicks         int64
	UniqueVisitors int64
}

func (q *Queries) GetLinkDimensions(ctx context.Context, arg GetLinkDimensionsParams) ([]GetLinkDimensionsRow, error) {
	rows, err := q.db.Query(ctx, getLinkDimensions,
		arg.LinkID,
		arg.Dimension,
		arg.FromDay,
		arg.ToDay,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLinkDimensionsRow{}
	for rows.Next() {
		var i GetLinkDimensionsRow
		if err := rows.Scan(&i.Value, &i.Clicks, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkStats = `-- name: GetLinkStats :many
SELECT day, clicks, unique_visitors, bot_clicks
FROM link_click_daily
WHERE link_id = $1
  AND day >= $2::date
  AND day <= $3::date
ORDER BY day
`

type GetLinkStatsParams struct {
	LinkID  uuid.UUID
	FromDay time.Time
	ToDay   time.Time
}

type GetLinkStatsRow struct {
	Day            time.Time
	Clicks         int64
	UniqueVisitors int64
	BotClicks      int64
}

// Reads the rollup, never the raw events. This is what keeps analytics under
// the 2s target as click_events grows into the tens of millions.
func (q *Queries) GetLinkStats(ctx context.Context, arg GetLinkStatsParams) ([]GetLinkStatsRow, error) {
	rows, err := q.db.Query(ctx, getLinkStats, arg.LinkID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLinkStatsRow{}
	for rows.Next() {
		var i GetLinkStatsRow
		if err := rows.Scan(
			&i.Day,
			&i.Clicks,
			&i.UniqueVisitors,
			&i.BotClicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentClicks = `-- name: GetRecentClicks :many
SELECT occurred_at, device, browser, os, country, referrer_host, is_bot
FROM click_events
WHERE link_id = $1
ORDER BY occurred_at DESC
LIMIT $2
`

type GetRecentClicksParams struct {
	LinkID   uuid.UUID
	RowLimit int32
}

type GetRecentClicksRow struct {
	OccurredAt   time.Time
	Device       *string
	Browser      *string
	Os           *string
	Country      *string
	ReferrerHost *string
	IsBot        bool
}

// The live-activity feed. Bounded and index-backed on (link_id, occurred_at).
func (q *Queries) GetRecentClicks(ctx context.Context, arg GetRecentClicksParams) ([]GetRecentClicksRow, error) {
	rows, err := q.db.Query(ctx, getRecentClicks, arg.LinkID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentClicksRow{}
	for rows.Next() {
		var i GetRecentClicksRow
		if err := rows.Scan(
			&i.OccurredAt,
			&i.Device,
			&i.Browser,
			&i.Os,
			&i.Country,
			&i.ReferrerHost,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalt = `-- name: GetSalt :one

SELECT salt FROM analytics_salts WHERE valid_on = $1
`

// Analytics: salts, rollups and reads.
func (q *Queries) GetSalt(ctx context.Context, validOn time.Time) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSalt, validOn)
	var salt []byte
	err := row.Scan(&salt)
	return salt, err
}

const getWorkspaceStats = `-- name: GetWorkspaceStats :many
SELECT day, clicks, unique_visitors, bot_clicks, active_links
FROM workspace_click_daily
WHERE workspace_id = $1
  AND day >= $2::date
  AND day <= $3::date
ORDER BY day
`

type GetWorkspaceStatsParams struct {
	WorkspaceID uuid.UUID
	FromDay     time.Time
	ToDay       time.Time
}

type GetWorkspaceStatsRow struct {
	Day            time.Time
	Clicks         int64
	UniqueVisitors int64
	BotClicks      int64
	ActiveLinks    int64
}

func (q *Queries) GetWorkspaceStats(ctx context.Context, arg GetWorkspaceStatsParams) ([]GetWorkspaceStatsRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceStats, arg.WorkspaceID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkspaceStatsRow{}
	for rows.Next() {
		var i GetWorkspaceStatsRow
		if err := rows.Scan(
			&i.Day,
			&i.Clicks,
			&i.UniqueVisitors,
			&i.BotClicks,
			&i.ActiveLinks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceTotals = `-- name: GetWorkspaceTotals :one
SELECT
    coalesce(sum(clicks), 0)::bigint          AS clicks,
    coalesce(sum(unique_visitors), 0)::bigint AS unique_visitors,
    coalesce(sum(bot_clicks), 0)::bigint      AS bot_clicks
FROM workspace_click_daily
WHERE workspace_id = $1
  AND day >= $2::date
  AND day <= $3::date
`

type GetWorkspaceTotalsParams struct {
	WorkspaceID uuid.UUID
	FromDay     time.Time
	ToDay       time.Time
}

type GetWorkspaceTotalsRow struct {
	Clicks         int64
	UniqueVisitors int64
	BotClicks      int64
}

// Summing daily uniques over-counts anyone visiting on more than one day.
// Reported as "unique visitors per day, summed" in the UI rather than
// presented as a distinct-person count, because the exact figure cannot be
// recovered once the salts are purged. That is the intended trade.
func (q *Queries) GetWorkspaceTotals(ctx context.Context, arg GetWorkspaceTotalsParams) (GetWorkspaceTotalsRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceTotals, arg.WorkspaceID, arg.FromDay, arg.ToDay)
	var i GetWorkspaceTotalsRow
	err := row.Scan(&i.Clicks, &i.UniqueVisitors, &i.BotClicks)
	return i, err
}

const purgeExpiredSalts = `-- name: PurgeExpiredSalts :execrows
DELETE FROM analytics_salts WHERE purge_at < now()
`

// The de-identification step. Once the salt is gone the day's hashes cannot be
// linked back to an address.
func (q *Queries) PurgeExpiredSalts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredSalts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rollupDimensionDaily = `-- name: RollupDimensionDaily :exec
INSERT INTO link_dimension_daily (link_id, workspace_id, day, dimension, value, clicks, unique_visitors)
SELECT link_id, workspace_id, day, dimension, value,
       count(*)                     AS clicks,
       count(DISTINCT visitor_hash) AS unique_visitors
FROM (
    SELECT ce.link_id, ce.workspace_id, (ce.occurred_at AT TIME ZONE 'UTC')::date AS day,
           'device' AS dimension, coalesce(ce.device, 'unknown') AS value, ce.visitor_hash
      FROM click_events ce
     WHERE ce.occurred_at >= $1 AND ce.occurred_at < $2 AND NOT ce.is_bot
    UNION ALL
    SELECT ce.link_id, ce.workspace_id, (ce.occurred_at AT TIME ZONE 'UTC')::date,
           'browser', coalesce(ce.browser, 'Other'), ce.visitor_hash
      FROM click_events ce
     WHERE ce.occurred_at >= $1 AND ce.occurred_at < $2 AND NOT ce.is_bot
    UNION ALL
    SELECT ce.link_id, ce.workspace_id, (ce.occurred_at AT TIME ZONE 'UTC')::date,
           'os', coalesce(ce.os, 'Other'), ce.visitor_hash
      FROM click_events ce
     WHERE ce.occurred_at >= $1 AND ce.occurred_at < $2 AND NOT ce.is_bot
    UNION ALL
    SELECT ce.link_id, ce.workspace_id, (ce.occurred_at AT TIME ZONE 'UTC')::date,
           'country', coalesce(ce.country, 'unknown'), ce.visitor_hash
      FROM click_events ce
     WHERE ce.occurred_at >= $1 AND ce.occurred_at < $2 AND NOT ce.is_bot
    UNION ALL
    SELECT ce.link_id, ce.workspace_id, (ce.occurred_at AT TIME ZONE 'UTC')::date,
           'referrer', coalesce(nullif(ce.referrer_host, ''), 'direct'), ce.visitor_hash
      FROM click_events ce
     WHERE ce.occurred_at >= $1 AND ce.occurred_at < $2 AND NOT ce.is_bot
    UNION ALL
    SELECT ce.link_id, ce.workspace_id, (ce.occurred_at AT TIME ZONE 'UTC')::date,
           'language', coalesce(nullif(ce.language, ''), 'unknown'), ce.visitor_hash
      FROM click_events ce
     WHERE ce.occurred_at >= $1 AND ce.occurred_at < $2 AND NOT ce.is_bot
) d
GROUP BY link_id, workspace_id, day, dimension, value
ON CONFLICT (link_id, day, dimension, value) DO UPDATE
   SET clicks = EXCLUDED.clicks,
       unique_visitors = EXCLUDED.unique_visitors
`

type RollupDimensionDailyParams struct {
	WindowStart time.Time
	WindowEnd   time.Time
}

// One statement per dimension via UNION ALL, rather than eight round trips.
func (q *Queries) RollupDimensionDaily(ctx context.Context, arg RollupDimensionDailyParams) error {
	_, err := q.db.Exec(ctx, rollupDimensionDaily, arg.WindowStart, arg.WindowEnd)
	return err
}

const rollupLinkDaily = `-- name: RollupLinkDaily :exec
INSERT INTO link_click_daily (link_id, workspace_id, day, clicks, unique_visitors, bot_clicks)
SELECT
    ce.link_id,
    ce.workspace_id,
    (ce.occurred_at AT TIME ZONE 'UTC')::date AS day,
    count(*) FILTER (WHERE NOT ce.is_bot)                        AS clicks,
    count(DISTINCT ce.visitor_hash) FILTER (WHERE NOT ce.is_bot) AS unique_visitors,
    count(*) FILTER (WHERE ce.is_bot)                            AS bot_clicks
FROM click_events ce
WHERE ce.occurred_at >= $1
  AND ce.occurred_at <  $2
GROUP BY ce.link_id, ce.workspace_id, 3
ON CONFLICT (link_id, day) DO UPDATE
   SET clicks = EXCLUDED.clicks,
       unique_visitors = EXCLUDED.unique_visitors,
       bot_clicks = EXCLUDED.bot_clicks
`

type RollupLinkDailyParams struct {
	WindowStart time.Time
	WindowEnd   time.Time
}

// Recompute per-link daily totals for a window.
//
// Idempotent by construction: it recomputes a whole day from the raw events
// and upserts, so running it twice, or after a crash mid-run, converges to the
// same numbers. An incremental "add what is new" design would double-count on
// any retry.
func (q *Queries) RollupLinkDaily(ctx context.Context, arg RollupLinkDailyParams) error {
	_, err := q.db.Exec(ctx, rollupLinkDaily, arg.WindowStart, arg.WindowEnd)
	return err
}

const rollupWorkspaceDaily = `-- name: RollupWorkspaceDaily :exec
INSERT INTO workspace_click_daily (workspace_id, day, clicks, unique_visitors, bot_clicks, active_links)
SELECT
    ce.workspace_id,
    (ce.occurred_at AT TIME ZONE 'UTC')::date,
    count(*) FILTER (WHERE NOT ce.is_bot),
    count(DISTINCT ce.visitor_hash) FILTER (WHERE NOT ce.is_bot),
    count(*) FILTER (WHERE ce.is_bot),
    count(DISTINCT ce.link_id)
FROM click_events ce
WHERE ce.occurred_at >= $1
  AND ce.occurred_at <  $2
GROUP BY ce.workspace_id, 2
ON CONFLICT (workspace_id, day) DO UPDATE
   SET clicks = EXCLUDED.clicks,
       unique_visitors = EXCLUDED.unique_visitors,
       bot_clicks = EXCLUDED.bot_clicks,
       active_links = EXCLUDED.active_links
`

type RollupWorkspaceDailyParams struct {
	WindowStart time.Time
	WindowEnd   time.Time
}

func (q *Queries) RollupWorkspaceDaily(ctx context.Context, arg RollupWorkspaceDailyParams) error {
	_, err := q.db.Exec(ctx, rollupWorkspaceDaily, arg.WindowStart, arg.WindowEnd)
	return err
}
