// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    id, user_id, organization_id, workspace_id,
    name, prefix, key_hash, scopes, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, organization_id, workspace_id, name, prefix, key_hash, scopes, last_used_at, expires_at, revoked_at, created_at, rotated_at, grace_expires_at, successor_id
`

type CreateAPIKeyParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID *uuid.UUID
	WorkspaceID    *uuid.UUID
	Name           string
	Prefix         string
	KeyHash        []byte
	Scopes         []string
	ExpiresAt      *time.Time
}

// API keys and the permission vocabulary their scopes are drawn from.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.GraceExpiresAt,
		&i.SuccessorID,
	)
	return i, err
}

const deleteRevokedAPIKeys = `-- name: DeleteRevokedAPIKeys :execrows
DELETE FROM api_keys
WHERE revoked_at IS NOT NULL
  AND revoked_at < now() - interval '90 days'
`

// Reaper. Kept long enough to be visible in the key list after revocation, and
// long enough for the audit question above to be answerable.
func (q *Queries) DeleteRevokedAPIKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevokedAPIKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT
    k.id, k.user_id, k.organization_id, k.workspace_id,
    k.key_hash, k.scopes, k.expires_at, k.revoked_at, k.grace_expires_at,
    u.email, u.name AS user_name, u.status,
    EXISTS (
        SELECT 1 FROM memberships m
         WHERE m.user_id = k.user_id
           AND (m.workspace_id IS NULL OR m.workspace_id = k.workspace_id)
           AND (CASE
                  WHEN k.organization_id IS NOT NULL
                    THEN m.organization_id = k.organization_id
                  ELSE NOT EXISTS (
                         SELECT 1 FROM api_key_org_revocations x
                          WHERE x.api_key_id = k.id
                            AND x.organization_id = m.organization_id)
                END)
    ) AS owner_is_member
FROM api_keys k
JOIN users u ON u.id = k.user_id
WHERE k.prefix = $1
  AND u.deleted_at IS NULL
`

type GetAPIKeyByPrefixRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID *uuid.UUID
	WorkspaceID    *uuid.UUID
	KeyHash        []byte
	Scopes         []string
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	GraceExpiresAt *time.Time
	Email          string
	UserName       string
	Status         string
	OwnerIsMember  bool
}

// The verification lookup, on the unique prefix index, joined with the user so
// authentication is one round trip. Revoked and expired keys are returned
// rather than filtered out: the caller distinguishes them so the response can
// say which it was, and a deleted user's key resolves to no row at all.
//
// grace_expires_at comes back for the same reason revoked_at does: a rotated
// predecessor stops verifying when its window closes, and that refusal is
// decided here rather than by the housekeeping job that later writes revoked_at.
//
// owner_is_member is the membership the key leans on, asked here so that
// authentication stays one round trip. A key acts *as its owner*, and an owner
// with no membership covering the key's scope has no authority for it to act
// with — so the credential is invalid rather than merely powerless. The
// predicate matches GetUserPermissions exactly: an organization-wide membership
// covers every workspace, a workspace-scoped one covers its own, and an
// unpinned key is covered only by an organization-wide membership, because
// NULL = NULL is not true.
//
// **Which organization it asks about is no longer the key's column** (M54). A
// pinned key still asks about the organization it names, and that branch is
// unchanged. An account-wide one has no column to ask about: it asks whether
// the owner holds an organization-wide membership in *any* organization this
// key has not been barred from, which is the same question one step earlier —
// can this credential reach anywhere at all. Which organization it then lands
// in is ResolveOrganizationForAPIKey's, and the membership covering that one is
// guaranteed by the same join, so the precise test and this coarse one cannot
// disagree.
//
// Returned as a column rather than joined into the WHERE clause for the reason
// revoked and expired keys are returned rather than filtered: the caller decides
// what each state means, and a refusal a reader can see beside the others is
// worth more than a row that silently fails to exist.
func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i GetAPIKeyByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.KeyHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.GraceExpiresAt,
		&i.Email,
		&i.UserName,
		&i.Status,
		&i.OwnerIsMember,
	)
	return i, err
}

const getAPIKeyForRotation = `-- name: GetAPIKeyForRotation :one
SELECT k.id, k.user_id, k.organization_id, k.workspace_id, k.name, k.prefix,
       k.scopes, k.expires_at, k.revoked_at, k.rotated_at, k.grace_expires_at,
       k.successor_id, k.created_at,
       EXISTS (
           SELECT 1 FROM memberships m
            WHERE m.user_id = k.user_id
              AND (m.workspace_id IS NULL OR m.workspace_id = k.workspace_id)
              AND (CASE
                     WHEN k.organization_id IS NOT NULL
                       THEN m.organization_id = k.organization_id
                     ELSE NOT EXISTS (
                            SELECT 1 FROM api_key_org_revocations x
                             WHERE x.api_key_id = k.id
                               AND x.organization_id = m.organization_id)
                   END)
       ) AS owner_is_member,
       COALESCE((SELECT u.status FROM users u
                  WHERE u.id = k.user_id AND u.deleted_at IS NULL), 'deleted') AS owner_status
FROM api_keys k
WHERE k.id = $1
FOR UPDATE
`

type GetAPIKeyForRotationRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID *uuid.UUID
	WorkspaceID    *uuid.UUID
	Name           string
	Prefix         string
	Scopes         []string
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	RotatedAt      *time.Time
	GraceExpiresAt *time.Time
	SuccessorID    *uuid.UUID
	CreatedAt      time.Time
	OwnerIsMember  bool
	OwnerStatus    interface{}
}

// The predecessor, locked, so two rotations of one key serialize instead of
// racing.
//
// FOR UPDATE rather than an optimistic conditional write: the loser of a race
// should be told "this key has already been rotated" by the check that follows,
// which is a sentence somebody can act on, not have its transaction rolled back
// by a unique-index violation on a column it never named.
//
// owner_is_member and owner_status come back for the reason revoked_at does:
// they are re-read here, under the lock, so a membership removed or an account
// deactivated between authentication and this statement wins. Without them a
// removal racing a rotation leaves behind a successor the removal was meant to
// kill, on a chain that can rotate again. A soft-deleted account reads
// 'deleted' rather than NULL, so the one comparison at the call site covers it
// and no branch depends on a scan of an absent row.
func (q *Queries) GetAPIKeyForRotation(ctx context.Context, id uuid.UUID) (GetAPIKeyForRotationRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyForRotation, id)
	var i GetAPIKeyForRotationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedAt,
		&i.GraceExpiresAt,
		&i.SuccessorID,
		&i.CreatedAt,
		&i.OwnerIsMember,
		&i.OwnerStatus,
	)
	return i, err
}

const getAPIKeyReach = `-- name: GetAPIKeyReach :one
SELECT k.id, k.user_id, k.organization_id, k.prefix, k.revoked_at
FROM api_keys k
WHERE k.id = $1
`

type GetAPIKeyReachRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID *uuid.UUID
	Prefix         string
	RevokedAt      *time.Time
}

// The reach of a key named by id, for the administrator's arm of Revoke (M54).
//
// Read before the write because the write depends on the answer: a pinned key
// is revoked outright and an account-wide one has an organization cut out of
// it, and those are different statements against different tables. Returns the
// owner too, because whichever it turns out to be, the record has to name whose
// credential was stopped.
//
// No organization predicate, deliberately. Scoping the *read* would make an
// account-wide key unfindable by every administrator, since it matches none of
// them; the authorization is at the call site, which refuses unless the owner
// is a member of the organization the actor holds authority in. A key whose
// owner has never been in the actor's organization is ErrNotFound, exactly as an
// unknown id is.
func (q *Queries) GetAPIKeyReach(ctx context.Context, id uuid.UUID) (GetAPIKeyReachRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyReach, id)
	var i GetAPIKeyReachRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.Prefix,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeysForUser = `-- name: ListAPIKeysForUser :many
SELECT id, name, prefix, scopes, organization_id, workspace_id, last_used_at,
       expires_at, revoked_at, rotated_at, grace_expires_at, successor_id,
       created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysForUserRow struct {
	ID             uuid.UUID
	Name           string
	Prefix         string
	Scopes         []string
	OrganizationID *uuid.UUID
	WorkspaceID    *uuid.UUID
	LastUsedAt     *time.Time
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	RotatedAt      *time.Time
	GraceExpiresAt *time.Time
	SuccessorID    *uuid.UUID
	CreatedAt      time.Time
}

// Revoked keys are included. "Which keys existed and when were they revoked"
// is the question asked after an incident, so they are listed until the reaper
// removes them.
//
// workspace_id is selected because NULL is a state the owner chose (M44): a key
// bound to one workspace and a key valid across the organization look identical
// without it. organization_id is selected for the same reason one tier up
// (M54): NULL there is account-wide and non-NULL is pinned, and a list that
// omitted it would show two credentials with different reach as one row shape.
//
// **Owner alone, no organization predicate** (M54, closing F75). It used to
// carry `AND organization_id = $2` while RevokeAPIKey carried only the owner,
// and the two statements disagreeing about which keys an actor reaches was the
// whole of that finding: a key listed nowhere still revoked, so 204-versus-404
// answered "is this id one of mine, elsewhere". They agree now because the
// question they both ask is the same one — whose key is this — and an
// account-wide key has no organization to filter on in the first place.
func (q *Queries) ListAPIKeysForUser(ctx context.Context, userID uuid.UUID) ([]ListAPIKeysForUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysForUserRow{}
	for rows.Next() {
		var i ListAPIKeysForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Scopes,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RotatedAt,
			&i.GraceExpiresAt,
			&i.SuccessorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionSlugs = `-- name: ListPermissionSlugs :many
SELECT slug FROM permissions ORDER BY slug
`

// The scope vocabulary. Scopes are validated against the permissions table
// rather than a list in Go, so RBAC and API keys cannot drift apart.
func (q *Queries) ListPermissionSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAPIKeyRotated = `-- name: MarkAPIKeyRotated :execrows
UPDATE api_keys
   SET rotated_at = now(),
       grace_expires_at = $2,
       successor_id = $3
 WHERE id = $1
   AND successor_id IS NULL
`

type MarkAPIKeyRotatedParams struct {
	ID             uuid.UUID
	GraceExpiresAt *time.Time
	SuccessorID    *uuid.UUID
}

// Closes the predecessor: names its successor and sets the far edge of the
// grace window.
//
// `successor_id IS NULL` in the WHERE clause is belt to the FOR UPDATE braces.
// The lock is what serializes; this is what makes the second writer a no-op
// rather than a silent overwrite if the lock is ever dropped from the read.
func (q *Queries) MarkAPIKeyRotated(ctx context.Context, arg MarkAPIKeyRotatedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAPIKeyRotated, arg.ID, arg.GraceExpiresAt, arg.SuccessorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveOrganizationForAPIKey = `-- name: ResolveOrganizationForAPIKey :one
SELECT o.id
FROM organizations o
JOIN memberships m ON m.organization_id = o.id
                  AND m.user_id = $1
                  AND m.workspace_id IS NULL
JOIN users u ON u.id = m.user_id
LEFT JOIN workspaces dw ON dw.id = u.default_workspace_id AND dw.deleted_at IS NULL
LEFT JOIN workspaces lw ON lw.id = u.last_workspace_id    AND lw.deleted_at IS NULL
WHERE o.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM api_key_org_revocations x
       WHERE x.api_key_id = $2
         AND x.organization_id = o.id
  )
ORDER BY
    (o.id IS NOT DISTINCT FROM dw.organization_id) DESC,
    (o.id IS NOT DISTINCT FROM lw.organization_id) DESC,
    o.created_at, o.id
LIMIT 1
`

type ResolveOrganizationForAPIKeyParams struct {
	UserID   uuid.UUID
	ApiKeyID uuid.UUID
}

// Which organization an **account-wide** key's request lands in (M54).
//
// One tier above ResolveWorkspaceForUser, and deliberately not a second copy of
// it. That statement answers "which workspace, given a person and optionally a
// bound"; this one answers "which tenant", and the answer then becomes M44's
// organization_id bound so the workspace precedence stays stated exactly once.
// Feeding it the organization the request resolved to is the whole of M44's
// parameter surviving a key that has no organization column to feed it from.
//
// The rungs are the person's, for the reason D90 gives: what an unpinned key
// follows is the person, and where the person is acting is part of that. Their
// pinned default's organization wins, then the one they last used, then the
// oldest they belong to. There is no session rung because there is no session.
//
// **Organization-wide memberships only.** An unpinned key has always required
// one — GetAPIKeyByPrefix's predicate refuses a workspace-NULL key covered by a
// workspace-scoped membership, and MayCreateOrgWide refuses to mint one without
// it. Carrying that rule across the tenancy boundary is what stops an
// account-wide key widening into an organization where its owner is scoped to a
// single workspace: a key minted under organization-wide authority must not
// acquire reach its owner could not have granted it there.
//
// Barred organizations are excluded here as well as in the coarse check, and
// both matter: the coarse one decides whether the credential authenticates at
// all, this one decides where it lands, and an administrator who cut their
// tenant out must not be reachable by a key that simply had nowhere else to go.
func (q *Queries) ResolveOrganizationForAPIKey(ctx context.Context, arg ResolveOrganizationForAPIKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveOrganizationForAPIKey, arg.UserID, arg.ApiKeyID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
   SET revoked_at = COALESCE(revoked_at, now())
 WHERE id = $1
   AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Idempotent: revoking an already-revoked key keeps the original timestamp and
// still reports one row, so a repeated call is a success rather than a 404
// while a genuinely unknown id is still distinguishable.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIKeyInOrganization = `-- name: RevokeAPIKeyInOrganization :one
UPDATE api_keys
   SET revoked_at = COALESCE(revoked_at, now())
 WHERE id = $1
   AND organization_id = $2
RETURNING user_id, prefix
`

type RevokeAPIKeyInOrganizationParams struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
}

type RevokeAPIKeyInOrganizationRow struct {
	UserID uuid.UUID
	Prefix string
}

// The administrator's revoke, keyed on the organization instead of on the
// owner.
//
// RevokeAPIKey above is a person disabling their own credential and is the
// normal path. This one exists because there was otherwise no path at all: a key
// belonging to somebody else could be *seen* — the rotation records are
// organization-scoped — and not stopped, so an administrator holding an incident
// had to wait for its owner. Scoped by organization rather than by workspace
// because a key is issued into an organization and its id is what an audit
// record hands the reader.
//
// Returns the owner and the prefix rather than a row count, because this write
// is audited and the record has to name whose credential was stopped. No row
// means an id from another organization or none at all, and both answer the same
// way at the call site.
//
// **Pinned keys only** since M54, and by the predicate rather than by a new
// clause: `organization_id = $2` is never true of a NULL. That is the right
// refusal rather than a gap. This statement destroys a credential outright, and
// for a pinned key that is proportionate — the organization is the key's entire
// reach, so cutting the reach and cutting the key are the same act. An
// account-wide key belongs to an account that acts in tenants this administrator
// has no authority over, and RevokeAPIKeyReachInOrganization below is what they
// get instead.
func (q *Queries) RevokeAPIKeyInOrganization(ctx context.Context, arg RevokeAPIKeyInOrganizationParams) (RevokeAPIKeyInOrganizationRow, error) {
	row := q.db.QueryRow(ctx, revokeAPIKeyInOrganization, arg.ID, arg.OrganizationID)
	var i RevokeAPIKeyInOrganizationRow
	err := row.Scan(&i.UserID, &i.Prefix)
	return i, err
}

const revokeAPIKeyReachInOrganization = `-- name: RevokeAPIKeyReachInOrganization :execrows
INSERT INTO api_key_org_revocations (api_key_id, organization_id, revoked_by)
VALUES ($1, $2, $3)
ON CONFLICT (api_key_id, organization_id) DO NOTHING
`

type RevokeAPIKeyReachInOrganizationParams struct {
	ApiKeyID       uuid.UUID
	OrganizationID uuid.UUID
	RevokedBy      *uuid.UUID
}

// An administrator cutting their organization out of an account-wide key.
//
// Idempotent for the reason RevokeAPIKey is: the second call reports a row and
// keeps the original timestamp, so repeating it is a success rather than a 404,
// while an id nobody may act on is still distinguishable.
//
// ON CONFLICT rather than a prior existence check, because two administrators
// reacting to the same incident is the normal case and neither should see an
// error about the other.
func (q *Queries) RevokeAPIKeyReachInOrganization(ctx context.Context, arg RevokeAPIKeyReachInOrganizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKeyReachInOrganization, arg.ApiKeyID, arg.OrganizationID, arg.RevokedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLapsedAPIKeyGraces = `-- name: RevokeLapsedAPIKeyGraces :execrows
UPDATE api_keys
   SET revoked_at = grace_expires_at
 WHERE revoked_at IS NULL
   AND grace_expires_at IS NOT NULL
   AND grace_expires_at <= now()
`

// Auto-revocation, from housekeeping.
//
// revoked_at is set to the moment the window closed rather than to now(), so
// the list says when the key stopped working instead of when the job noticed.
// Nothing depends on this running: authentication already refuses a key past
// grace_expires_at. What this buys is a key list that agrees with the behaviour.
func (q *Queries) RevokeLapsedAPIKeyGraces(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLapsedAPIKeyGraces)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKeys = `-- name: TouchAPIKeys :exec
UPDATE api_keys AS k
   SET last_used_at = GREATEST(COALESCE(k.last_used_at, to_timestamp(0)), v.used_at)
  FROM (
      SELECT unnest($1::uuid[])          AS id,
             unnest($2::timestamptz[]) AS used_at
  ) AS v
 WHERE k.id = v.id
`

type TouchAPIKeysParams struct {
	Ids    []uuid.UUID
	UsedAt []time.Time
}

// Batch write of last_used_at, from the coalescing tracker rather than from the
// request path: authenticating a key must not cost a synchronous write.
//
// GREATEST guards against a late batch moving the timestamp backwards, which
// two processes flushing out of order would otherwise do.
func (q *Queries) TouchAPIKeys(ctx context.Context, arg TouchAPIKeysParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeys, arg.Ids, arg.UsedAt)
	return err
}
