// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    id, user_id, organization_id, workspace_id,
    name, prefix, key_hash, scopes, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, organization_id, workspace_id, name, prefix, key_hash, scopes, last_used_at, expires_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	WorkspaceID    *uuid.UUID
	Name           string
	Prefix         string
	KeyHash        []byte
	Scopes         []string
	ExpiresAt      *time.Time
}

// API keys and the permission vocabulary their scopes are drawn from.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRevokedAPIKeys = `-- name: DeleteRevokedAPIKeys :execrows
DELETE FROM api_keys
WHERE revoked_at IS NOT NULL
  AND revoked_at < now() - interval '90 days'
`

// Reaper. Kept long enough to be visible in the key list after revocation, and
// long enough for the audit question above to be answerable.
func (q *Queries) DeleteRevokedAPIKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevokedAPIKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT
    k.id, k.user_id, k.organization_id, k.workspace_id,
    k.key_hash, k.scopes, k.expires_at, k.revoked_at,
    u.email, u.name AS user_name, u.status
FROM api_keys k
JOIN users u ON u.id = k.user_id
WHERE k.prefix = $1
  AND u.deleted_at IS NULL
`

type GetAPIKeyByPrefixRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	WorkspaceID    *uuid.UUID
	KeyHash        []byte
	Scopes         []string
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	Email          string
	UserName       string
	Status         string
}

// The verification lookup, on the unique prefix index, joined with the user so
// authentication is one round trip. Revoked and expired keys are returned
// rather than filtered out: the caller distinguishes them so the response can
// say which it was, and a deleted user's key resolves to no row at all.
func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i GetAPIKeyByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.KeyHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Email,
		&i.UserName,
		&i.Status,
	)
	return i, err
}

const listAPIKeysForUser = `-- name: ListAPIKeysForUser :many
SELECT id, name, prefix, scopes, last_used_at, expires_at, revoked_at, created_at
FROM api_keys
WHERE user_id = $1
  AND organization_id = $2
ORDER BY created_at DESC
`

type ListAPIKeysForUserParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
}

type ListAPIKeysForUserRow struct {
	ID         uuid.UUID
	Name       string
	Prefix     string
	Scopes     []string
	LastUsedAt *time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
}

// Revoked keys are included. "Which keys existed and when were they revoked"
// is the question asked after an incident, so they are listed until the reaper
// removes them.
func (q *Queries) ListAPIKeysForUser(ctx context.Context, arg ListAPIKeysForUserParams) ([]ListAPIKeysForUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysForUser, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysForUserRow{}
	for rows.Next() {
		var i ListAPIKeysForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionSlugs = `-- name: ListPermissionSlugs :many
SELECT slug FROM permissions ORDER BY slug
`

// The scope vocabulary. Scopes are validated against the permissions table
// rather than a list in Go, so RBAC and API keys cannot drift apart.
func (q *Queries) ListPermissionSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
   SET revoked_at = COALESCE(revoked_at, now())
 WHERE id = $1
   AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Idempotent: revoking an already-revoked key keeps the original timestamp and
// still reports one row, so a repeated call is a success rather than a 404
// while a genuinely unknown id is still distinguishable.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKeys = `-- name: TouchAPIKeys :exec
UPDATE api_keys AS k
   SET last_used_at = GREATEST(COALESCE(k.last_used_at, to_timestamp(0)), v.used_at)
  FROM (
      SELECT unnest($1::uuid[])          AS id,
             unnest($2::timestamptz[]) AS used_at
  ) AS v
 WHERE k.id = v.id
`

type TouchAPIKeysParams struct {
	Ids    []uuid.UUID
	UsedAt []time.Time
}

// Batch write of last_used_at, from the coalescing tracker rather than from the
// request path: authenticating a key must not cost a synchronous write.
//
// GREATEST guards against a late batch moving the timestamp backwards, which
// two processes flushing out of order would otherwise do.
func (q *Queries) TouchAPIKeys(ctx context.Context, arg TouchAPIKeysParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeys, arg.Ids, arg.UsedAt)
	return err
}
