// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    id, user_id, organization_id, workspace_id,
    name, prefix, key_hash, scopes, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, organization_id, workspace_id, name, prefix, key_hash, scopes, last_used_at, expires_at, revoked_at, created_at, rotated_at, grace_expires_at, successor_id
`

type CreateAPIKeyParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	WorkspaceID    *uuid.UUID
	Name           string
	Prefix         string
	KeyHash        []byte
	Scopes         []string
	ExpiresAt      *time.Time
}

// API keys and the permission vocabulary their scopes are drawn from.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.GraceExpiresAt,
		&i.SuccessorID,
	)
	return i, err
}

const deleteRevokedAPIKeys = `-- name: DeleteRevokedAPIKeys :execrows
DELETE FROM api_keys
WHERE revoked_at IS NOT NULL
  AND revoked_at < now() - interval '90 days'
`

// Reaper. Kept long enough to be visible in the key list after revocation, and
// long enough for the audit question above to be answerable.
func (q *Queries) DeleteRevokedAPIKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevokedAPIKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT
    k.id, k.user_id, k.organization_id, k.workspace_id,
    k.key_hash, k.scopes, k.expires_at, k.revoked_at, k.grace_expires_at,
    u.email, u.name AS user_name, u.status
FROM api_keys k
JOIN users u ON u.id = k.user_id
WHERE k.prefix = $1
  AND u.deleted_at IS NULL
`

type GetAPIKeyByPrefixRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	WorkspaceID    *uuid.UUID
	KeyHash        []byte
	Scopes         []string
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	GraceExpiresAt *time.Time
	Email          string
	UserName       string
	Status         string
}

// The verification lookup, on the unique prefix index, joined with the user so
// authentication is one round trip. Revoked and expired keys are returned
// rather than filtered out: the caller distinguishes them so the response can
// say which it was, and a deleted user's key resolves to no row at all.
//
// grace_expires_at comes back for the same reason revoked_at does: a rotated
// predecessor stops verifying when its window closes, and that refusal is
// decided here rather than by the housekeeping job that later writes revoked_at.
func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i GetAPIKeyByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.KeyHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.GraceExpiresAt,
		&i.Email,
		&i.UserName,
		&i.Status,
	)
	return i, err
}

const getAPIKeyForRotation = `-- name: GetAPIKeyForRotation :one
SELECT id, user_id, organization_id, workspace_id, name, prefix, scopes,
       expires_at, revoked_at, rotated_at, grace_expires_at, successor_id,
       created_at
FROM api_keys
WHERE id = $1
FOR UPDATE
`

type GetAPIKeyForRotationRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	WorkspaceID    *uuid.UUID
	Name           string
	Prefix         string
	Scopes         []string
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	RotatedAt      *time.Time
	GraceExpiresAt *time.Time
	SuccessorID    *uuid.UUID
	CreatedAt      time.Time
}

// The predecessor, locked, so two rotations of one key serialize instead of
// racing.
//
// FOR UPDATE rather than an optimistic conditional write: the loser of a race
// should be told "this key has already been rotated" by the check that follows,
// which is a sentence somebody can act on, not have its transaction rolled back
// by a unique-index violation on a column it never named.
func (q *Queries) GetAPIKeyForRotation(ctx context.Context, id uuid.UUID) (GetAPIKeyForRotationRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyForRotation, id)
	var i GetAPIKeyForRotationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedAt,
		&i.GraceExpiresAt,
		&i.SuccessorID,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysForUser = `-- name: ListAPIKeysForUser :many
SELECT id, name, prefix, scopes, workspace_id, last_used_at, expires_at,
       revoked_at, rotated_at, grace_expires_at, successor_id, created_at
FROM api_keys
WHERE user_id = $1
  AND organization_id = $2
ORDER BY created_at DESC
`

type ListAPIKeysForUserParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
}

type ListAPIKeysForUserRow struct {
	ID             uuid.UUID
	Name           string
	Prefix         string
	Scopes         []string
	WorkspaceID    *uuid.UUID
	LastUsedAt     *time.Time
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	RotatedAt      *time.Time
	GraceExpiresAt *time.Time
	SuccessorID    *uuid.UUID
	CreatedAt      time.Time
}

// Revoked keys are included. "Which keys existed and when were they revoked"
// is the question asked after an incident, so they are listed until the reaper
// removes them.
//
// workspace_id is selected because NULL is a state the owner chose (M44): a key
// bound to one workspace and a key valid across the organization look identical
// without it.
func (q *Queries) ListAPIKeysForUser(ctx context.Context, arg ListAPIKeysForUserParams) ([]ListAPIKeysForUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysForUser, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysForUserRow{}
	for rows.Next() {
		var i ListAPIKeysForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Scopes,
			&i.WorkspaceID,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RotatedAt,
			&i.GraceExpiresAt,
			&i.SuccessorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionSlugs = `-- name: ListPermissionSlugs :many
SELECT slug FROM permissions ORDER BY slug
`

// The scope vocabulary. Scopes are validated against the permissions table
// rather than a list in Go, so RBAC and API keys cannot drift apart.
func (q *Queries) ListPermissionSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAPIKeyRotated = `-- name: MarkAPIKeyRotated :execrows
UPDATE api_keys
   SET rotated_at = now(),
       grace_expires_at = $2,
       successor_id = $3
 WHERE id = $1
   AND successor_id IS NULL
`

type MarkAPIKeyRotatedParams struct {
	ID             uuid.UUID
	GraceExpiresAt *time.Time
	SuccessorID    *uuid.UUID
}

// Closes the predecessor: names its successor and sets the far edge of the
// grace window.
//
// `successor_id IS NULL` in the WHERE clause is belt to the FOR UPDATE braces.
// The lock is what serializes; this is what makes the second writer a no-op
// rather than a silent overwrite if the lock is ever dropped from the read.
func (q *Queries) MarkAPIKeyRotated(ctx context.Context, arg MarkAPIKeyRotatedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAPIKeyRotated, arg.ID, arg.GraceExpiresAt, arg.SuccessorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
   SET revoked_at = COALESCE(revoked_at, now())
 WHERE id = $1
   AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Idempotent: revoking an already-revoked key keeps the original timestamp and
// still reports one row, so a repeated call is a success rather than a 404
// while a genuinely unknown id is still distinguishable.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLapsedAPIKeyGraces = `-- name: RevokeLapsedAPIKeyGraces :execrows
UPDATE api_keys
   SET revoked_at = grace_expires_at
 WHERE revoked_at IS NULL
   AND grace_expires_at IS NOT NULL
   AND grace_expires_at <= now()
`

// Auto-revocation, from housekeeping.
//
// revoked_at is set to the moment the window closed rather than to now(), so
// the list says when the key stopped working instead of when the job noticed.
// Nothing depends on this running: authentication already refuses a key past
// grace_expires_at. What this buys is a key list that agrees with the behaviour.
func (q *Queries) RevokeLapsedAPIKeyGraces(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLapsedAPIKeyGraces)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKeys = `-- name: TouchAPIKeys :exec
UPDATE api_keys AS k
   SET last_used_at = GREATEST(COALESCE(k.last_used_at, to_timestamp(0)), v.used_at)
  FROM (
      SELECT unnest($1::uuid[])          AS id,
             unnest($2::timestamptz[]) AS used_at
  ) AS v
 WHERE k.id = v.id
`

type TouchAPIKeysParams struct {
	Ids    []uuid.UUID
	UsedAt []time.Time
}

// Batch write of last_used_at, from the coalescing tracker rather than from the
// request path: authenticating a key must not cost a synchronous write.
//
// GREATEST guards against a late batch moving the timestamp backwards, which
// two processes flushing out of order would otherwise do.
func (q *Queries) TouchAPIKeys(ctx context.Context, arg TouchAPIKeysParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeys, arg.Ids, arg.UsedAt)
	return err
}
