// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one

SELECT count(*) FROM users WHERE deleted_at IS NULL
`

// Users, sessions and tenancy provisioning.
// Drives the first-run setup flow: /setup exists only while this is zero.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (id, user_id, organization_id, role_id, workspace_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, organization_id, role_id, workspace_id, created_at, updated_at
`

type CreateMembershipParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	RoleID         uuid.UUID
	WorkspaceID    *uuid.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.RoleID,
		arg.WorkspaceID,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.RoleID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug, is_personal)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, data_region, is_personal, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	IsPersonal bool
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.IsPersonal,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DataRegion,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, ip_prefix, user_agent, expires_at, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token_hash, ip_prefix, user_agent, created_at, last_seen_at, expires_at, revoked_at, workspace_id
`

type CreateSessionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	TokenHash   []byte
	IpPrefix    *string
	UserAgent   *string
	ExpiresAt   time.Time
	WorkspaceID *uuid.UUID
}

// workspace_id is written at sign-in rather than left for the first switch, so
// a session says where it is from its first row. Resolution would answer the
// same either way — a NULL simply falls through to the user's preference — but
// a switcher that only takes effect after the first switch is a switcher whose
// state is unreadable until somebody uses it.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.IpPrefix,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.WorkspaceID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpPrefix,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, password_hash, status, email_verified_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, email_lower, email_verified_at, name, password_hash, status, failed_login_count, locked_until, mfa_secret, mfa_enabled_at, anonymized_at, last_login_at, created_at, updated_at, deleted_at, default_workspace_id, last_workspace_id
`

type CreateUserParams struct {
	ID              uuid.UUID
	Email           string
	Name            string
	PasswordHash    *string
	Status          string
	EmailVerifiedAt *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Status,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.MfaSecret,
		&i.MfaEnabledAt,
		&i.AnonymizedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DefaultWorkspaceID,
		&i.LastWorkspaceID,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, organization_id, name, slug)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, slug, analytics_retention_days, created_at, updated_at, deleted_at, signing_secret
`

type CreateWorkspaceParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Slug           string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.AnalyticsRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SigningSecret,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < now() - interval '7 days'
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '7 days')
`

// Reaper. Revoked rows are kept briefly so "sign out everywhere" is visible in
// the session list before it disappears.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, organization_id, slug, name, description, is_builtin, rank, created_at FROM roles WHERE slug = $1 AND organization_id IS NULL
`

func (q *Queries) GetRoleBySlug(ctx context.Context, slug string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleBySlug, slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsBuiltin,
		&i.Rank,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    s.id, s.user_id, s.created_at, s.last_seen_at, s.expires_at,
    u.email, u.name, u.status, u.password_hash
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND u.deleted_at IS NULL
`

type GetSessionByTokenHashRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	CreatedAt    time.Time
	LastSeenAt   time.Time
	ExpiresAt    time.Time
	Email        string
	Name         string
	Status       string
	PasswordHash *string
}

// Joined with the user so validating a session is one round trip on a path
// that runs for every authenticated request. Filters revoked and deleted here
// rather than in Go, so a revoked session cannot be resurrected by a caller
// that forgets to check.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_lower, email_verified_at, name, password_hash, status, failed_login_count, locked_until, mfa_secret, mfa_enabled_at, anonymized_at, last_login_at, created_at, updated_at, deleted_at, default_workspace_id, last_workspace_id FROM users
WHERE email_lower = lower($1::text)
  AND deleted_at IS NULL
`

// Comparison is on the generated email_lower column, so callers cannot
// accidentally do a case-sensitive lookup and create a duplicate account.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.MfaSecret,
		&i.MfaEnabledAt,
		&i.AnonymizedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DefaultWorkspaceID,
		&i.LastWorkspaceID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_lower, email_verified_at, name, password_hash, status, failed_login_count, locked_until, mfa_secret, mfa_enabled_at, anonymized_at, last_login_at, created_at, updated_at, deleted_at, default_workspace_id, last_workspace_id FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.MfaSecret,
		&i.MfaEnabledAt,
		&i.AnonymizedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DefaultWorkspaceID,
		&i.LastWorkspaceID,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.slug
FROM memberships m
JOIN workspaces w  ON w.organization_id = m.organization_id
JOIN role_permissions rp ON rp.role_id = m.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE m.user_id = $1
  AND w.id = $2
  AND w.deleted_at IS NULL
  AND (m.workspace_id IS NULL OR m.workspace_id = w.id)
ORDER BY p.slug
`

type GetUserPermissionsParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

// The RBAC evaluator's source of truth. Returns every permission a user holds
// in a workspace, via their organization membership and its role.
//
// A NULL memberships.workspace_id means the membership covers every workspace
// in the organization, which is what Phase 1 always creates.
func (q *Queries) GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleInWorkspace = `-- name: GetUserRoleInWorkspace :one
SELECT r.slug, r.name, r.rank
FROM memberships m
JOIN workspaces w ON w.organization_id = m.organization_id
JOIN roles r ON r.id = m.role_id
WHERE m.user_id = $1
  AND w.id = $2
  AND (m.workspace_id IS NULL OR m.workspace_id = w.id)
ORDER BY r.rank
LIMIT 1
`

type GetUserRoleInWorkspaceParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetUserRoleInWorkspaceRow struct {
	Slug string
	Name string
	Rank int32
}

func (q *Queries) GetUserRoleInWorkspace(ctx context.Context, arg GetUserRoleInWorkspaceParams) (GetUserRoleInWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getUserRoleInWorkspace, arg.UserID, arg.ID)
	var i GetUserRoleInWorkspaceRow
	err := row.Scan(&i.Slug, &i.Name, &i.Rank)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, ip_prefix, user_agent, created_at, last_seen_at, expires_at
FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_seen_at DESC
`

type ListUserSessionsRow struct {
	ID         uuid.UUID
	IpPrefix   *string
	UserAgent  *string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.IpPrefix,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, status, last_login_at, created_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at
`

type ListUsersRow struct {
	ID          uuid.UUID
	Email       string
	Name        string
	Status      string
	LastLoginAt *time.Time
	CreatedAt   time.Time
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFirstUserSetup = `-- name: LockFirstUserSetup :exec
SELECT pg_advisory_xact_lock(7810213058373316608)
`

// Serializes the setup flow's count-then-create.
//
// Both setup surfaces read CountUsers and then, in a separate transaction,
// register the first user. Nothing held the gap, and the gap is wide: the
// argon2 hash runs for ~100ms before the transaction even begins. On a fresh
// closed instance, setup is unauthenticated and only login-rate-limited, so an
// attacker polling it could have their CountUsers land in the window while the
// real operator was hashing, and both would be created as "the first user" —
// each with their own organization, on an instance the operator believes only
// they can reach.
//
// Transaction-scoped, so it releases on commit or rollback with nothing to
// clean up. The key is the ASCII bytes "lcsetup\0" as a literal, NOT a hash of
// anything; to inspect it from psql use the value directly:
//
//	SELECT pg_advisory_xact_lock(7810213058373316608);
func (q *Queries) LockFirstUserSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockFirstUserSetup)
	return err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE users
   SET failed_login_count = CASE
           WHEN locked_until IS NOT NULL AND locked_until <= now() THEN 1
           ELSE failed_login_count + 1
       END,
       -- Seconds rather than an interval literal: an interval parameter maps
       -- to pgtype.Interval, which would leak a driver type into the service
       -- layer for no benefit.
       locked_until = CASE
           WHEN $2::int <= 0 THEN locked_until
           WHEN locked_until IS NOT NULL AND locked_until <= now()
           THEN CASE
               WHEN 1 >= $2::int
               THEN now() + make_interval(secs => $3::int)
               ELSE NULL
           END
           WHEN failed_login_count + 1 >= $2::int
           THEN now() + make_interval(secs => $3::int)
           ELSE locked_until
       END,
       updated_at = now()
 WHERE id = $1
RETURNING failed_login_count, locked_until
`

type RecordFailedLoginParams struct {
	ID             uuid.UUID
	Threshold      int32
	LockoutSeconds int32
}

type RecordFailedLoginRow struct {
	FailedLoginCount int32
	LockedUntil      *time.Time
}

// Returns the new count so the caller can apply the lockout policy without a
// second round trip and without a read-modify-write race between two
// concurrent attempts.
//
// An elapsed lockout starts the count over. Incrementing unconditionally meant
// the counter only ever went down on a successful sign-in or a password change,
// so once an account had been locked it sat at the threshold forever: the user
// waited out the window, got one attempt, and a single wrong guess re-locked
// them for the full duration. The lockout became permanent for anyone who could
// not remember their password on the first try — which is the population it
// applies to.
func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, arg.ID, arg.Threshold, arg.LockoutSeconds)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const recordSuccessfulLogin = `-- name: RecordSuccessfulLogin :exec
UPDATE users
   SET last_login_at = now(),
       failed_login_count = 0,
       locked_until = NULL,
       updated_at = now()
 WHERE id = $1
`

func (q *Queries) RecordSuccessfulLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordSuccessfulLogin, id)
	return err
}

const resolveWorkspaceForUser = `-- name: ResolveWorkspaceForUser :one
SELECT w.id, w.organization_id, w.name, w.slug, w.analytics_retention_days, w.created_at, w.updated_at, w.deleted_at, w.signing_secret
FROM workspaces w
JOIN memberships m ON m.organization_id = w.organization_id
JOIN users u       ON u.id = m.user_id
LEFT JOIN sessions s ON s.id = $1::uuid
                    AND s.user_id = m.user_id
                    AND s.revoked_at IS NULL
WHERE m.user_id = $2
  AND w.deleted_at IS NULL
  AND ($3::uuid IS NULL
       OR w.organization_id = $3::uuid)
  -- A NULL memberships.workspace_id covers every workspace in the organization;
  -- a set one covers exactly that workspace. Same rule GetUserPermissions
  -- applies, so a user can never resolve into a workspace they hold no
  -- permissions in. No-op today, where every membership is organization-wide.
  AND (m.workspace_id IS NULL OR m.workspace_id = w.id)
ORDER BY
    (w.id IS NOT DISTINCT FROM s.workspace_id)          DESC,
    (w.id IS NOT DISTINCT FROM u.default_workspace_id)  DESC,
    (w.id IS NOT DISTINCT FROM u.last_workspace_id)     DESC,
    w.created_at, w.id
LIMIT 1
`

type ResolveWorkspaceForUserParams struct {
	SessionID      *uuid.UUID
	UserID         uuid.UUID
	OrganizationID *uuid.UUID
}

// The workspace a request acts in, and the only place that question is
// answered. Every identity — session, API key, CLI — comes through here.
//
// The precedence is the ORDER BY and nothing else, so there is one statement of
// it rather than one per caller:
//
//  1. the session's own current workspace, for a request that has a session
//  2. the workspace the user pinned as their default
//  3. the workspace they used last
//  4. the oldest workspace they are a member of
//
// Each rung is a tiebreak on the one above, so a user with a single membership
// ties on all four and lands where they always did. That is what makes the
// switcher a no-op for every instance that exists today.
//
// Membership is the WHERE clause, not the ordering, so a preference pointing at
// a workspace the user has been removed from — or one that has been deleted —
// cannot win. It simply stops matching and the next rung answers.
//
// session_id is optional. NULL leaves the LEFT JOIN unmatched and rung 1 dead,
// which is right for a login (the session does not exist yet), the CLI, and an
// API key. The join also requires the session to belong to this user, so a
// borrowed id resolves nothing.
//
// organization_id is optional too, and it is a *bound* rather than a rung: it
// narrows which workspaces are candidates without touching the precedence. Only
// one caller passes it, and the reason is M44. An organization-wide API key is a
// row with a NULL workspace_id, which means "every workspace in **the
// organization** the key belongs to" — and without this clause the precedence
// would happily rank a workspace in some *other* organization the owner also
// belongs to, because membership is the only filter and a person's pinned
// default is a property of the person rather than of the tenancy. The key would
// then act in a tenant it was never issued for. Every other caller passes NULL
// and resolves exactly as it always did.
func (q *Queries) ResolveWorkspaceForUser(ctx context.Context, arg ResolveWorkspaceForUserParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, resolveWorkspaceForUser, arg.SessionID, arg.UserID, arg.OrganizationID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.AnalyticsRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SigningSecret,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
   SET revoked_at = now()
 WHERE user_id = $1
   AND revoked_at IS NULL
   AND ($2::uuid IS NULL OR id <> $2::uuid)
`

type RevokeAllUserSessionsParams struct {
	UserID      uuid.UUID
	KeepSession *uuid.UUID
}

// Used on password change. Anyone who had the old password must be logged out,
// which is the entire point of changing it.
// keep_session is optional: pass NULL to revoke everything, or the current
// session's id to leave the browser the user is changing their password in
// still signed in.
func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.UserID, arg.KeepSession)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

// Idle expiry is measured from last_seen_at. Updated at most once a minute by
// the caller, because writing on every request would turn a read-mostly path
// into a write on the hottest authenticated query.
func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
   SET password_hash = $2,
       failed_login_count = 0,
       locked_until = NULL,
       updated_at = now()
 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
