// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countCampaigns = `-- name: CountCampaigns :one
SELECT count(*) FROM campaigns
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCampaigns(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaigns, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQRCodes = `-- name: CountQRCodes :one
SELECT count(*) FROM qr_codes WHERE link_id = $1 AND workspace_id = $2
`

type CountQRCodesParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
}

// What domain.MaxQRCodesPerLink is checked against, the way campaign creation
// checks CountCampaigns.
func (q *Queries) CountQRCodes(ctx context.Context, arg CountQRCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQRCodes, arg.LinkID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one

INSERT INTO campaigns (id, workspace_id, name, slug, description, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, name, slug, description, settings, starts_at, ends_at, created_at, updated_at, deleted_at
`

type CreateCampaignParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
	StartsAt    *time.Time
	EndsAt      *time.Time
}

// Campaigns and QR codes (M41).
//
// Both tables were created dormant by 00600 and woken by 02700. They share this
// file because they share a milestone and neither is large enough to be worth
// its own; nothing else connects them.
//
// **A campaign is soft-deleted and a QR style is not.** The asymmetry is
// deliberate. A campaign names a body of work whose links keep their history
// after it ends, and `links.campaign_id` is ON DELETE SET NULL, so a hard delete
// would unlabel every link the moment somebody tidied up a finished campaign —
// exactly the failure the folder migration (02400) argues against. `deleted_at`
// keeps the row, and every statement here filters on it. A QR style is a
// rendering preference with nothing to restore: deleting it returns the link's
// code to the default style, which is the state every link starts in.
func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Settings,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :execrows
UPDATE campaigns SET deleted_at = now(), updated_at = now()
 WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type DeleteCampaignParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Soft. The links keep their history; `links.campaign_id` is cleared by the
// statement below rather than by a cascade, because a cascade would fire on a
// hard delete this statement never performs.
func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCampaign, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteQRCode = `-- name: DeleteQRCode :execrows
DELETE FROM qr_codes WHERE link_id = $1 AND workspace_id = $2 AND slug = ''
`

type DeleteQRCodeParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
}

// Returns the link's default code to the default style. A hard delete, because
// the row holds nothing but the preference being withdrawn.
func (q *Queries) DeleteQRCode(ctx context.Context, arg DeleteQRCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQRCode, arg.LinkID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteQRCodeByID = `-- name: DeleteQRCodeByID :execrows
DELETE FROM qr_codes WHERE id = $1 AND workspace_id = $2 AND slug <> ''
`

type DeleteQRCodeByIDParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Removes one named code. Scoped by workspace rather than by link, because the
// id is already unique and the service has resolved the link before it gets
// here; the workspace column is the tenancy check.
func (q *Queries) DeleteQRCodeByID(ctx context.Context, arg DeleteQRCodeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQRCodeByID, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, workspace_id, name, slug, description, settings, starts_at, ends_at, created_at, updated_at, deleted_at FROM campaigns
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetCampaignParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Workspace-scoped like GetLink and GetFolder, and for the same reason: the
// wrong workspace returns no rows rather than a row the caller must remember to
// reject.
func (q *Queries) GetCampaign(ctx context.Context, arg GetCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, arg.ID, arg.WorkspaceID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Settings,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQRCode = `-- name: GetQRCode :one
SELECT q.id, q.link_id, q.workspace_id, q.style, q.created_at, q.updated_at, q.label, q.slug FROM qr_codes q
JOIN links l ON l.id = q.link_id
WHERE q.link_id = $1 AND q.workspace_id = $2 AND q.slug = $3 AND l.deleted_at IS NULL
`

type GetQRCodeParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
	Slug        string
}

// One code of a link's, by slug. No rows is not an error for the default code
// (slug ”): it means the default style, which is what every link's code is
// drawn with until somebody changes it. For any other slug no rows means the
// code does not exist, and the service reports that.
func (q *Queries) GetQRCode(ctx context.Context, arg GetQRCodeParams) (QrCode, error) {
	row := q.db.QueryRow(ctx, getQRCode, arg.LinkID, arg.WorkspaceID, arg.Slug)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.Style,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.Slug,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT c.id, c.workspace_id, c.name, c.slug, c.description, c.settings, c.starts_at, c.ends_at, c.created_at, c.updated_at, c.deleted_at, COALESCE(k.n, 0)::bigint AS link_count
FROM campaigns c
LEFT JOIN (
    SELECT l.campaign_id, count(*) AS n
      FROM links l
     WHERE l.workspace_id = $1
       AND l.deleted_at IS NULL
       AND l.campaign_id IS NOT NULL
     GROUP BY l.campaign_id
) k ON k.campaign_id = c.id
WHERE c.workspace_id = $1 AND c.deleted_at IS NULL
ORDER BY lower(c.name), c.id
`

type ListCampaignsRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
	Settings    []byte
	StartsAt    *time.Time
	EndsAt      *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	LinkCount   int64
}

// Every campaign in the workspace, with how many live links carry it.
//
// The count is a grouped scan of links_campaign_idx rather than a correlated
// subquery per campaign, exactly as ListFolders counts filed links: a workspace
// with many campaigns costs one pass instead of one index probe each.
//
// Unpaginated, and bounded instead by domain.MaxCampaignsPerWorkspace. A
// campaign list is a picker as much as it is a page — the link form offers it —
// and a picker that paginates is a picker nobody can choose from.
func (q *Queries) ListCampaigns(ctx context.Context, workspaceID uuid.UUID) ([]ListCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listCampaigns, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignsRow{}
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Settings,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQRCodes = `-- name: ListQRCodes :many
SELECT q.id, q.link_id, q.workspace_id, q.style, q.created_at, q.updated_at, q.label, q.slug FROM qr_codes q
JOIN links l ON l.id = q.link_id
WHERE q.link_id = $1 AND q.workspace_id = $2 AND l.deleted_at IS NULL
ORDER BY (q.slug <> ''), q.created_at, q.id
`

type ListQRCodesParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
}

// Every code a link carries (M50), default first.
//
// Unpaginated, and bounded instead by domain.MaxQRCodesPerLink, which is the
// same trade ListCampaigns makes: the cap is small enough that a page of them is
// the whole set, and a pager over a list that cannot exceed it would be a
// control nobody ever operates.
//
// `q.slug <> ”` sorts false before true, so the default code leads whatever
// order the rest were created in — it is the one every already-printed code
// attributes to, and a list that buried it would bury the answer to "which of
// these is the one on my existing posters".
func (q *Queries) ListQRCodes(ctx context.Context, arg ListQRCodesParams) ([]QrCode, error) {
	rows, err := q.db.Query(ctx, listQRCodes, arg.LinkID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QrCode{}
	for rows.Next() {
		var i QrCode
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.WorkspaceID,
			&i.Style,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Label,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignCampaignLinks = `-- name: UnassignCampaignLinks :execrows
UPDATE links SET campaign_id = NULL, updated_at = now()
 WHERE workspace_id = $2 AND campaign_id = $1
`

type UnassignCampaignLinksParams struct {
	CampaignID  *uuid.UUID
	WorkspaceID uuid.UUID
}

// Takes every link out of a deleted campaign.
//
// Run in the same transaction as DeleteCampaign. Without it the links keep an id
// pointing at a row no query returns, which is a link filtered by a campaign
// that is not in the campaign list — the invisible-rows failure 02400 describes
// for folders, in the one place the schema does not prevent it.
func (q *Queries) UnassignCampaignLinks(ctx context.Context, arg UnassignCampaignLinksParams) (int64, error) {
	result, err := q.db.Exec(ctx, unassignCampaignLinks, arg.CampaignID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
   SET name        = COALESCE($1, name),
       slug        = COALESCE($2, slug),
       description = COALESCE($3, description),
       starts_at   = CASE WHEN $4::boolean THEN NULL
                          ELSE COALESCE($5, starts_at) END,
       ends_at     = CASE WHEN $6::boolean THEN NULL
                          ELSE COALESCE($7, ends_at) END,
       updated_at  = now()
 WHERE id = $8 AND workspace_id = $9 AND deleted_at IS NULL
RETURNING id, workspace_id, name, slug, description, settings, starts_at, ends_at, created_at, updated_at, deleted_at
`

type UpdateCampaignParams struct {
	Name          *string
	Slug          *string
	Description   *string
	ClearStartsAt bool
	StartsAt      *time.Time
	ClearEndsAt   bool
	EndsAt        *time.Time
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
}

// Partial update through COALESCE, like UpdateLink. The two schedule bounds are
// three-valued through their own clear flags, because "leave the end date alone"
// and "this campaign no longer ends" are different requests and one nullable
// parameter cannot express both.
func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ClearStartsAt,
		arg.StartsAt,
		arg.ClearEndsAt,
		arg.EndsAt,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Settings,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateQRCodeLabel = `-- name: UpdateQRCodeLabel :execrows
UPDATE qr_codes SET label = $3, updated_at = now()
 WHERE id = $1 AND workspace_id = $2
`

type UpdateQRCodeLabelParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Label       string
}

// Renames one code. The slug is untouched on purpose: it is printed, and a
// rename that moved it would break every copy already in the world.
func (q *Queries) UpdateQRCodeLabel(ctx context.Context, arg UpdateQRCodeLabelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQRCodeLabel, arg.ID, arg.WorkspaceID, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertQRCode = `-- name: UpsertQRCode :one
INSERT INTO qr_codes (id, link_id, workspace_id, slug, label, style)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (link_id, slug) DO UPDATE
   SET style = EXCLUDED.style, updated_at = now()
RETURNING id, link_id, workspace_id, style, created_at, updated_at, label, slug
`

type UpsertQRCodeParams struct {
	ID          uuid.UUID
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
	Slug        string
	Label       string
	Style       []byte
}

// One row per (link, slug), which qr_codes_link_slug_key (03700) is what makes
// true. Without the unique index this is two concurrent inserts and a link with
// two codes answering to one name.
//
// The label is not in the DO UPDATE list. This statement is how a *style* is
// written, and a style write must not silently rename the code it is drawn for;
// UpdateQRCodeLabel is the operation that renames one.
func (q *Queries) UpsertQRCode(ctx context.Context, arg UpsertQRCodeParams) (QrCode, error) {
	row := q.db.QueryRow(ctx, upsertQRCode,
		arg.ID,
		arg.LinkID,
		arg.WorkspaceID,
		arg.Slug,
		arg.Label,
		arg.Style,
	)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.Style,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.Slug,
	)
	return i, err
}
