// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disputes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOpenDestinationDisputes = `-- name: CountOpenDestinationDisputes :one
SELECT count(*) FROM destination_disputes WHERE status = 'open'
`

// What the queue's heading says there is to do. Served by the partial unique
// index, whose predicate this matches exactly.
func (q *Queries) CountOpenDestinationDisputes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenDestinationDisputes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideDestinationDispute = `-- name: DecideDestinationDispute :one
UPDATE destination_disputes
   SET status = $1,
       decided_by = $2,
       decided_by_label = $3,
       decided_at = now()
 WHERE id = $4 AND status = 'open'
RETURNING id, host, url_defanged, reason_code, status, organization_id, workspace_id, created_by, created_by_label, created_at, decided_by, decided_by_label, decided_at
`

type DecideDestinationDisputeParams struct {
	Status         string
	DecidedBy      *uuid.UUID
	DecidedByLabel string
	ID             uuid.UUID
}

// Records a decision, and only on a dispute nobody has decided yet.
//
// The `status = 'open'` predicate is the concurrency control: two owners
// clicking allow and uphold on the same row produce one decision and one
// no-rows, rather than a last-writer-wins that leaves the audit record and the
// blocklist disagreeing about what happened.
func (q *Queries) DecideDestinationDispute(ctx context.Context, arg DecideDestinationDisputeParams) (DestinationDispute, error) {
	row := q.db.QueryRow(ctx, decideDestinationDispute,
		arg.Status,
		arg.DecidedBy,
		arg.DecidedByLabel,
		arg.ID,
	)
	var i DestinationDispute
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.UrlDefanged,
		&i.ReasonCode,
		&i.Status,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.CreatedByLabel,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedByLabel,
		&i.DecidedAt,
	)
	return i, err
}

const deleteBlockedDestination = `-- name: DeleteBlockedDestination :execrows
DELETE FROM blocked_destinations WHERE host = lower($1::text)
`

// Removes one host from the low-confidence runtime list.
//
// The only deletion in this program that is not a reconciliation, and the only
// one an `allow` decision performs. Scoped to an exact host — the row that was
// matched, which the caller has already read — so a decision about
// 'login.evil.example' cannot take 'evil.example' off the list by accident.
//
// It cannot reach the other two tiers, and there is nothing to scope against
// them: the embedded list is a compiled file and the unappealable tier has no
// row anywhere. That is the structural half of "decisions act only on the
// runtime low-confidence list".
func (q *Queries) DeleteBlockedDestination(ctx context.Context, host string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockedDestination, host)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDestinationDispute = `-- name: GetDestinationDispute :one
SELECT id, host, url_defanged, reason_code, status, organization_id, workspace_id, created_by, created_by_label, created_at, decided_by, decided_by_label, decided_at FROM destination_disputes WHERE id = $1
`

func (q *Queries) GetDestinationDispute(ctx context.Context, id uuid.UUID) (DestinationDispute, error) {
	row := q.db.QueryRow(ctx, getDestinationDispute, id)
	var i DestinationDispute
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.UrlDefanged,
		&i.ReasonCode,
		&i.Status,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.CreatedByLabel,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedByLabel,
		&i.DecidedAt,
	)
	return i, err
}

const hostHasAllowedDispute = `-- name: HostHasAllowedDispute :one
SELECT EXISTS (
    SELECT 1 FROM destination_disputes
     WHERE host = lower($1::text)
       AND status = 'allowed'
)
`

// Whether the instance owner has allowed this host (M32).
//
// Read at exactly one call site — internal/link's feed step — and that
// confinement is the whole safety argument. It suppresses the third-party
// reputation feed for a host the owner already decided about, which is what
// makes a feed verdict owner-overridable without 01500 growing the allow column
// it deliberately does not have.
//
// It cannot widen anything else. The three tiers above the feed have all
// returned by the time this runs, and M31 refuses to file a dispute about any
// refusal but a low-confidence one, so no row here can carry an unappealable or
// embedded-tier reason code to be read as permission.
//
// Equality rather than the blocklist's candidate walk: allowing 'evil.example'
// says nothing about 'login.evil.example', and 01700's partial index matches
// this predicate exactly.
func (q *Queries) HostHasAllowedDispute(ctx context.Context, host string) (bool, error) {
	row := q.db.QueryRow(ctx, hostHasAllowedDispute, host)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertDestinationDispute = `-- name: InsertDestinationDispute :one

INSERT INTO destination_disputes (
    id, host, url_defanged, reason_code,
    organization_id, workspace_id, created_by, created_by_label
) VALUES (
    $1, lower($2::text), $3, $4,
    $5, $6, $7, $8
)
RETURNING id, host, url_defanged, reason_code, status, organization_id, workspace_id, created_by, created_by_label, created_at, decided_by, decided_by_label, decided_at
`

type InsertDestinationDisputeParams struct {
	ID             uuid.UUID
	Host           string
	UrlDefanged    string
	ReasonCode     string
	OrganizationID *uuid.UUID
	WorkspaceID    *uuid.UUID
	CreatedBy      *uuid.UUID
	CreatedByLabel string
}

// Blocked-attempt disputes (M31).
//
// Read and written on the management path only. Like the blocklist it argues
// with, nothing here is reachable from the redirect tree: a dispute is about
// what may be *stored*, and a link that was refused at creation never became a
// row for a visitor to resolve.
// Files one dispute.
//
// The unique partial index on (host) WHERE status = 'open' is what makes a
// second open dispute about the same host a constraint violation rather than a
// duplicate row, so the "already under review" answer is decided by the database
// and not by a check-then-insert that two requests can both pass.
func (q *Queries) InsertDestinationDispute(ctx context.Context, arg InsertDestinationDisputeParams) (DestinationDispute, error) {
	row := q.db.QueryRow(ctx, insertDestinationDispute,
		arg.ID,
		arg.Host,
		arg.UrlDefanged,
		arg.ReasonCode,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.CreatedByLabel,
	)
	var i DestinationDispute
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.UrlDefanged,
		&i.ReasonCode,
		&i.Status,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.CreatedByLabel,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedByLabel,
		&i.DecidedAt,
	)
	return i, err
}

const listDestinationDisputes = `-- name: ListDestinationDisputes :many
SELECT id, host, url_defanged, reason_code, status, organization_id, workspace_id, created_by, created_by_label, created_at, decided_by, decided_by_label, decided_at FROM destination_disputes
 WHERE (NOT $1::boolean OR status = 'open')
   AND (
        $2::timestamptz IS NULL
     OR (created_at, id) < ($2::timestamptz, $3::uuid)
   )
 ORDER BY created_at DESC, id DESC
 LIMIT $4
`

type ListDestinationDisputesParams struct {
	OpenOnly      bool
	CursorCreated *time.Time
	CursorID      *uuid.UUID
	PageLimit     int32
}

// The queue, newest first, keyset on (created_at, id).
//
// Instance-wide rather than scoped to the reader's organization, because the
// list a decision acts on is instance-wide (01500) and a queue narrower than the
// authority it exercises would hide rows the reader is nonetheless deciding for.
// The permission is what bounds who sees it.
//
// @open_only lets the page show the work and the archive from one query, which
// is the same shape ListNotifications' unread filter has.
func (q *Queries) ListDestinationDisputes(ctx context.Context, arg ListDestinationDisputesParams) ([]DestinationDispute, error) {
	rows, err := q.db.Query(ctx, listDestinationDisputes,
		arg.OpenOnly,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DestinationDispute{}
	for rows.Next() {
		var i DestinationDispute
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.UrlDefanged,
			&i.ReasonCode,
			&i.Status,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.CreatedByLabel,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedByLabel,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
