// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLinksOnDomain = `-- name: CountLinksOnDomain :one
SELECT count(*) FROM links WHERE domain_id = $1 AND deleted_at IS NULL
`

// What deletion is refused for. Zero on every registered hostname today, because
// nothing serves one and links are created on the default domain — the guard is
// here so that it is already true when M40 makes it reachable.
func (q *Queries) CountLinksOnDomain(ctx context.Context, domainID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLinksOnDomain, domainID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomain = `-- name: CreateDomain :one

INSERT INTO domains (id, organization_id, workspace_id, hostname)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, hostname, is_default, verified_at, ssl_status, created_at, updated_at, deleted_at, root_redirect_url, block_bots, block_bots_enforced, workspace_id
`

type CreateDomainParams struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	WorkspaceID    *uuid.UUID
	Hostname       string
}

// Domain ownership and registration (M39).
//
// The settings queries for the instance default live in links.sql, where they
// were written when there was exactly one domain. These are the ones that exist
// because there can now be more than one, and every statement here reads or
// writes the *ownership* columns rather than the serving ones — nothing on a
// registered hostname is served until M40 verifies it.
//
// Ownership is never decided in SQL. Every write below is by id, and
// link.Service reads the row first and judges the actor against it, so the
// refusal is a sentence naming whose domain it is rather than a statement that
// silently affected no rows. ListDomains is the exception, and it is a read: it
// is scoped by the actor's organization and workspace because a list is only
// ever the caller's own.
// Registered, and deliberately unverified: verified_at stays NULL and
// ssl_status stays at its 'none' default. is_default is never set here — there
// is one instance default and 00700 seeded it.
func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.ID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.Hostname,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RootRedirectUrl,
		&i.BlockBots,
		&i.BlockBotsEnforced,
		&i.WorkspaceID,
	)
	return i, err
}

const getDomainByHostname = `-- name: GetDomainByHostname :one
SELECT id, organization_id, hostname, is_default, verified_at, ssl_status, created_at, updated_at, deleted_at, root_redirect_url, block_bots, block_bots_enforced, workspace_id FROM domains WHERE lower(hostname) = lower($1) AND deleted_at IS NULL
`

// Matches domains_hostname_key exactly — lower(hostname) among the undeleted —
// so the availability check and the unique index cannot disagree about which
// names collide.
func (q *Queries) GetDomainByHostname(ctx context.Context, lower string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByHostname, lower)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RootRedirectUrl,
		&i.BlockBots,
		&i.BlockBotsEnforced,
		&i.WorkspaceID,
	)
	return i, err
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT id, organization_id, hostname, is_default, verified_at, ssl_status, created_at, updated_at, deleted_at, root_redirect_url, block_bots, block_bots_enforced, workspace_id FROM domains WHERE id = $1 AND deleted_at IS NULL
`

// The row the ownership check is made against, so it carries both owner columns.
func (q *Queries) GetDomainByID(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RootRedirectUrl,
		&i.BlockBots,
		&i.BlockBotsEnforced,
		&i.WorkspaceID,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT d.id, d.organization_id, d.hostname, d.is_default, d.verified_at, d.ssl_status, d.created_at, d.updated_at, d.deleted_at, d.root_redirect_url, d.block_bots, d.block_bots_enforced, d.workspace_id, count(l.id)::bigint AS link_count
FROM domains d
LEFT JOIN links l ON l.domain_id = d.id AND l.deleted_at IS NULL
WHERE d.deleted_at IS NULL
  AND (
        (d.organization_id IS NULL AND d.workspace_id IS NULL)
     OR (d.organization_id = $1 AND d.workspace_id IS NULL)
     OR  d.workspace_id = $2
      )
GROUP BY d.id
ORDER BY d.is_default DESC, lower(d.hostname), d.id
`

type ListDomainsParams struct {
	OrganizationID *uuid.UUID
	WorkspaceID    *uuid.UUID
}

type ListDomainsRow struct {
	ID                uuid.UUID
	OrganizationID    *uuid.UUID
	Hostname          string
	IsDefault         bool
	VerifiedAt        *time.Time
	SslStatus         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
	RootRedirectUrl   *string
	BlockBots         bool
	BlockBotsEnforced bool
	WorkspaceID       *uuid.UUID
	LinkCount         int64
}

// Every domain the caller may use: the instance default, whatever their
// organization owns, and whatever their own workspace owns.
//
// Another workspace's hostname is absent rather than present and unmanageable.
// A list that showed it would disclose which hostnames a neighbouring workspace
// has registered, and the registration is the only thing there is to disclose at
// this milestone.
//
// Ordered default-first, then by hostname: the default is the one every link is
// on today, so it belongs at the top rather than wherever its placeholder name
// happens to sort.
func (q *Queries) ListDomains(ctx context.Context, arg ListDomainsParams) ([]ListDomainsRow, error) {
	rows, err := q.db.Query(ctx, listDomains, arg.OrganizationID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainsRow{}
	for rows.Next() {
		var i ListDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Hostname,
			&i.IsDefault,
			&i.VerifiedAt,
			&i.SslStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RootRedirectUrl,
			&i.BlockBots,
			&i.BlockBotsEnforced,
			&i.WorkspaceID,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameDomain = `-- name: RenameDomain :one
UPDATE domains
   SET hostname = $2, updated_at = now()
 WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, hostname, is_default, verified_at, ssl_status, created_at, updated_at, deleted_at, root_redirect_url, block_bots, block_bots_enforced, workspace_id
`

type RenameDomainParams struct {
	ID       uuid.UUID
	Hostname string
}

// The hostname is the only thing a registration has to change, and it is
// changeable only while nothing serves it; see decisions.md, D69.
//
// Not scoped by owner. The caller has already been judged against the row read
// by GetDomainByID, and repeating the predicate here would turn a 403 into a
// 404 for anybody who got past that check by a route this file cannot see.
func (q *Queries) RenameDomain(ctx context.Context, arg RenameDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, renameDomain, arg.ID, arg.Hostname)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Hostname,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RootRedirectUrl,
		&i.BlockBots,
		&i.BlockBotsEnforced,
		&i.WorkspaceID,
	)
	return i, err
}

const softDeleteDomain = `-- name: SoftDeleteDomain :execrows
UPDATE domains
   SET deleted_at = now(), updated_at = now()
 WHERE id = $1 AND deleted_at IS NULL
`

// Soft, unlike a folder. A domain is the namespace its links' aliases live in
// and `links.domain_id` is NOT NULL with no cascade, so a hard delete is refused
// by the database the moment one link exists; a soft delete keeps the row that
// every historic click event and reserved alias still points at.
func (q *Queries) SoftDeleteDomain(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDomain, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
