// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMembershipsForEmail = `-- name: CountMembershipsForEmail :one
SELECT count(*) FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
  AND u.email_lower = lower($2::text)
  AND u.deleted_at IS NULL
`

type CountMembershipsForEmailParams struct {
	OrganizationID uuid.UUID
	Email          string
}

// Whether the person at this address is already in this organization.
//
// Asked at creation, where the actor holds members.write on the organization
// and could read its member list anyway, so answering it discloses nothing they
// could not already see. Redemption asks the same question of a user id it has
// already resolved, and answers it with the same generic refusal as every other
// failure.
func (q *Queries) CountMembershipsForEmail(ctx context.Context, arg CountMembershipsForEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsForEmail, arg.OrganizationID, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembershipsForUser = `-- name: CountMembershipsForUser :one
SELECT count(*) FROM memberships
WHERE organization_id = $1 AND user_id = $2
`

type CountMembershipsForUserParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) CountMembershipsForUser(ctx context.Context, arg CountMembershipsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsForUser, arg.OrganizationID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO invitations (
    id, organization_id, email, role_id, token_hash, invited_by, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, email, email_lower, role_id, token_hash, invited_by, created_at, expires_at, revoked_at, redeemed_at, redeemed_by
`

type CreateInvitationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	RoleID         uuid.UUID
	TokenHash      []byte
	InvitedBy      *uuid.UUID
	ExpiresAt      time.Time
}

// Invitations: issuing, listing, revoking and redeeming (M27).
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.RoleID,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.EmailLower,
		&i.RoleID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
	)
	return i, err
}

const getBuiltinRoleBySlug = `-- name: GetBuiltinRoleBySlug :one
SELECT id, slug, name, rank
FROM roles
WHERE slug = $1 AND organization_id IS NULL
`

type GetBuiltinRoleBySlugRow struct {
	ID   uuid.UUID
	Slug string
	Name string
	Rank int32
}

func (q *Queries) GetBuiltinRoleBySlug(ctx context.Context, slug string) (GetBuiltinRoleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBuiltinRoleBySlug, slug)
	var i GetBuiltinRoleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Rank,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT
    i.id, i.organization_id, i.email, i.email_lower, i.role_id,
    i.invited_by, i.created_at, i.expires_at, i.revoked_at, i.redeemed_at,
    r.slug AS role_slug,
    o.name AS organization_name
FROM invitations i
JOIN roles r         ON r.id = i.role_id
JOIN organizations o ON o.id = i.organization_id
WHERE i.token_hash = $1
  AND o.deleted_at IS NULL
FOR UPDATE OF i
`

type GetInvitationByTokenHashRow struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Email            string
	EmailLower       *string
	RoleID           uuid.UUID
	InvitedBy        *uuid.UUID
	CreatedAt        time.Time
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	RedeemedAt       *time.Time
	RoleSlug         string
	OrganizationName string
}

// Redemption's only lookup, and the row it locks.
//
// FOR UPDATE OF i serializes two redemptions of the same token: the second
// blocks until the first commits and then reads redeemed_at set, so single-use
// is enforced by the database rather than by a check-then-act in Go. The joined
// tables are not locked — they are read for their labels, and locking a role
// row would block every other invite that names it.
//
// Expiry and revocation are deliberately NOT in the WHERE clause. The caller
// has to tell "no such token" from "expired" apart to decide what to log, and
// it answers all of them identically to the person redeeming (decision D27).
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash []byte) (GetInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i GetInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.EmailLower,
		&i.RoleID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RedeemedAt,
		&i.RoleSlug,
		&i.OrganizationName,
	)
	return i, err
}

const getOrganizationName = `-- name: GetOrganizationName :one
SELECT name FROM organizations WHERE id = $1 AND deleted_at IS NULL
`

// What to call the organization in an invitation. A primary-key lookup on a
// path that is already writing a row, rather than carrying a name on every
// identity for the one surface that needs it.
func (q *Queries) GetOrganizationName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOrganizationName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listBuiltinRoles = `-- name: ListBuiltinRoles :many
SELECT id, slug, name, description, rank
FROM roles
WHERE organization_id IS NULL AND is_builtin
ORDER BY rank
`

type ListBuiltinRolesRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description string
	Rank        int32
}

// The four seeded roles, most powerful first. Feeds the invite form's role
// choices, filtered by the inviter's own rank in the service (decision D28).
func (q *Queries) ListBuiltinRoles(ctx context.Context) ([]ListBuiltinRolesRow, error) {
	rows, err := q.db.Query(ctx, listBuiltinRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuiltinRolesRow{}
	for rows.Next() {
		var i ListBuiltinRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT
    i.id, i.email, i.created_at, i.expires_at, i.revoked_at, i.redeemed_at,
    r.slug AS role_slug,
    r.rank AS role_rank,
    coalesce(u.email, '') AS invited_by_label
FROM invitations i
JOIN roles r      ON r.id = i.role_id
LEFT JOIN users u ON u.id = i.invited_by
WHERE i.organization_id = $1
ORDER BY i.created_at DESC, i.id DESC
`

type ListInvitationsRow struct {
	ID             uuid.UUID
	Email          string
	CreatedAt      time.Time
	ExpiresAt      time.Time
	RevokedAt      *time.Time
	RedeemedAt     *time.Time
	RoleSlug       string
	RoleRank       int32
	InvitedByLabel string
}

// The administrator's list, newest first.
//
// No pagination and no cursor. An organization's outstanding invitations are a
// handful of rows by construction, and redeemed ones stop accumulating the
// moment people join; the link list's machinery here would be a page that
// cannot fill.
//
// The inviter is joined as a label rather than an id, for the same reason the
// audit log stores one: the row has to stay readable after that account is
// gone, and the LEFT JOIN is what lets it.
func (q *Queries) ListInvitations(ctx context.Context, organizationID uuid.UUID) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RedeemedAt,
			&i.RoleSlug,
			&i.RoleRank,
			&i.InvitedByLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationRedeemed = `-- name: MarkInvitationRedeemed :execrows
UPDATE invitations
   SET redeemed_at = now(),
       redeemed_by = $2
 WHERE id = $1
   AND revoked_at IS NULL
   AND redeemed_at IS NULL
   AND expires_at > now()
`

type MarkInvitationRedeemedParams struct {
	ID         uuid.UUID
	RedeemedBy *uuid.UUID
}

// The single-use write. Conditional on the invite still being redeemable, so
// even without the lock above this could not be spent twice.
func (q *Queries) MarkInvitationRedeemed(ctx context.Context, arg MarkInvitationRedeemedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInvitationRedeemed, arg.ID, arg.RedeemedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const peekInvitationByTokenHash = `-- name: PeekInvitationByTokenHash :one
SELECT
    i.id, i.organization_id, i.email, i.email_lower, i.role_id,
    i.invited_by, i.created_at, i.expires_at, i.revoked_at, i.redeemed_at,
    r.slug AS role_slug,
    o.name AS organization_name
FROM invitations i
JOIN roles r         ON r.id = i.role_id
JOIN organizations o ON o.id = i.organization_id
WHERE i.token_hash = $1
  AND o.deleted_at IS NULL
`

type PeekInvitationByTokenHashRow struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Email            string
	EmailLower       *string
	RoleID           uuid.UUID
	InvitedBy        *uuid.UUID
	CreatedAt        time.Time
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	RedeemedAt       *time.Time
	RoleSlug         string
	OrganizationName string
}

// The same lookup without the lock, for rendering the redemption page.
//
// A GET must not take a row lock: the page is served to anybody holding the
// link, and a locking read there would let a stranger hold a write lock on the
// row by opening a page.
func (q *Queries) PeekInvitationByTokenHash(ctx context.Context, tokenHash []byte) (PeekInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, peekInvitationByTokenHash, tokenHash)
	var i PeekInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.EmailLower,
		&i.RoleID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RedeemedAt,
		&i.RoleSlug,
		&i.OrganizationName,
	)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE invitations
   SET revoked_at = now()
 WHERE id = $1
   AND organization_id = $2
   AND revoked_at IS NULL
   AND redeemed_at IS NULL
`

type RevokeInvitationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Scoped by organization as well as id, so an id from another organization is
// indistinguishable from one that does not exist: both change zero rows.
//
// Already-revoked and already-redeemed are excluded rather than tolerated. A
// redeemed invite has produced a member, and reporting "revoked" for it would
// claim something the tree does not support.
func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLapsedInvitation = `-- name: RevokeLapsedInvitation :execrows
UPDATE invitations
   SET revoked_at = now()
 WHERE organization_id = $1
   AND email_lower = lower($2::text)
   AND revoked_at IS NULL
   AND redeemed_at IS NULL
   AND expires_at <= now()
`

type RevokeLapsedInvitationParams struct {
	OrganizationID uuid.UUID
	Email          string
}

// Clears an expired invite out of the outstanding slot so a replacement can be
// issued.
//
// The partial unique index cannot exclude expired rows — `now()` is not
// immutable, so Postgres will not index on it — which means an invite that
// lapsed still occupies the address. This runs immediately before the insert,
// in the same transaction, and touches nothing that is still redeemable.
func (q *Queries) RevokeLapsedInvitation(ctx context.Context, arg RevokeLapsedInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLapsedInvitation, arg.OrganizationID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
