// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveLink = `-- name: ArchiveLink :one
UPDATE links
   SET status = 'archived', archived_at = now(), updated_at = now()
 WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id, bot_blocking, forward_path, require_signature
`

type ArchiveLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) ArchiveLink(ctx context.Context, arg ArchiveLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, archiveLink, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
		&i.BotBlocking,
		&i.ForwardPath,
		&i.RequireSignature,
	)
	return i, err
}

const attachTag = `-- name: AttachTag :exec
INSERT INTO link_tags (link_id, tag_id, workspace_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AttachTagParams struct {
	LinkID      uuid.UUID
	TagID       uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.Exec(ctx, attachTag, arg.LinkID, arg.TagID, arg.WorkspaceID)
	return err
}

const countLinks = `-- name: CountLinks :one
SELECT count(*) FROM links l
WHERE l.workspace_id = $1
  AND l.deleted_at IS NULL
  -- Filtered on effective status, not the stored column: nothing ever writes
  -- 'expired', so ` + "`" + `?status=expired` + "`" + ` matched no row while expired links listed
  -- themselves as active. Must stay identical to domain.EffectiveStatus and to
  -- Snapshot.Decide, expiry outranking an archived status in all three.
  AND ($2::text IS NULL
       OR CASE WHEN l.expires_at IS NOT NULL AND l.expires_at <= now()
               THEN 'expired' ELSE l.status END = $2::text)
  AND ($3::text IS NULL
       -- A degenerate query means "no filter", not "match nothing".
       -- websearch_to_tsquery returns an empty tsquery for a stopword ("and")
       -- or pure punctuation ("!!"), and without this branch a user typing
       -- either gets an empty list and concludes their links have vanished.
       OR websearch_to_tsquery('english', $3::text) = ''::tsquery
       OR l.search_vector @@ websearch_to_tsquery('english', $3::text)
       OR l.alias ILIKE '%' || $3::text || '%'
       OR l.primary_url ILIKE '%' || $3::text || '%')
  -- Must mirror ListLinks exactly. Without this branch a tag-filtered page
  -- reported the workspace's whole link count as its total, so "8 of 100" was
  -- shown for a filter matching 8 of 8.
  AND ($4::uuid[] IS NULL
       OR EXISTS (SELECT 1 FROM link_tags lt
                   WHERE lt.link_id = l.id
                     AND lt.tag_id = ANY($4::uuid[])))
  -- Must mirror ListLinks exactly, for the reason the tag filter above says in
  -- full: a folder-filtered page whose total counted the whole workspace would
  -- read "3 of 40 links" under a list of every link in one folder.
  AND (NOT $5::boolean OR l.folder_id IS NULL)
  AND ($6::uuid IS NULL OR l.folder_id = $6::uuid)
  -- Must mirror ListLinks exactly (M41), for the reason the folder pair above
  -- says in full: a campaign-filtered page whose total counted the workspace
  -- would read "5 of 40 links" over a list of five.
  AND (NOT $7::boolean OR l.campaign_id IS NULL)
  AND ($8::uuid IS NULL OR l.campaign_id = $8::uuid)
  -- Must mirror ListLinks exactly, for the reason the two filters above say in
  -- full: a page filtered to one hostname whose total counted every domain
  -- would read "4 of 40 links" over a list of four.
  AND ($9::uuid IS NULL OR l.domain_id = $9::uuid)
`

type CountLinksParams struct {
	WorkspaceID  uuid.UUID
	Status       *string
	Search       *string
	TagIds       []uuid.UUID
	Unfiled      bool
	FolderID     *uuid.UUID
	Uncampaigned bool
	CampaignID   *uuid.UUID
	DomainID     *uuid.UUID
}

// Only issued when the caller explicitly asks for a total, because counting
// costs a scan the common page load should not pay for.
func (q *Queries) CountLinks(ctx context.Context, arg CountLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks,
		arg.WorkspaceID,
		arg.Status,
		arg.Search,
		arg.TagIds,
		arg.Unfiled,
		arg.FolderID,
		arg.Uncampaigned,
		arg.CampaignID,
		arg.DomainID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDestination = `-- name: CreateDestination :one
INSERT INTO destinations (id, link_id, workspace_id, url, url_host, position)
VALUES ($1, $2, $3, $4, $5, 0)
RETURNING id, link_id, workspace_id, url, url_host, label, weight, position, created_at, updated_at, deleted_at
`

type CreateDestinationParams struct {
	ID          uuid.UUID
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
	Url         string
	UrlHost     string
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createDestination,
		arg.ID,
		arg.LinkID,
		arg.WorkspaceID,
		arg.Url,
		arg.UrlHost,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.Url,
		&i.UrlHost,
		&i.Label,
		&i.Weight,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLink = `-- name: CreateLink :one

INSERT INTO links (
    id, workspace_id, domain_id, alias, primary_url,
    title, description, status, expires_at, created_by, forward_query,
    forward_path, password_hash, max_clicks, one_time, require_signature,
    folder_id, campaign_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id, bot_blocking, forward_path, require_signature
`

type CreateLinkParams struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	DomainID         uuid.UUID
	Alias            string
	PrimaryUrl       string
	Title            string
	Description      string
	Status           string
	ExpiresAt        *time.Time
	CreatedBy        *uuid.UUID
	ForwardQuery     bool
	ForwardPath      bool
	PasswordHash     *string
	MaxClicks        *int64
	OneTime          bool
	RequireSignature bool
	FolderID         *uuid.UUID
	CampaignID       *uuid.UUID
}

// Links, destinations and tags.
func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.ID,
		arg.WorkspaceID,
		arg.DomainID,
		arg.Alias,
		arg.PrimaryUrl,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.ForwardQuery,
		arg.ForwardPath,
		arg.PasswordHash,
		arg.MaxClicks,
		arg.OneTime,
		arg.RequireSignature,
		arg.FolderID,
		arg.CampaignID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
		&i.BotBlocking,
		&i.ForwardPath,
		&i.RequireSignature,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (id, workspace_id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, color, created_at
`

type CreateTagParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Color       string
}

// --- tags -------------------------------------------------------------------
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1 AND workspace_id = $2
`

type DeleteTagParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachAllTags = `-- name: DetachAllTags :exec
DELETE FROM link_tags WHERE link_id = $1
`

func (q *Queries) DetachAllTags(ctx context.Context, linkID uuid.UUID) error {
	_, err := q.db.Exec(ctx, detachAllTags, linkID)
	return err
}

const getDefaultDomainSettings = `-- name: GetDefaultDomainSettings :one
SELECT id, hostname, root_redirect_url, block_bots, block_bots_enforced
FROM domains
WHERE id = $1 AND deleted_at IS NULL
`

type GetDefaultDomainSettingsRow struct {
	ID                uuid.UUID
	Hostname          string
	RootRedirectUrl   *string
	BlockBots         bool
	BlockBotsEnforced bool
}

// One domain's settings and where its root points.
//
// **The filter its own comment promised** (M40). It read `WHERE is_default`,
// which was the whole truth while an instance had exactly one domain and became
// a way of asking the wrong row the moment it had several: a verified custom
// hostname has a root of its own, and reading its settings through a predicate
// that can only ever return the default would answer about somebody else's
// hostname.
//
// Not scoped by owner, like every other statement addressed by id in this
// schema. link.Service has already judged the actor against the row.
func (q *Queries) GetDefaultDomainSettings(ctx context.Context, domainID uuid.UUID) (GetDefaultDomainSettingsRow, error) {
	row := q.db.QueryRow(ctx, getDefaultDomainSettings, domainID)
	var i GetDefaultDomainSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.RootRedirectUrl,
		&i.BlockBots,
		&i.BlockBotsEnforced,
	)
	return i, err
}

const getDomainBotSettings = `-- name: GetDomainBotSettings :one
SELECT id, hostname, block_bots, block_bots_enforced
FROM domains
WHERE id = $1 AND deleted_at IS NULL
`

type GetDomainBotSettingsRow struct {
	ID                uuid.UUID
	Hostname          string
	BlockBots         bool
	BlockBotsEnforced bool
}

// One domain's bot policy, by id.
//
// Read on the management path only, and only when a link's own setting is being
// changed: the service has to know whether the domain enforces before it can
// tell the caller their `off` will not be honoured. The redirect path never
// runs this — it gets the same two columns from ResolveAliasForRedirect's join,
// which is the whole reason that join exists.
func (q *Queries) GetDomainBotSettings(ctx context.Context, id uuid.UUID) (GetDomainBotSettingsRow, error) {
	row := q.db.QueryRow(ctx, getDomainBotSettings, id)
	var i GetDomainBotSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.BlockBots,
		&i.BlockBotsEnforced,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id, bot_blocking, forward_path, require_signature FROM links
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Workspace-scoped by design. Passing the workspace here rather than checking
// it after the fetch makes cross-tenant reads impossible to write by accident:
// the wrong workspace returns no rows rather than a row the caller must
// remember to reject.
func (q *Queries) GetLink(ctx context.Context, arg GetLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
		&i.BotBlocking,
		&i.ForwardPath,
		&i.RequireSignature,
	)
	return i, err
}

const getLinkByAlias = `-- name: GetLinkByAlias :one
SELECT id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id, bot_blocking, forward_path, require_signature FROM links
WHERE domain_id = $1 AND alias = $2 AND deleted_at IS NULL
`

type GetLinkByAliasParams struct {
	DomainID uuid.UUID
	Alias    string
}

func (q *Queries) GetLinkByAlias(ctx context.Context, arg GetLinkByAliasParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByAlias, arg.DomainID, arg.Alias)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
		&i.BotBlocking,
		&i.ForwardPath,
		&i.RequireSignature,
	)
	return i, err
}

const getLinkTags = `-- name: GetLinkTags :many
SELECT t.id, t.name, t.color
FROM link_tags lt JOIN tags t ON t.id = lt.tag_id
WHERE lt.link_id = $1
ORDER BY t.name
`

type GetLinkTagsRow struct {
	ID    uuid.UUID
	Name  string
	Color string
}

func (q *Queries) GetLinkTags(ctx context.Context, linkID uuid.UUID) ([]GetLinkTagsRow, error) {
	rows, err := q.db.Query(ctx, getLinkTags, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLinkTagsRow{}
	for rows.Next() {
		var i GetLinkTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, workspace_id, name, color, created_at FROM tags WHERE workspace_id = $1 AND lower(name) = lower($2)
`

type GetTagByNameParams struct {
	WorkspaceID uuid.UUID
	Lower       string
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.WorkspaceID, arg.Lower)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceDefaultDomain = `-- name: GetWorkspaceDefaultDomain :one
SELECT id, hostname, organization_id, workspace_id FROM domains
WHERE deleted_at IS NULL
  AND (
        is_default
     OR (verified_at IS NOT NULL AND workspace_id = $1)
     OR (verified_at IS NOT NULL AND workspace_id IS NULL
         AND organization_id = $2)
      )
ORDER BY
    CASE WHEN workspace_id = $1 THEN 0
         WHEN NOT is_default                        THEN 1
         ELSE 2 END,
    verified_at, id
LIMIT 1
`

type GetWorkspaceDefaultDomainParams struct {
	WorkspaceID    *uuid.UUID
	OrganizationID *uuid.UUID
}

type GetWorkspaceDefaultDomainRow struct {
	ID             uuid.UUID
	Hostname       string
	OrganizationID *uuid.UUID
	WorkspaceID    *uuid.UUID
}

// The hostname a new link goes on when the caller names none.
//
// **This is the filter the name promised and the query never had** (M40). It
// read `WHERE is_default` with no workspace argument at all, so every workspace
// on the instance got the same answer and the word "workspace" in the name was
// describing an intention rather than a predicate.
//
// A workspace's own *verified* hostname wins over the instance default, which is
// what registering one is for; the instance default is the fallback and is what
// every workspace without one still gets, unchanged. Organization-owned
// hostnames sit between the two — every workspace in the organization may use
// one, so it is more specific than the instance and less than a workspace's own.
//
// **Verified only.** An unverified hostname is not a routing target, so putting
// a link on it would mint a short URL that resolves nowhere; the ordering below
// cannot reach one because the WHERE clause has already excluded it.
//
// Ties are broken by verified_at then id, so the answer is stable: a workspace
// that verifies a second hostname does not silently move its new links onto it.
// organization_id and workspace_id are selected because they are the domain's
// *scope*, and the scope is what decides whether an alias collision on it could
// involve a workspace the caller cannot see. A refusal that cannot tell a shared
// namespace from a private one has to be worded for the worst case or say
// nothing useful at all (F23).
func (q *Queries) GetWorkspaceDefaultDomain(ctx context.Context, arg GetWorkspaceDefaultDomainParams) (GetWorkspaceDefaultDomainRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceDefaultDomain, arg.WorkspaceID, arg.OrganizationID)
	var i GetWorkspaceDefaultDomainRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.OrganizationID,
		&i.WorkspaceID,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT
    l.id, l.workspace_id, l.domain_id, l.folder_id, l.alias, l.primary_url, l.primary_destination_id, l.title, l.description, l.status, l.expires_at, l.password_hash, l.max_clicks, l.one_time, l.forward_query, l.click_count, l.last_click_at, l.created_by, l.created_at, l.updated_at, l.archived_at, l.deleted_at, l.purge_after, l.search_vector, l.campaign_id, l.bot_blocking, l.forward_path, l.require_signature,
    COALESCE(tg.names, ARRAY[]::text[])::text[] AS tag_names,
    COALESCE(tg.ids, ARRAY[]::text[])::text[]   AS tag_ids
FROM links l
LEFT JOIN LATERAL (
    SELECT array_agg(t.name ORDER BY t.name, t.id)     AS names,
           array_agg(t.id::text ORDER BY t.name, t.id) AS ids
      FROM link_tags lt JOIN tags t ON t.id = lt.tag_id
     WHERE lt.link_id = l.id
) tg ON true
WHERE l.workspace_id = $1
  AND l.deleted_at IS NULL
  -- Filtered on effective status, not the stored column: nothing ever writes
  -- 'expired', so ` + "`" + `?status=expired` + "`" + ` matched no row while expired links listed
  -- themselves as active. Must stay identical to domain.EffectiveStatus and to
  -- Snapshot.Decide, expiry outranking an archived status in all three.
  AND ($2::text IS NULL
       OR CASE WHEN l.expires_at IS NOT NULL AND l.expires_at <= now()
               THEN 'expired' ELSE l.status END = $2::text)
  -- Full-text first, then trigram substring. websearch_to_tsquery returns an
  -- empty query for input like "and" or "!!", which matches nothing, so the
  -- caller treats a blank search as no filter rather than as zero results.
  AND ($3::text IS NULL
       -- A degenerate query means "no filter", not "match nothing".
       -- websearch_to_tsquery returns an empty tsquery for a stopword ("and")
       -- or pure punctuation ("!!"), and without this branch a user typing
       -- either gets an empty list and concludes their links have vanished.
       OR websearch_to_tsquery('english', $3::text) = ''::tsquery
       OR l.search_vector @@ websearch_to_tsquery('english', $3::text)
       OR l.alias ILIKE '%' || $3::text || '%'
       OR l.primary_url ILIKE '%' || $3::text || '%')
  AND ($4::uuid[] IS NULL
       OR EXISTS (SELECT 1 FROM link_tags lt
                   WHERE lt.link_id = l.id
                     AND lt.tag_id = ANY($4::uuid[])))
  -- The folder filter (M38), in two halves because "no filter" and "the links
  -- that are in no folder" are different questions and a nullable id can only
  -- ask one of them. ` + "`" + `unfiled` + "`" + ` is the second; without it there is no way to find
  -- the links that were never filed, which is the state every link starts in.
  --
  -- One folder, not its subtree. The number this filter returns has to be the
  -- number shown beside the folder on the tree page, and a parent that reported
  -- its descendants' links would disagree with it — and would put a recursive
  -- walk inside the dashboard's hottest query to do so.
  AND (NOT $5::boolean OR l.folder_id IS NULL)
  AND ($6::uuid IS NULL OR l.folder_id = $6::uuid)
  -- The campaign filter (M41), in two halves for the reason the folder pair
  -- above is: "no filter" and "the links in no campaign" are different
  -- questions. ` + "`" + `uncampaigned` + "`" + ` is what the campaigns page links to when somebody
  -- asks which links are not attributed to anything yet, which is the question
  -- every campaign list eventually raises.
  AND (NOT $7::boolean OR l.campaign_id IS NULL)
  AND ($8::uuid IS NULL OR l.campaign_id = $8::uuid)
  -- Which hostname the link is served on (M40). One filter and no ` + "`" + `unhosted` + "`" + `
  -- half, unlike the folder pair above: ` + "`" + `links.domain_id` + "`" + ` is NOT NULL, so there
  -- is no third state to ask about — every link is on exactly one domain, and
  -- "no filter" is the only other question there is.
  AND ($9::uuid IS NULL OR l.domain_id = $9::uuid)
  -- Keyset pagination only works if the predicate compares the same tuple the
  -- ORDER BY sorts on. It did not: every sort filtered on (created_at, id)
  -- while 'clicks' ordered by click_count, so page 2 dropped rows that belonged
  -- on it and repeated rows already shown. Each branch below pairs with the
  -- correspondingly-named ORDER BY key, and the id tiebreaker matches its
  -- direction — 'oldest' ascends, so its tiebreaker ascends too.
  AND (
        $10::uuid IS NULL
        OR ($11::text = 'oldest'
              AND (l.created_at, l.id) > ($12::timestamptz, $10::uuid))
        OR ($11::text = 'clicks'
              AND (l.click_count, l.id) < ($13::bigint, $10::uuid))
        OR ($11::text NOT IN ('oldest','clicks')
              AND (l.created_at, l.id) < ($12::timestamptz, $10::uuid))
      )
ORDER BY
    CASE WHEN $11::text = 'oldest' THEN l.created_at END ASC,
    CASE WHEN $11::text = 'clicks' THEN l.click_count END DESC,
    CASE WHEN $11::text NOT IN ('oldest','clicks') THEN l.created_at END DESC,
    -- Ascending tiebreaker for the ascending sort. For the others this key is
    -- NULL on every row, so it ties and the DESC key below decides.
    CASE WHEN $11::text = 'oldest' THEN l.id END ASC,
    l.id DESC
LIMIT $14
`

type ListLinksParams struct {
	WorkspaceID   uuid.UUID
	Status        *string
	Search        *string
	TagIds        []uuid.UUID
	Unfiled       bool
	FolderID      *uuid.UUID
	Uncampaigned  bool
	CampaignID    *uuid.UUID
	DomainID      *uuid.UUID
	CursorID      *uuid.UUID
	Sort          string
	CursorCreated *time.Time
	CursorClicks  *int64
	PageLimit     int32
}

type ListLinksRow struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	DomainID             uuid.UUID
	FolderID             *uuid.UUID
	Alias                string
	PrimaryUrl           string
	PrimaryDestinationID *uuid.UUID
	Title                string
	Description          string
	Status               string
	ExpiresAt            *time.Time
	PasswordHash         *string
	MaxClicks            *int64
	OneTime              bool
	ForwardQuery         bool
	ClickCount           int64
	LastClickAt          *time.Time
	CreatedBy            *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ArchivedAt           *time.Time
	DeletedAt            *time.Time
	PurgeAfter           *time.Time
	SearchVector         interface{}
	CampaignID           *uuid.UUID
	BotBlocking          string
	ForwardPath          bool
	RequireSignature     bool
	TagNames             []string
	TagIds               []string
}

// Keyset pagination over (created_at, id).
//
// The cursor is a composite so ordering is total: created_at alone is not
// unique, and a tie at the page boundary would drop or duplicate rows.
// Comparing the pair with row-value syntax lets the composite index serve it
// directly.
//
// Sorting is a CASE rather than three separate queries because sqlc has no
// dynamic SQL. If plan stability becomes a problem this splits into
// ListLinksNewest/Oldest/Clicks; measure before doing that.
// The two tag aggregates are paired positionally by the caller, so they must
// agree on their order — and on the table they read. Aggregating names from a
// join and ids from link_tags alone, each sorted by its own column, produced
// arrays in different orders whenever a link's tags sorted differently by name
// than by id, and every tag came back carrying another tag's name. One
// subquery, one ORDER BY, both columns.
func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]ListLinksRow, error) {
	rows, err := q.db.Query(ctx, listLinks,
		arg.WorkspaceID,
		arg.Status,
		arg.Search,
		arg.TagIds,
		arg.Unfiled,
		arg.FolderID,
		arg.Uncampaigned,
		arg.CampaignID,
		arg.DomainID,
		arg.CursorID,
		arg.Sort,
		arg.CursorCreated,
		arg.CursorClicks,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksRow{}
	for rows.Next() {
		var i ListLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DomainID,
			&i.FolderID,
			&i.Alias,
			&i.PrimaryUrl,
			&i.PrimaryDestinationID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ExpiresAt,
			&i.PasswordHash,
			&i.MaxClicks,
			&i.OneTime,
			&i.ForwardQuery,
			&i.ClickCount,
			&i.LastClickAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.PurgeAfter,
			&i.SearchVector,
			&i.CampaignID,
			&i.BotBlocking,
			&i.ForwardPath,
			&i.RequireSignature,
			&i.TagNames,
			&i.TagIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.workspace_id, t.name, t.color, t.created_at, count(l.id) AS link_count
FROM tags t
LEFT JOIN link_tags lt ON lt.tag_id = t.id
LEFT JOIN links l ON l.id = lt.link_id AND l.deleted_at IS NULL
WHERE t.workspace_id = $1
GROUP BY t.id
ORDER BY t.name
`

type ListTagsRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Color       string
	CreatedAt   time.Time
	LinkCount   int64
}

// Counts l.id, not lt.link_id. The join onto links is what excludes trashed
// links, but counting the link_tags column ignored it: a LEFT JOIN keeps the
// link_tags row when its link is soft-deleted, so the count included trashed
// links for the whole 30-day window and the tag list disagreed with the link
// list it filters.
func (q *Queries) ListTags(ctx context.Context, workspaceID uuid.UUID) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLink = `-- name: LockLink :one
SELECT id FROM links WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

// The link row, locked, for a guard whose decision is a count.
//
// A count cannot be locked, so `SELECT count(*)` as a ceiling check is a
// check-then-act: two writers each read a state the other is changing, and both
// pass a limit neither would pass alone. This is `LockOrganizations`' pattern at
// the link level — take the lock on the parent, make the decision inside the
// transaction that writes, and let the second writer block until the first
// commits and then re-read what it left behind.
//
// Locking the *link* rather than the rules is what makes it work with nothing to
// lock in the empty case. Postgres takes `FOR KEY SHARE` on a parent when a row
// referencing it is inserted, and that conflicts with `FOR UPDATE` — so a locked
// link cannot acquire a routing rule or a split arm while the guard is deciding,
// including the first one, where a lock on the rules would have had no rows to
// take (F67).
//
// Returns the id alone: the caller already has the link, and this exists for its
// lock rather than for its columns. No workspace parameter, for the same reason
// — every caller has already been through GetLink, which is workspace-scoped, so
// adding one here would be a second tenancy check in a statement whose job is
// serialization.
func (q *Queries) LockLink(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockLink, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const purgeExpiredLinks = `-- name: PurgeExpiredLinks :many
WITH doomed AS (
    SELECT id, domain_id, alias, click_count
      FROM links
     WHERE deleted_at IS NOT NULL
       AND purge_after IS NOT NULL
       AND purge_after < now()
     ORDER BY purge_after
     LIMIT $1::int
       FOR UPDATE SKIP LOCKED
),
reserve AS (
    INSERT INTO reserved_aliases (domain_id, alias, reason)
    SELECT domain_id, alias, 'purged with traffic'
      FROM doomed
     WHERE click_count > 0
    ON CONFLICT DO NOTHING
)
DELETE FROM links l
 USING doomed d
 WHERE l.id = d.id
RETURNING l.alias, (d.click_count > 0)::boolean AS reserved
`

type PurgeExpiredLinksRow struct {
	Alias    string
	Reserved bool
}

// The end of the trash window: hard-delete links whose purge_after has passed.
//
// One statement, so the reservation and the deletion cannot be separated by a
// crash: an alias that ever received traffic is written to reserved_aliases in
// the same command that removes its row, and ON CONFLICT makes a retried run
// converge rather than fail. Aliases that never received a click are released —
// deliberately, per the reserved_aliases rationale: nothing in the wild points
// at them, so permanent reservation would only bleed the namespace.
//
// SKIP LOCKED so the purge can never block, or be blocked by, a concurrent
// restore-by-hand of the same row; a skipped row is caught on the next run.
// Destinations and link_tags follow by ON DELETE CASCADE. click_events rows
// carry no FK (partitioned) and are dropped by analytics retention instead.
func (q *Queries) PurgeExpiredLinks(ctx context.Context, batchSize int32) ([]PurgeExpiredLinksRow, error) {
	rows, err := q.db.Query(ctx, purgeExpiredLinks, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurgeExpiredLinksRow{}
	for rows.Next() {
		var i PurgeExpiredLinksRow
		if err := rows.Scan(&i.Alias, &i.Reserved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveAlias = `-- name: ReserveAlias :exec
INSERT INTO reserved_aliases (domain_id, alias, reason)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ReserveAliasParams struct {
	DomainID uuid.UUID
	Alias    string
	Reason   string
}

// Called before purging a link that has clicks. The alias is in the wild — on
// printed material and in other people's bookmarks — so handing it to a new
// destination would be a redirect hijack.
func (q *Queries) ReserveAlias(ctx context.Context, arg ReserveAliasParams) error {
	_, err := q.db.Exec(ctx, reserveAlias, arg.DomainID, arg.Alias, arg.Reason)
	return err
}

const restoreLink = `-- name: RestoreLink :one
UPDATE links
   SET status = 'active', archived_at = NULL, updated_at = now()
 WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id, bot_blocking, forward_path, require_signature
`

type RestoreLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) RestoreLink(ctx context.Context, arg RestoreLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, restoreLink, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
		&i.BotBlocking,
		&i.ForwardPath,
		&i.RequireSignature,
	)
	return i, err
}

const setBotBlockingForEveryDomain = `-- name: SetBotBlockingForEveryDomain :many
WITH updated AS (
    UPDATE domains
       SET block_bots          = $1::boolean,
           block_bots_enforced = $2::boolean,
           updated_at          = now()
     WHERE deleted_at IS NULL
    RETURNING id, hostname, root_redirect_url, block_bots, block_bots_enforced, is_default
)
SELECT id, hostname, root_redirect_url, block_bots, block_bots_enforced, is_default
FROM updated
ORDER BY is_default DESC, hostname
`

type SetBotBlockingForEveryDomainParams struct {
	BlockBots         bool
	BlockBotsEnforced bool
}

type SetBotBlockingForEveryDomainRow struct {
	ID                uuid.UUID
	Hostname          string
	RootRedirectUrl   *string
	BlockBots         bool
	BlockBotsEnforced bool
	IsDefault         bool
}

// Both switches at once, because they are one setting with two halves and the
// CHECK in 01800 refuses the combination that writing them separately would pass
// through on the way. That applies row by row, so a propagation that touched one
// column would be refused by the constraint on the way out.
//
// **Every undeleted domain, not only the default (F89).** This was
// `WHERE is_default` until M45, which was the whole truth while the instance
// default was the only domain there was. M40 added verified custom hostnames and
// `ResolveAliasForRedirect` reads the policy from the link's *own* domain row, so
// an operator who turned blocking on — even enforced — got no blocking on any
// link served on a custom hostname, and any workspace could open that hole for
// itself by registering one. Plan.md's "the domain's setting is instance-wide" is
// the claim being restored, and this is what makes it true.
//
// **Every updated row comes back, not just the default**, because each one is a
// cache invalidation the caller owes: a snapshot carries its domain's policy so
// the redirect path needs no second lookup, so every cached alias under every
// domain touched here is now wrong. The default is marked rather than sorted for,
// since it is the row the settings surfaces read and the hostname they name.
func (q *Queries) SetBotBlockingForEveryDomain(ctx context.Context, arg SetBotBlockingForEveryDomainParams) ([]SetBotBlockingForEveryDomainRow, error) {
	rows, err := q.db.Query(ctx, setBotBlockingForEveryDomain, arg.BlockBots, arg.BlockBotsEnforced)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetBotBlockingForEveryDomainRow{}
	for rows.Next() {
		var i SetBotBlockingForEveryDomainRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.RootRedirectUrl,
			&i.BlockBots,
			&i.BlockBotsEnforced,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultDomainRootRedirect = `-- name: SetDefaultDomainRootRedirect :one
UPDATE domains
   SET root_redirect_url = $1, updated_at = now()
 WHERE is_default AND deleted_at IS NULL
RETURNING id, hostname, root_redirect_url, block_bots, block_bots_enforced
`

type SetDefaultDomainRootRedirectRow struct {
	ID                uuid.UUID
	Hostname          string
	RootRedirectUrl   *string
	BlockBots         bool
	BlockBotsEnforced bool
}

// NULL clears it, which restores the 404 the root answered before anyone set
// anything.
func (q *Queries) SetDefaultDomainRootRedirect(ctx context.Context, rootRedirectUrl *string) (SetDefaultDomainRootRedirectRow, error) {
	row := q.db.QueryRow(ctx, setDefaultDomainRootRedirect, rootRedirectUrl)
	var i SetDefaultDomainRootRedirectRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.RootRedirectUrl,
		&i.BlockBots,
		&i.BlockBotsEnforced,
	)
	return i, err
}

const setPrimaryDestination = `-- name: SetPrimaryDestination :exec
UPDATE links SET primary_destination_id = $2, updated_at = now() WHERE id = $1
`

type SetPrimaryDestinationParams struct {
	ID                   uuid.UUID
	PrimaryDestinationID *uuid.UUID
}

func (q *Queries) SetPrimaryDestination(ctx context.Context, arg SetPrimaryDestinationParams) error {
	_, err := q.db.Exec(ctx, setPrimaryDestination, arg.ID, arg.PrimaryDestinationID)
	return err
}

const softDeleteLink = `-- name: SoftDeleteLink :one
UPDATE links
   SET deleted_at = now(),
       purge_after = now() + make_interval(days => $1::int),
       updated_at = now()
 WHERE id = $2 AND workspace_id = $3 AND deleted_at IS NULL
RETURNING id, alias, domain_id, click_count
`

type SoftDeleteLinkParams struct {
	RetentionDays int32
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
}

type SoftDeleteLinkRow struct {
	ID         uuid.UUID
	Alias      string
	DomainID   uuid.UUID
	ClickCount int64
}

// Soft delete with a purge deadline rather than an immediate DELETE. Restoring
// a link someone deleted by accident is a common request, and the alias stays
// reserved while the row exists.
func (q *Queries) SoftDeleteLink(ctx context.Context, arg SoftDeleteLinkParams) (SoftDeleteLinkRow, error) {
	row := q.db.QueryRow(ctx, softDeleteLink, arg.RetentionDays, arg.ID, arg.WorkspaceID)
	var i SoftDeleteLinkRow
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.DomainID,
		&i.ClickCount,
	)
	return i, err
}

const updateDestinationURL = `-- name: UpdateDestinationURL :exec
UPDATE destinations d
   SET url = $3, url_host = $4, updated_at = now()
  FROM links l
 WHERE l.id = $1
   AND l.workspace_id = $2
   AND d.id = l.primary_destination_id
   AND d.deleted_at IS NULL
`

type UpdateDestinationURLParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Url         string
	UrlHost     string
}

// The trigger on destinations mirrors this into links.primary_url, so the hot
// path never joins.
//
// Narrowed to the *primary* destination by M34, and the narrowing is the point
// rather than tidying. Until routing rules existed a link had exactly one
// destination row, so matching on link_id alone matched it; a rule target is a
// second row on the same link, and this query would have rewritten every one of
// them to the link's own URL the next time somebody edited the link. Every rule
// on the link would silently start pointing at the same place, which is
// indistinguishable from the rules having stopped working.
//
// Matched through links.primary_destination_id rather than through `position =
// 0`, because that column is what the sync trigger keys on and what the rest of
// the schema treats as the authority. Two definitions of "the primary" is how
// they come to disagree.
func (q *Queries) UpdateDestinationURL(ctx context.Context, arg UpdateDestinationURLParams) error {
	_, err := q.db.Exec(ctx, updateDestinationURL,
		arg.ID,
		arg.WorkspaceID,
		arg.Url,
		arg.UrlHost,
	)
	return err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
   SET title         = COALESCE($1, title),
       description   = COALESCE($2, description),
       expires_at    = CASE WHEN $3::boolean THEN NULL
                            ELSE COALESCE($4, expires_at) END,
       alias         = COALESCE($5, alias),
       forward_query = COALESCE($6, forward_query),
       forward_path  = COALESCE($7, forward_path),
       bot_blocking  = COALESCE($8, bot_blocking),
       -- The gates (M35). Each is three-valued through its own pair of
       -- arguments, because "leave it alone" and "remove it" are different
       -- requests and a nullable column cannot express both with one nullable
       -- parameter. clear_password wins over password_hash for the same reason
       -- clear_expiry wins over expires_at, and the order is the same.
       password_hash = CASE WHEN $9::boolean THEN NULL
                            ELSE COALESCE($10, password_hash) END,
       max_clicks    = CASE WHEN $11::boolean THEN NULL
                            ELSE COALESCE($12, max_clicks) END,
       one_time      = COALESCE($13, one_time),
       require_signature = COALESCE($14, require_signature),
       -- Which folder the link is filed in (M38). Three-valued for the reason
       -- the gates above are: "leave it where it is" and "take it out of every
       -- folder" are different requests, and a nullable column cannot express
       -- both through one nullable parameter. The service has already checked
       -- that the folder belongs to this workspace — the foreign key does not,
       -- because it points at folders(id) and says nothing about tenancy.
       folder_id     = CASE WHEN $15::boolean THEN NULL
                            ELSE COALESCE($16, folder_id) END,
       -- Which campaign the link belongs to (M41). Three-valued for the reason
       -- the folder above is, and the third state is the one that matters: a
       -- link joins a campaign by mistake as easily as it joins one on purpose,
       -- and without clear_campaign the only way out would be to delete the
       -- campaign, which would take every other link with it.
       campaign_id   = CASE WHEN $17::boolean THEN NULL
                            ELSE COALESCE($18, campaign_id) END,
       updated_at    = now()
 WHERE id = $19 AND workspace_id = $20 AND deleted_at IS NULL
RETURNING id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id, bot_blocking, forward_path, require_signature
`

type UpdateLinkParams struct {
	Title            *string
	Description      *string
	ClearExpiry      bool
	ExpiresAt        *time.Time
	Alias            *string
	ForwardQuery     *bool
	ForwardPath      *bool
	BotBlocking      *string
	ClearPassword    bool
	PasswordHash     *string
	ClearMaxClicks   bool
	MaxClicks        *int64
	OneTime          *bool
	RequireSignature *bool
	ClearFolder      bool
	FolderID         *uuid.UUID
	ClearCampaign    bool
	CampaignID       *uuid.UUID
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
}

// COALESCE with sqlc.narg gives partial update: a NULL argument leaves the
// column alone, so PATCH semantics need no dynamic SQL.
func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.Title,
		arg.Description,
		arg.ClearExpiry,
		arg.ExpiresAt,
		arg.Alias,
		arg.ForwardQuery,
		arg.ForwardPath,
		arg.BotBlocking,
		arg.ClearPassword,
		arg.PasswordHash,
		arg.ClearMaxClicks,
		arg.MaxClicks,
		arg.OneTime,
		arg.RequireSignature,
		arg.ClearFolder,
		arg.FolderID,
		arg.ClearCampaign,
		arg.CampaignID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
		&i.BotBlocking,
		&i.ForwardPath,
		&i.RequireSignature,
	)
	return i, err
}
