// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveLink = `-- name: ArchiveLink :one
UPDATE links
   SET status = 'archived', archived_at = now(), updated_at = now()
 WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id
`

type ArchiveLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) ArchiveLink(ctx context.Context, arg ArchiveLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, archiveLink, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
	)
	return i, err
}

const attachTag = `-- name: AttachTag :exec
INSERT INTO link_tags (link_id, tag_id, workspace_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AttachTagParams struct {
	LinkID      uuid.UUID
	TagID       uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.Exec(ctx, attachTag, arg.LinkID, arg.TagID, arg.WorkspaceID)
	return err
}

const countLinks = `-- name: CountLinks :one
SELECT count(*) FROM links l
WHERE l.workspace_id = $1
  AND l.deleted_at IS NULL
  AND ($2::text IS NULL OR l.status = $2::text)
  AND ($3::text IS NULL
       -- A degenerate query means "no filter", not "match nothing".
       -- websearch_to_tsquery returns an empty tsquery for a stopword ("and")
       -- or pure punctuation ("!!"), and without this branch a user typing
       -- either gets an empty list and concludes their links have vanished.
       OR websearch_to_tsquery('english', $3::text) = ''::tsquery
       OR l.search_vector @@ websearch_to_tsquery('english', $3::text)
       OR l.alias ILIKE '%' || $3::text || '%'
       OR l.primary_url ILIKE '%' || $3::text || '%')
`

type CountLinksParams struct {
	WorkspaceID uuid.UUID
	Status      *string
	Search      *string
}

// Only issued when the caller explicitly asks for a total, because counting
// costs a scan the common page load should not pay for.
func (q *Queries) CountLinks(ctx context.Context, arg CountLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks, arg.WorkspaceID, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDestination = `-- name: CreateDestination :one
INSERT INTO destinations (id, link_id, workspace_id, url, url_host, position)
VALUES ($1, $2, $3, $4, $5, 0)
RETURNING id, link_id, workspace_id, url, url_host, label, weight, position, created_at, updated_at, deleted_at
`

type CreateDestinationParams struct {
	ID          uuid.UUID
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
	Url         string
	UrlHost     string
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createDestination,
		arg.ID,
		arg.LinkID,
		arg.WorkspaceID,
		arg.Url,
		arg.UrlHost,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.Url,
		&i.UrlHost,
		&i.Label,
		&i.Weight,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLink = `-- name: CreateLink :one

INSERT INTO links (
    id, workspace_id, domain_id, alias, primary_url,
    title, description, status, expires_at, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id
`

type CreateLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DomainID    uuid.UUID
	Alias       string
	PrimaryUrl  string
	Title       string
	Description string
	Status      string
	ExpiresAt   *time.Time
	CreatedBy   *uuid.UUID
}

// Links, destinations and tags.
func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.ID,
		arg.WorkspaceID,
		arg.DomainID,
		arg.Alias,
		arg.PrimaryUrl,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (id, workspace_id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, color, created_at
`

type CreateTagParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Color       string
}

// --- tags -------------------------------------------------------------------
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1 AND workspace_id = $2
`

type DeleteTagParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachAllTags = `-- name: DetachAllTags :exec
DELETE FROM link_tags WHERE link_id = $1
`

func (q *Queries) DetachAllTags(ctx context.Context, linkID uuid.UUID) error {
	_, err := q.db.Exec(ctx, detachAllTags, linkID)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id FROM links
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Workspace-scoped by design. Passing the workspace here rather than checking
// it after the fetch makes cross-tenant reads impossible to write by accident:
// the wrong workspace returns no rows rather than a row the caller must
// remember to reject.
func (q *Queries) GetLink(ctx context.Context, arg GetLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
	)
	return i, err
}

const getLinkByAlias = `-- name: GetLinkByAlias :one
SELECT id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id FROM links
WHERE domain_id = $1 AND alias = $2 AND deleted_at IS NULL
`

type GetLinkByAliasParams struct {
	DomainID uuid.UUID
	Alias    string
}

func (q *Queries) GetLinkByAlias(ctx context.Context, arg GetLinkByAliasParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByAlias, arg.DomainID, arg.Alias)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
	)
	return i, err
}

const getLinkTags = `-- name: GetLinkTags :many
SELECT t.id, t.name, t.color
FROM link_tags lt JOIN tags t ON t.id = lt.tag_id
WHERE lt.link_id = $1
ORDER BY t.name
`

type GetLinkTagsRow struct {
	ID    uuid.UUID
	Name  string
	Color string
}

func (q *Queries) GetLinkTags(ctx context.Context, linkID uuid.UUID) ([]GetLinkTagsRow, error) {
	rows, err := q.db.Query(ctx, getLinkTags, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLinkTagsRow{}
	for rows.Next() {
		var i GetLinkTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, workspace_id, name, color, created_at FROM tags WHERE workspace_id = $1 AND lower(name) = lower($2)
`

type GetTagByNameParams struct {
	WorkspaceID uuid.UUID
	Lower       string
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.WorkspaceID, arg.Lower)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceDefaultDomain = `-- name: GetWorkspaceDefaultDomain :one
SELECT id, hostname FROM domains WHERE is_default AND deleted_at IS NULL
`

type GetWorkspaceDefaultDomainRow struct {
	ID       uuid.UUID
	Hostname string
}

func (q *Queries) GetWorkspaceDefaultDomain(ctx context.Context) (GetWorkspaceDefaultDomainRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceDefaultDomain)
	var i GetWorkspaceDefaultDomainRow
	err := row.Scan(&i.ID, &i.Hostname)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT
    l.id, l.workspace_id, l.domain_id, l.folder_id, l.alias, l.primary_url, l.primary_destination_id, l.title, l.description, l.status, l.expires_at, l.password_hash, l.max_clicks, l.one_time, l.forward_query, l.click_count, l.last_click_at, l.created_by, l.created_at, l.updated_at, l.archived_at, l.deleted_at, l.purge_after, l.search_vector, l.campaign_id,
    COALESCE(
        (SELECT array_agg(t.name ORDER BY t.name)
           FROM link_tags lt JOIN tags t ON t.id = lt.tag_id
          WHERE lt.link_id = l.id),
        ARRAY[]::text[]
    )::text[] AS tag_names,
    COALESCE(
        (SELECT array_agg(lt.tag_id::text ORDER BY lt.tag_id)
           FROM link_tags lt WHERE lt.link_id = l.id),
        ARRAY[]::text[]
    )::text[] AS tag_ids
FROM links l
WHERE l.workspace_id = $1
  AND l.deleted_at IS NULL
  AND ($2::text IS NULL OR l.status = $2::text)
  -- Full-text first, then trigram substring. websearch_to_tsquery returns an
  -- empty query for input like "and" or "!!", which matches nothing, so the
  -- caller treats a blank search as no filter rather than as zero results.
  AND ($3::text IS NULL
       -- A degenerate query means "no filter", not "match nothing".
       -- websearch_to_tsquery returns an empty tsquery for a stopword ("and")
       -- or pure punctuation ("!!"), and without this branch a user typing
       -- either gets an empty list and concludes their links have vanished.
       OR websearch_to_tsquery('english', $3::text) = ''::tsquery
       OR l.search_vector @@ websearch_to_tsquery('english', $3::text)
       OR l.alias ILIKE '%' || $3::text || '%'
       OR l.primary_url ILIKE '%' || $3::text || '%')
  AND ($4::uuid[] IS NULL
       OR EXISTS (SELECT 1 FROM link_tags lt
                   WHERE lt.link_id = l.id
                     AND lt.tag_id = ANY($4::uuid[])))
  AND (
        $5::timestamptz IS NULL
        OR ($6::text = 'oldest'
              AND (l.created_at, l.id) > ($5::timestamptz, $7::uuid))
        OR ($6::text <> 'oldest'
              AND (l.created_at, l.id) < ($5::timestamptz, $7::uuid))
      )
ORDER BY
    CASE WHEN $6::text = 'oldest' THEN l.created_at END ASC,
    CASE WHEN $6::text = 'clicks' THEN l.click_count END DESC,
    CASE WHEN $6::text NOT IN ('oldest','clicks') THEN l.created_at END DESC,
    l.id DESC
LIMIT $8
`

type ListLinksParams struct {
	WorkspaceID   uuid.UUID
	Status        *string
	Search        *string
	TagIds        []uuid.UUID
	CursorCreated *time.Time
	Sort          string
	CursorID      *uuid.UUID
	PageLimit     int32
}

type ListLinksRow struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	DomainID             uuid.UUID
	FolderID             *uuid.UUID
	Alias                string
	PrimaryUrl           string
	PrimaryDestinationID *uuid.UUID
	Title                string
	Description          string
	Status               string
	ExpiresAt            *time.Time
	PasswordHash         *string
	MaxClicks            *int64
	OneTime              bool
	ForwardQuery         bool
	ClickCount           int64
	LastClickAt          *time.Time
	CreatedBy            *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ArchivedAt           *time.Time
	DeletedAt            *time.Time
	PurgeAfter           *time.Time
	SearchVector         interface{}
	CampaignID           *uuid.UUID
	TagNames             []string
	TagIds               []string
}

// Keyset pagination over (created_at, id).
//
// The cursor is a composite so ordering is total: created_at alone is not
// unique, and a tie at the page boundary would drop or duplicate rows.
// Comparing the pair with row-value syntax lets the composite index serve it
// directly.
//
// Sorting is a CASE rather than three separate queries because sqlc has no
// dynamic SQL. If plan stability becomes a problem this splits into
// ListLinksNewest/Oldest/Clicks; measure before doing that.
func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]ListLinksRow, error) {
	rows, err := q.db.Query(ctx, listLinks,
		arg.WorkspaceID,
		arg.Status,
		arg.Search,
		arg.TagIds,
		arg.CursorCreated,
		arg.Sort,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksRow{}
	for rows.Next() {
		var i ListLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DomainID,
			&i.FolderID,
			&i.Alias,
			&i.PrimaryUrl,
			&i.PrimaryDestinationID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ExpiresAt,
			&i.PasswordHash,
			&i.MaxClicks,
			&i.OneTime,
			&i.ForwardQuery,
			&i.ClickCount,
			&i.LastClickAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.PurgeAfter,
			&i.SearchVector,
			&i.CampaignID,
			&i.TagNames,
			&i.TagIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.workspace_id, t.name, t.color, t.created_at, count(lt.link_id) AS link_count
FROM tags t
LEFT JOIN link_tags lt ON lt.tag_id = t.id
LEFT JOIN links l ON l.id = lt.link_id AND l.deleted_at IS NULL
WHERE t.workspace_id = $1
GROUP BY t.id
ORDER BY t.name
`

type ListTagsRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Color       string
	CreatedAt   time.Time
	LinkCount   int64
}

func (q *Queries) ListTags(ctx context.Context, workspaceID uuid.UUID) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveAlias = `-- name: ReserveAlias :exec
INSERT INTO reserved_aliases (domain_id, alias, reason)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ReserveAliasParams struct {
	DomainID uuid.UUID
	Alias    string
	Reason   string
}

// Called before purging a link that has clicks. The alias is in the wild — on
// printed material and in other people's bookmarks — so handing it to a new
// destination would be a redirect hijack.
func (q *Queries) ReserveAlias(ctx context.Context, arg ReserveAliasParams) error {
	_, err := q.db.Exec(ctx, reserveAlias, arg.DomainID, arg.Alias, arg.Reason)
	return err
}

const restoreLink = `-- name: RestoreLink :one
UPDATE links
   SET status = 'active', archived_at = NULL, updated_at = now()
 WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id
`

type RestoreLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) RestoreLink(ctx context.Context, arg RestoreLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, restoreLink, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
	)
	return i, err
}

const setPrimaryDestination = `-- name: SetPrimaryDestination :exec
UPDATE links SET primary_destination_id = $2, updated_at = now() WHERE id = $1
`

type SetPrimaryDestinationParams struct {
	ID                   uuid.UUID
	PrimaryDestinationID *uuid.UUID
}

func (q *Queries) SetPrimaryDestination(ctx context.Context, arg SetPrimaryDestinationParams) error {
	_, err := q.db.Exec(ctx, setPrimaryDestination, arg.ID, arg.PrimaryDestinationID)
	return err
}

const softDeleteLink = `-- name: SoftDeleteLink :one
UPDATE links
   SET deleted_at = now(),
       purge_after = now() + make_interval(days => $1::int),
       updated_at = now()
 WHERE id = $2 AND workspace_id = $3 AND deleted_at IS NULL
RETURNING id, alias, domain_id, click_count
`

type SoftDeleteLinkParams struct {
	RetentionDays int32
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
}

type SoftDeleteLinkRow struct {
	ID         uuid.UUID
	Alias      string
	DomainID   uuid.UUID
	ClickCount int64
}

// Soft delete with a purge deadline rather than an immediate DELETE. Restoring
// a link someone deleted by accident is a common request, and the alias stays
// reserved while the row exists.
func (q *Queries) SoftDeleteLink(ctx context.Context, arg SoftDeleteLinkParams) (SoftDeleteLinkRow, error) {
	row := q.db.QueryRow(ctx, softDeleteLink, arg.RetentionDays, arg.ID, arg.WorkspaceID)
	var i SoftDeleteLinkRow
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.DomainID,
		&i.ClickCount,
	)
	return i, err
}

const updateDestinationURL = `-- name: UpdateDestinationURL :exec
UPDATE destinations
   SET url = $3, url_host = $4, updated_at = now()
 WHERE link_id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type UpdateDestinationURLParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
	Url         string
	UrlHost     string
}

// The trigger on destinations mirrors this into links.primary_url, so the hot
// path never joins.
func (q *Queries) UpdateDestinationURL(ctx context.Context, arg UpdateDestinationURLParams) error {
	_, err := q.db.Exec(ctx, updateDestinationURL,
		arg.LinkID,
		arg.WorkspaceID,
		arg.Url,
		arg.UrlHost,
	)
	return err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
   SET title       = COALESCE($1, title),
       description = COALESCE($2, description),
       expires_at  = CASE WHEN $3::boolean THEN NULL
                          ELSE COALESCE($4, expires_at) END,
       alias       = COALESCE($5, alias),
       updated_at  = now()
 WHERE id = $6 AND workspace_id = $7 AND deleted_at IS NULL
RETURNING id, workspace_id, domain_id, folder_id, alias, primary_url, primary_destination_id, title, description, status, expires_at, password_hash, max_clicks, one_time, forward_query, click_count, last_click_at, created_by, created_at, updated_at, archived_at, deleted_at, purge_after, search_vector, campaign_id
`

type UpdateLinkParams struct {
	Title       *string
	Description *string
	ClearExpiry bool
	ExpiresAt   *time.Time
	Alias       *string
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// COALESCE with sqlc.narg gives partial update: a NULL argument leaves the
// column alone, so PATCH semantics need no dynamic SQL.
func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.Title,
		arg.Description,
		arg.ClearExpiry,
		arg.ExpiresAt,
		arg.Alias,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.FolderID,
		&i.Alias,
		&i.PrimaryUrl,
		&i.PrimaryDestinationID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.OneTime,
		&i.ForwardQuery,
		&i.ClickCount,
		&i.LastClickAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.PurgeAfter,
		&i.SearchVector,
		&i.CampaignID,
	)
	return i, err
}
