// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecentNotificationsOfKind = `-- name: CountRecentNotificationsOfKind :one
SELECT count(*) FROM notifications
 WHERE user_id = $1
   AND kind = $2
   AND created_at > $3
`

type CountRecentNotificationsOfKindParams struct {
	UserID uuid.UUID
	Kind   string
	Since  time.Time
}

// The re-notify guard. A threshold that is still crossed is still crossed on
// the next run an hour later, and a notification per hour forever is how an
// inbox becomes something people stop reading — which would cost exactly the
// warning D5 depends on.
func (q *Queries) CountRecentNotificationsOfKind(ctx context.Context, arg CountRecentNotificationsOfKindParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentNotificationsOfKind, arg.UserID, arg.Kind, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications
 WHERE user_id = $1 AND read_at IS NULL
   AND (workspace_id IS NULL OR workspace_id = $2)
`

type CountUnreadNotificationsParams struct {
	UserID      uuid.UUID
	WorkspaceID *uuid.UUID
}

// Served by notifications_user_unread_idx, the partial index the table already
// ships with: the WHERE clause here has to match the index's predicate exactly
// or this becomes a sequential scan on every page render in the dashboard.
//
// **Both halves of the workspace predicate are load-bearing** (D102, F105).
// `workspace_id = @workspace_id` alone hides every organization-level
// notification, because disputes and audit-growth write NULL — the reader would
// lose exactly the notifications that are not about any one workspace. And the
// clause has to be identical here and in ListUnreadNotificationPreview below, or
// the badge and the list it previews disagree while one of them stops using the
// index.
func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.UserID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, workspace_id, kind, title, body, data, read_at, created_at
  FROM notifications
 WHERE id = $1 AND user_id = $2
`

type GetNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// One row of the actor's own inbox, scoped by user_id like every statement
// around it: somebody else's notification is "no rows" rather than a 403 that
// confirms the id exists.
//
// Read by the click-through (M48). Where a notification leads is computed from
// its `kind` and its `data`, and both have to come off the row — a destination
// carried on the request would be a redirect target the caller chose.
func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :exec

INSERT INTO notifications (id, user_id, workspace_id, kind, title, body, data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNotificationParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WorkspaceID *uuid.UUID
	Kind        string
	Title       string
	Body        string
	Data        []byte
}

// Notifications. The table shipped dormant in 00600; nothing here adds a
// column, per the rule that a dormant table's structure goes in its jsonb until
// the feature that needs a column arrives. `data` carries whatever a kind needs.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, workspace_id, kind, title, body, data, read_at, created_at
  FROM notifications
 WHERE user_id = $1
   AND (workspace_id IS NULL OR workspace_id = $2)
   AND (NOT $3::boolean OR read_at IS NULL)
   AND (
        $4::timestamptz IS NULL
     OR (created_at, id) < ($4::timestamptz, $5::uuid)
   )
 ORDER BY created_at DESC, id DESC
 LIMIT $6
`

type ListNotificationsParams struct {
	UserID        uuid.UUID
	WorkspaceID   *uuid.UUID
	UnreadOnly    bool
	CursorCreated *time.Time
	CursorID      *uuid.UUID
	PageLimit     int32
}

// Newest first, keyset on (created_at, id). Same shape as the audit log and the
// link list: an offset shifts under a notification arriving mid-page, and a new
// notification arriving is the normal case here rather than the rare one.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.WorkspaceID,
		arg.UnreadOnly,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationIDs = `-- name: ListOrganizationIDs :many
SELECT id FROM organizations WHERE deleted_at IS NULL ORDER BY id
`

// Every organization on the instance. Phase 1 has exactly one; this is written
// as a list because M28 makes that untrue and a job that notified only the
// first organization would then be silently wrong for every other.
func (q *Queries) ListOrganizationIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOrganizationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationPreview = `-- name: ListUnreadNotificationPreview :many
SELECT id, user_id, workspace_id, kind, title, body, data, read_at, created_at,
       count(*) OVER () AS unread_total
  FROM notifications
 WHERE user_id = $1 AND read_at IS NULL
   AND (workspace_id IS NULL OR workspace_id = $2)
 ORDER BY created_at DESC, id DESC
 LIMIT $3
`

type ListUnreadNotificationPreviewParams struct {
	UserID      uuid.UUID
	WorkspaceID *uuid.UUID
	PageLimit   int32
}

type ListUnreadNotificationPreviewRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WorkspaceID *uuid.UUID
	Kind        string
	Title       string
	Body        string
	Data        []byte
	ReadAt      *time.Time
	CreatedAt   time.Time
	UnreadTotal int64
}

// The whole of the header's notification lookup: the newest unread rows the bell
// previews, and the unread total the badge shows, in one round trip.
//
// Two shapes already in this file, composed rather than a third one. The
// predicate is CountUnreadNotifications' predicate character for character, so
// notifications_user_unread_idx still serves it; the ordering is
// ListNotifications' ordering, so the preview is the same "newest first" the
// page shows.
//
// `count(*) OVER ()` is what makes it one query instead of two. Window functions
// are evaluated before LIMIT, so the count is every unread row rather than the
// handful returned — which is the only reason the badge can keep being exact
// while the preview stays bounded. A page render costs one notification query
// here, as it did when it cost a bare count.
func (q *Queries) ListUnreadNotificationPreview(ctx context.Context, arg ListUnreadNotificationPreviewParams) ([]ListUnreadNotificationPreviewRow, error) {
	rows, err := q.db.Query(ctx, listUnreadNotificationPreview, arg.UserID, arg.WorkspaceID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadNotificationPreviewRow{}
	for rows.Next() {
		var i ListUnreadNotificationPreviewRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UnreadTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRoleInOrg = `-- name: ListUsersWithRoleInOrg :many
SELECT DISTINCT u.id, u.email, u.name
  FROM memberships m
  JOIN roles r ON r.id = m.role_id
  JOIN users u ON u.id = m.user_id
 WHERE m.organization_id = $1
   AND (m.workspace_id IS NULL OR m.workspace_id = $2)
   AND r.slug = $3
   AND r.organization_id IS NULL
   AND u.status = 'active'
 ORDER BY u.id
`

type ListUsersWithRoleInOrgParams struct {
	OrganizationID uuid.UUID
	WorkspaceID    *uuid.UUID
	RoleSlug       string
}

type ListUsersWithRoleInOrgRow struct {
	ID    uuid.UUID
	Email string
	Name  string
}

// Who to tell about something that concerns the organization rather than a
// person. Active users only: a deactivated account cannot sign in to read it.
//
// **Scoped, because a membership is** (D44). The sentence LockOrganizationOwners
// states in members.sql applies here word for word: a workspace-scoped owner
// membership grants ownership of one workspace, not of the organization. So the
// recipients are the organization-wide rows, plus — when the news belongs to a
// workspace — the rows scoped to *that* workspace, because news about their
// workspace is theirs to hear.
//
// Two arms rather than one predicate, and that is the whole correction. Adding
// `m.workspace_id IS NULL` alone is the smaller diff and the wrong recipient
// set: it silences a workspace-scoped owner about their own workspace, which is
// exactly what a caller passing a workspace id means to tell them about. A NULL
// @workspace_id is news that belongs to no workspace, and the second arm
// matches nothing then, which is what the organization-wide callers want.
//
// r.organization_id IS NULL for the reason LockOrganizationOwners carries it:
// 'owner' names a built-in role, and a tenant's custom role of the same slug is
// a different role.
//
// DISTINCT because the arms overlap. One person may hold both an
// organization-wide owner membership and an owner membership scoped to this
// workspace — that pair is precisely how the defect was reachable — and a
// recipient list naming them twice would write two inbox rows and send two
// mails.
//
// The address comes back with the id because both deliveries address the same
// person: the inbox row is keyed by user, the mail by address, and looking the
// second one up separately would mean a query per recipient.
func (q *Queries) ListUsersWithRoleInOrg(ctx context.Context, arg ListUsersWithRoleInOrgParams) ([]ListUsersWithRoleInOrgRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRoleInOrg, arg.OrganizationID, arg.WorkspaceID, arg.RoleSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithRoleInOrgRow{}
	for rows.Next() {
		var i ListUsersWithRoleInOrgRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
   SET read_at = now()
 WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
   SET read_at = now()
 WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Scoped by user_id as well as id, so someone else's notification is a
// zero-row update rather than a 403 that confirms the id exists.
//
// read_at is only set once. Marking an already-read notification is a no-op
// rather than a fresh timestamp, so "when did you first see this" survives a
// double click.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationUnread = `-- name: MarkNotificationUnread :execrows
UPDATE notifications
   SET read_at = NULL
 WHERE id = $1 AND user_id = $2 AND read_at IS NOT NULL
`

type MarkNotificationUnreadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// `read_at` back to NULL, which is the whole of "unread": 00600 declared the
// column nullable and the inbox has always used NULL for it, so putting one
// back is an UPDATE and never a migration (M48).
//
// **Deliberately not the mirror image of MarkNotificationRead.** That statement
// refuses to touch an already-read row so that "when did you first see this"
// survives a double click. This one carries no such guard: it exists because the
// click-through M48 adds marks a notification read as a side effect of opening
// it, and somebody undoing that is saying they have not dealt with it — which is
// as true of a row read last week as of one read by accident a second ago. The
// first-seen timestamp is what is being discarded, on purpose, by the person it
// belongs to.
func (q *Queries) MarkNotificationUnread(ctx context.Context, arg MarkNotificationUnreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationUnread, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
