// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countOrganizationLinks = `-- name: CountOrganizationLinks :one
SELECT count(*) FROM links l
JOIN workspaces w ON w.id = l.workspace_id
WHERE w.organization_id = $1
  AND w.deleted_at IS NULL
  AND l.deleted_at IS NULL
`

// What D37 refuses an organization deletion on, and it is deliberately the same
// shape as CountWorkspaceLinks one level up.
//
// Archived links count, soft-deleted ones do not — the reasoning is D32's and is
// written out there. What is new here is *why the org level asks the question at
// all*: cascading through these links would make D32 bypassable by deleting one
// level up, which turns a rule into a speed bump. So the organization refuses on
// exactly the rows its workspaces would refuse on.
func (q *Queries) CountOrganizationLinks(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationLinks, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMemberships = `-- name: CountUserMemberships :one
SELECT count(*) FROM memberships WHERE user_id = $1
`

// Whether an account belongs to anything at all.
//
// Read by exactly one caller: the first-organization path (D36). An account with
// no membership holds no role and therefore no `orgs.create`, so without this
// the prompt to create an organization would lead somewhere it is refused. This
// is a check on **present state** — how many memberships exist right now — and
// not on how the account was made, which is the distinction D16 was drawing when
// it made the permission a grant rather than a provenance test.
func (q *Queries) CountUserMemberships(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMemberships, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOrganization = `-- name: DeleteOrganization :execrows
DELETE FROM organizations
 WHERE id = $1 AND deleted_at IS NULL
`

// A real delete, not a soft one, and everything in 00200/00300/00500/01200 that
// references it cascades: workspaces and everything under them, memberships,
// invitations, API keys, and any custom domain.
//
// Two things deliberately do not. `audit_logs.organization_id` carries no
// foreign key, so the trail this organization wrote survives the row it
// describes — a tenancy teardown that erased its own record is the one shape an
// audit log must not have. And the instance default domain has
// `organization_id IS NULL`, so it and the `reserved_aliases` rows keyed to it
// are untouched.
func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrganization, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrganizationRollups = `-- name: DeleteOrganizationRollups :execrows
WITH gone AS (
    DELETE FROM link_click_daily
     WHERE workspace_id IN (SELECT w.id FROM workspaces w WHERE w.organization_id = $1)
    RETURNING 1
), gone_dims AS (
    DELETE FROM link_dimension_daily
     WHERE workspace_id IN (SELECT w.id FROM workspaces w WHERE w.organization_id = $1)
    RETURNING 1
), gone_ws AS (
    DELETE FROM workspace_click_daily
     WHERE workspace_id IN (SELECT w.id FROM workspaces w WHERE w.organization_id = $1)
    RETURNING 1
)
SELECT 1 FROM gone
UNION ALL SELECT 1 FROM gone_dims
UNION ALL SELECT 1 FROM gone_ws
`

// The three analytics rollups belonging to an organization's workspaces.
//
// They carry `workspace_id` with no foreign key — a deliberate choice recorded
// at 00400, so a rollup job never blocks on a tenancy write and a partition drop
// never has to consider them — and the cost of that choice is that nothing
// cascades them. `link_click_daily`, `link_dimension_daily` and
// `workspace_click_daily` therefore outlived the tenancy they describe, while
// DeleteOrganization's own doc said the audit trail was all that survived (F106).
//
// Run *before* the organization is deleted, and that ordering is required rather
// than tidy: the workspaces are what name these rows, and the cascade takes the
// workspaces. After the delete there is nothing left to select them by.
//
// Not a security fix. Every reader scopes to a live workspace_id, so these rows
// are unreachable rather than exposed; what they are is stale aggregate data
// with no owner, and a sentence that was not true.
func (q *Queries) DeleteOrganizationRollups(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrganizationRollups, organizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, data_region, is_personal, created_at, updated_at, deleted_at FROM organizations
WHERE id = $1 AND deleted_at IS NULL
`

// The organization being deleted, read after LockOrganizations has locked it.
//
// Its name and slug are read here because the audit record has to carry them:
// once the row is gone that record is the only remaining trace of what was
// deleted, exactly as it is for a workspace.
func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DataRegion,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockOrganizationWorkspaces = `-- name: LockOrganizationWorkspaces :many
SELECT id FROM workspaces
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY id
FOR UPDATE
`

// The organization's workspaces, locked, so no link can be created in one while
// the link guard below is counting.
//
// Ordered for the same deadlock reason as LockOrganizations.
func (q *Queries) LockOrganizationWorkspaces(ctx context.Context, organizationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockOrganizationWorkspaces, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganizations = `-- name: LockOrganizations :many

SELECT id FROM organizations
WHERE deleted_at IS NULL
ORDER BY id
FOR UPDATE
`

// Organization teardown (M28.5).
//
// Every statement here is either a guard or the delete it guards. The delete is
// one line; the guards are the milestone.
//
// **Locking, and why each of these returns rows rather than a count.** A count
// cannot be locked, so a guard written as `SELECT count(*)` is a check-then-act:
// two administrators acting at once each read a state the other is changing.
// The pattern is `LockOrganizationOwners`' — select the rows the decision is
// made on `FOR UPDATE`, count them in Go, and let the second transaction block
// until the first commits and then re-read what it left behind. Postgres also
// gives this a second effect that is the point of it here: inserting a row that
// references a locked parent takes `FOR KEY SHARE` on that parent, which
// conflicts with `FOR UPDATE` — so a locked organization cannot acquire a new
// workspace, and a locked workspace cannot acquire a new link, while the guard
// is deciding.
// Every live organization on the instance, locked, for the refusal that stops
// the last one being deleted.
//
// Instance-wide rather than scoped, because that is what the rule is about: an
// instance with no organization has no path back that does not involve SQL, the
// same argument that refuses the last owner and the last workspace.
//
// `ORDER BY id` is load-bearing rather than cosmetic. Two concurrent deletions
// of different organizations both take this lock, and taking a set of row locks
// in a different order in each transaction is a deadlock; a fixed order makes it
// a wait instead. It is also why this runs *before* the target row is read —
// the target is inside this set, so it is already locked by the time anything
// else touches it.
func (q *Queries) LockOrganizations(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveOrganizationTraffickedAliases = `-- name: ReserveOrganizationTraffickedAliases :exec
WITH doomed AS (
    SELECT l.domain_id, l.alias
      FROM links l
      JOIN workspaces w ON w.id = l.workspace_id
     WHERE w.organization_id = $1
       AND l.click_count > 0
     ORDER BY l.id
       FOR UPDATE OF l
)
INSERT INTO reserved_aliases (domain_id, alias, reason)
SELECT domain_id, alias, 'organization deleted with traffic'
  FROM doomed
ON CONFLICT DO NOTHING
`

// The organization-level half of the same reservation, and it exists for the
// same reason the link guard exists one level up: an organization-level cascade
// that behaved differently from a workspace-level one would make the rule
// bypassable by deleting one level up.
//
// The rationale is written out in full beside
// ReserveWorkspaceTraffickedAliases; only the reach differs. Note what is
// deliberately *not* filtered here: workspaces are joined without
// `deleted_at IS NULL`, unlike CountOrganizationLinks, because this statement
// follows what the cascade takes rather than what the guard counted, and the
// cascade takes every workspace of the organization.
func (q *Queries) ReserveOrganizationTraffickedAliases(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, reserveOrganizationTraffickedAliases, organizationID)
	return err
}
