// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveLink(ctx context.Context, arg ArchiveLinkParams) (Link, error)
	AttachTag(ctx context.Context, arg AttachTagParams) error
	//
	// One batch of due mail, claimed rather than merely selected.
	//
	// The UPDATE is what makes the claim: it spends the attempt and leases the row
	// forward, in one statement, before anything is sent. Two consequences, and
	// both are the point:
	//
	//   * A process killed between claiming and sending leaves a row that comes
	//     back on its own when the lease expires, instead of one stuck pending.
	//   * A crash loop is bounded. Counting the attempt at send time would let a
	//     process that dies mid-send retry the same message forever.
	//
	// FOR UPDATE SKIP LOCKED inside the subquery keeps two drainers from claiming
	// the same row. Leadership already keeps a second replica out of this job, but
	// leadership is an advisory lock released when its holder dies, so a moment of
	// overlap is possible; skip-locked makes that moment cost nothing rather than
	// send a message twice.
	//
	// Ordered oldest first, so a backlog drains in the order it was queued.
	ClaimDueMail(ctx context.Context, arg ClaimDueMailParams) ([]ClaimDueMailRow, error)
	CountClickEvents(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// Only issued when the caller explicitly asks for a total, because counting
	// costs a scan the common page load should not pay for.
	CountLinks(ctx context.Context, arg CountLinksParams) (int64, error)
	// Whether the person at this address is already in this organization.
	//
	// Asked at creation, where the actor holds members.write on the organization
	// and could read its member list anyway, so answering it discloses nothing they
	// could not already see. Redemption asks the same question of a user id it has
	// already resolved, and answers it with the same generic refusal as every other
	// failure.
	CountMembershipsForEmail(ctx context.Context, arg CountMembershipsForEmailParams) (int64, error)
	CountMembershipsForUser(ctx context.Context, arg CountMembershipsForUserParams) (int64, error)
	// Whether this is the organization's last workspace.
	//
	// Deleting it would leave every member of the organization resolving into no
	// workspace at all, which `ResolveWorkspaceForUser` reports as a broken instance
	// rather than as an empty state — so the account could not authenticate. Guarded
	// for the same reason the last owner is.
	CountOrganizationWorkspaces(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountPendingMail(ctx context.Context) (int64, error)
	//
	// The re-notify guard. A threshold that is still crossed is still crossed on
	// the next run an hour later, and a notification per hour forever is how an
	// inbox becomes something people stop reading — which would cost exactly the
	// warning D5 depends on.
	CountRecentNotificationsOfKind(ctx context.Context, arg CountRecentNotificationsOfKindParams) (int64, error)
	//
	// Served by notifications_user_unread_idx, the partial index the table already
	// ships with: the WHERE clause here has to match the index's predicate exactly
	// or this becomes a sequential scan on every page render in the dashboard.
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	// Users, sessions and tenancy provisioning.
	// Drives the first-run setup flow: /setup exists only while this is zero.
	CountUsers(ctx context.Context) (int64, error)
	// What D32 refuses a workspace deletion on.
	//
	// Soft-deleted links are excluded on purpose. `links`, `tags` and `folders` all
	// cascade from `workspaces`, so the guard is in front of a real cascade — but a
	// link the owner already deleted is one they cannot delete again, and counting
	// it would leave the workspace undeletable until the purge job ran, with nothing
	// the person could do about it. Archived links **are** counted: an archived link
	// keeps its alias and its click history, so cascading it away would be silent
	// data loss dressed as tidying up.
	CountWorkspaceLinks(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// API keys and the permission vocabulary their scopes are drawn from.
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error)
	// Invitations: issuing, listing, revoking and redeeming (M27).
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	// Links, destinations and tags.
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// ON CONFLICT DO NOTHING returns no row when another replica inserted first,
	// which the caller detects and re-reads. Two replicas using different salts
	// for the same day would split every visitor in two.
	CreateSalt(ctx context.Context, arg CreateSaltParams) ([]byte, error)
	// workspace_id is written at sign-in rather than left for the first switch, so
	// a session says where it is from its first row. Resolution would answer the
	// same either way — a NULL simply falls through to the user's preference — but
	// a switcher that only takes effect after the first switch is a switcher whose
	// state is unreadable until somebody uses it.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// --- tags -------------------------------------------------------------------
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	// Reaper. Revoked rows are kept briefly so "sign out everywhere" is visible in
	// the session list before it disappears.
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error)
	// Reaper. Kept long enough to be visible in the key list after revocation, and
	// long enough for the audit question above to be answerable.
	DeleteRevokedAPIKeys(ctx context.Context) (int64, error)
	DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error)
	// A real delete, not a soft one, and that is the decision D32 guards.
	//
	// `links`, `tags` and `folders` cascade from here (00300_links.sql). Soft
	// deleting instead would leave those rows behind and their aliases still
	// serving redirects out of a workspace the dashboard says is gone, which is a
	// worse outcome than the cascade — so the guard goes in front of the delete and
	// the delete is honest about what it does.
	DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) (int64, error)
	DetachAllTags(ctx context.Context, linkID uuid.UUID) error
	// The mail outbox. Queued on the request path, drained by the scheduler.
	//
	// The message is stored rendered. Nothing here re-renders from a template, so a
	// later template change cannot rewrite a mail somebody is already waiting for.
	EnqueueMail(ctx context.Context, arg EnqueueMailParams) error
	// The verification lookup, on the unique prefix index, joined with the user so
	// authentication is one round trip. Revoked and expired keys are returned
	// rather than filtered out: the caller distinguishes them so the response can
	// say which it was, and a deleted user's key resolves to no row at all.
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error)
	GetBuiltinRoleBySlug(ctx context.Context, slug string) (GetBuiltinRoleBySlugRow, error)
	// The instance's link domain and where its root points. Phase 1 has exactly one
	// default domain; Phase 2 gives a workspace its own and this gains a filter.
	GetDefaultDomainSettings(ctx context.Context) (GetDefaultDomainSettingsRow, error)
	// Redemption's only lookup, and the row it locks.
	//
	// FOR UPDATE OF i serializes two redemptions of the same token: the second
	// blocks until the first commits and then reads redeemed_at set, so single-use
	// is enforced by the database rather than by a check-then-act in Go. The joined
	// tables are not locked — they are read for their labels, and locking a role
	// row would block every other invite that names it.
	//
	// Expiry and revocation are deliberately NOT in the WHERE clause. The caller
	// has to tell "no such token" from "expired" apart to decide what to log, and
	// it answers all of them identically to the person redeeming (decision D27).
	GetInvitationByTokenHash(ctx context.Context, tokenHash []byte) (GetInvitationByTokenHashRow, error)
	// --- job bookkeeping ---------------------------------------------------------
	// The point a job is known to have completed through. Rollups recompute rather
	// than accumulate, so this is not a correctness dependency for a run that
	// happens on schedule — it exists for the run that does not. Without it,
	// RunRecent covered a fixed yesterday-and-today window, and any downtime that
	// spanned a UTC day left that day with no rollup and nothing to notice it: the
	// raw events were still there, but nothing ever aggregated them again.
	GetJobWatermark(ctx context.Context, job string) (*time.Time, error)
	// Workspace-scoped by design. Passing the workspace here rather than checking
	// it after the fetch makes cross-tenant reads impossible to write by accident:
	// the wrong workspace returns no rows rather than a row the caller must
	// remember to reject.
	GetLink(ctx context.Context, arg GetLinkParams) (Link, error)
	GetLinkByAlias(ctx context.Context, arg GetLinkByAliasParams) (Link, error)
	GetLinkDimensions(ctx context.Context, arg GetLinkDimensionsParams) ([]GetLinkDimensionsRow, error)
	// Reads the rollup, never the raw events. This is what keeps analytics under
	// the 2s target as click_events grows into the tens of millions.
	GetLinkStats(ctx context.Context, arg GetLinkStatsParams) ([]GetLinkStatsRow, error)
	GetLinkTags(ctx context.Context, linkID uuid.UUID) ([]GetLinkTagsRow, error)
	// One membership, scoped by organization so an id from elsewhere is
	// indistinguishable from one that never existed.
	//
	// FOR UPDATE OF m: every caller is about to re-role or delete this row, and the
	// rank check that decides whether they may is read from it. Without the lock,
	// two administrators acting at once could each read a state the other is
	// changing — the check-then-act that the last-owner refusal exists to prevent.
	GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error)
	// Whether a user is in an organization at all, for the grant path:
	// workspace-scoped access is given to somebody who is already a member, and
	// this is what establishes that.
	//
	// **Any** membership counts, organization-wide or workspace-scoped. Requiring
	// an organization-wide one would be a dead end: somebody left holding only a
	// workspace-scoped membership could never be given a second workspace, because
	// re-inviting them is refused as already-a-member. Under D31 every grant adds,
	// so widening a scoped member to a second workspace is the same kind of act as
	// the first grant was.
	//
	// The organization-wide row wins the tiebreak so the label and role this
	// returns are the person's broadest, which is what a control naming them should
	// show.
	GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (GetOrganizationMemberRow, error)
	// What to call the organization in an invitation. A primary-key lookup on a
	// path that is already writing a row, rather than carrying a name on every
	// identity for the one surface that needs it.
	GetOrganizationName(ctx context.Context, id uuid.UUID) (string, error)
	// The live-activity feed. Bounded and index-backed on (link_id, occurred_at).
	GetRecentClicks(ctx context.Context, arg GetRecentClicksParams) ([]GetRecentClicksRow, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	// Analytics: salts, rollups and reads.
	GetSalt(ctx context.Context, validOn time.Time) ([]byte, error)
	// Joined with the user so validating a session is one round trip on a path
	// that runs for every authenticated request. Filters revoked and deleted here
	// rather than in Go, so a revoked session cannot be resurrected by a caller
	// that forgets to check.
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	// Comparison is on the generated email_lower column, so callers cannot
	// accidentally do a case-sensitive lookup and create a duplicate account.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// The RBAC evaluator's source of truth. Returns every permission a user holds
	// in a workspace, via their organization membership and its role.
	//
	// A NULL memberships.workspace_id means the membership covers every workspace
	// in the organization, which is what Phase 1 always creates.
	GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]string, error)
	GetUserRoleInWorkspace(ctx context.Context, arg GetUserRoleInWorkspaceParams) (GetUserRoleInWorkspaceRow, error)
	GetWorkspaceDefaultDomain(ctx context.Context) (GetWorkspaceDefaultDomainRow, error)
	// One workspace, scoped by organization so an id belonging to another tenant is
	// indistinguishable from one that does not exist.
	//
	// FOR UPDATE: both callers — rename and delete — are about to write this row or
	// the rows that cascade from it, and delete reads a link count that must not
	// change underneath the decision.
	GetWorkspaceInOrganization(ctx context.Context, arg GetWorkspaceInOrganizationParams) (Workspace, error)
	GetWorkspaceStats(ctx context.Context, arg GetWorkspaceStatsParams) ([]GetWorkspaceStatsRow, error)
	// Summing daily uniques over-counts anyone visiting on more than one day.
	// Reported as "unique visitors per day, summed" in the UI rather than
	// presented as a distinct-person count, because the exact figure cannot be
	// recovered once the salts are purged. That is the intended trade.
	GetWorkspaceTotals(ctx context.Context, arg GetWorkspaceTotalsParams) (GetWorkspaceTotalsRow, error)
	// Audit log. Append-only: there is no update and no delete here, and that is the
	// point of the table. Rows leave only when retention drops a whole partition.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// Notifications. The table shipped dormant in 00600; nothing here adds a
	// column, per the rule that a dormant table's structure goes in its jsonb until
	// the feature that needs a column arrives. `data` carries whatever a kind needs.
	InsertNotification(ctx context.Context, arg InsertNotificationParams) error
	// Consulted by BOTH create paths — generated aliases before insert, and
	// user-supplied aliases as validation — and by alias changes.
	//
	// No deleted_at filter on the links branch, deliberately: a soft-deleted row
	// holds its alias for the whole trash window, so a link deleted by accident can
	// be restored under its own name. The partial unique index cannot enforce that
	// (it ignores trashed rows), so this check is the enforcement and the index
	// remains the guarantee against live-row races only.
	IsAliasTaken(ctx context.Context, arg IsAliasTakenParams) (bool, error)
	// Revoked keys are included. "Which keys existed and when were they revoked"
	// is the question asked after an incident, so they are listed until the reaper
	// removes them.
	ListAPIKeysForUser(ctx context.Context, arg ListAPIKeysForUserParams) ([]ListAPIKeysForUserRow, error)
	//
	// Newest first, keyed on (occurred_at, id) so the cursor is a position rather
	// than an offset: an event written while a reader is paginating shifts every
	// offset by one, and a keyset cursor is unaffected by it.
	//
	// The row-comparison predicate is what makes that hold. Comparing the columns
	// separately -- occurred_at < c OR (occurred_at = c AND id < i) -- is the same
	// logic, and the planner does not always recognise it as a range scan on the
	// (organization_id, occurred_at DESC) index.
	//
	// Scoped by organization, never by workspace: an audit log that can be narrowed
	// to the workspace the reader happens to be in would hide exactly the actions
	// worth reviewing.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// The four seeded roles, most powerful first. Feeds the invite form's role
	// choices, filtered by the inviter's own rank in the service (decision D28).
	ListBuiltinRoles(ctx context.Context) ([]ListBuiltinRolesRow, error)
	// The administrator's list, newest first.
	//
	// No pagination and no cursor. An organization's outstanding invitations are a
	// handful of rows by construction, and redeemed ones stop accumulating the
	// moment people join; the link list's machinery here would be a page that
	// cannot fill.
	//
	// The inviter is joined as a label rather than an id, for the same reason the
	// audit log stores one: the row has to stay readable after that account is
	// gone, and the LEFT JOIN is what lets it.
	ListInvitations(ctx context.Context, organizationID uuid.UUID) ([]ListInvitationsRow, error)
	// Keyset pagination over (created_at, id).
	//
	// The cursor is a composite so ordering is total: created_at alone is not
	// unique, and a tie at the page boundary would drop or duplicate rows.
	// Comparing the pair with row-value syntax lets the composite index serve it
	// directly.
	//
	// Sorting is a CASE rather than three separate queries because sqlc has no
	// dynamic SQL. If plan stability becomes a problem this splits into
	// ListLinksNewest/Oldest/Clicks; measure before doing that.
	// The two tag aggregates are paired positionally by the caller, so they must
	// agree on their order — and on the table they read. Aggregating names from a
	// join and ids from link_tags alone, each sorted by its own column, produced
	// arrays in different orders whenever a link's tags sorted differently by name
	// than by id, and every tag came back carrying another tag's name. One
	// subquery, one ORDER BY, both columns.
	ListLinks(ctx context.Context, arg ListLinksParams) ([]ListLinksRow, error)
	// Membership management: who is in an organization, at what rank, and where
	// that rank reaches (M28).
	//
	// The rows these statements read and write are the ones 00200 has carried since
	// Phase 1. Nothing here is new schema; what is new is that a person can change
	// them, which is why every write is scoped by organization_id as well as by id.
	// Every membership in an organization, most powerful first.
	//
	// One row per membership, not per user. A user holding an organization-wide
	// membership and a workspace-scoped one appears twice, and that is the shape the
	// page has to show: under D31 the two rows *add*, and collapsing them into one
	// would hide the second grant behind the first.
	//
	// The workspace name is joined rather than looked up per row, and is NULL for an
	// organization-wide membership — which is what the absence of a workspace_id
	// means, and the distinction the list is read for.
	//
	// Not paginated. An organization's membership is a handful of rows by
	// construction, exactly as its invitations are.
	ListMembers(ctx context.Context, organizationID uuid.UUID) ([]ListMembersRow, error)
	//
	// Newest first, keyset on (created_at, id). Same shape as the audit log and the
	// link list: an offset shifts under a notification arriving mid-page, and a new
	// notification arriving is the normal case here rather than the rare one.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	//
	// Every organization on the instance. Phase 1 has exactly one; this is written
	// as a list because M28 makes that untrue and a job that notified only the
	// first organization would then be silently wrong for every other.
	ListOrganizationIDs(ctx context.Context) ([]uuid.UUID, error)
	// The scope vocabulary. Scopes are validated against the permissions table
	// rather than a list in Go, so RBAC and API keys cannot drift apart.
	ListPermissionSlugs(ctx context.Context) ([]string, error)
	// Counts l.id, not lt.link_id. The join onto links is what excludes trashed
	// links, but counting the link_tags column ignored it: a LEFT JOIN keeps the
	// link_tags row when its link is soft-deleted, so the count included trashed
	// links for the whole 30-day window and the tag list disagreed with the link
	// list it filters.
	ListTags(ctx context.Context, workspaceID uuid.UUID) ([]ListTagsRow, error)
	//
	// The whole of the header's notification lookup: the newest unread rows the bell
	// previews, and the unread total the badge shows, in one round trip.
	//
	// Two shapes already in this file, composed rather than a third one. The
	// predicate is CountUnreadNotifications' predicate character for character, so
	// notifications_user_unread_idx still serves it; the ordering is
	// ListNotifications' ordering, so the preview is the same "newest first" the
	// page shows.
	//
	// `count(*) OVER ()` is what makes it one query instead of two. Window functions
	// are evaluated before LIMIT, so the count is every unread row rather than the
	// handful returned — which is the only reason the badge can keep being exact
	// while the preview stays bounded. A page render costs one notification query
	// here, as it did when it cost a bare count.
	ListUnreadNotificationPreview(ctx context.Context, arg ListUnreadNotificationPreviewParams) ([]ListUnreadNotificationPreviewRow, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]ListUserSessionsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	//
	// Who to tell about something that concerns the organization rather than a
	// person. Active users only: a deactivated account cannot sign in to read it.
	//
	// The address comes back with the id because both deliveries address the same
	// person: the inbox row is keyed by user, the mail by address, and looking the
	// second one up separately would mean a query per recipient.
	ListUsersWithRoleInOrg(ctx context.Context, arg ListUsersWithRoleInOrgParams) ([]ListUsersWithRoleInOrgRow, error)
	// The workspace switcher: what a user may act in, and what they have chosen.
	//
	// Resolution itself is in auth.sql, because it is identity, not a feature.
	// These are the reads and writes the switcher and its account setting need.
	// Every workspace a user may act in, with the organization it belongs to.
	//
	// DISTINCT because a user can hold both an organization-wide membership and a
	// workspace-scoped one in the same organization, which the unique index
	// permits; without it the switcher would list a workspace twice.
	//
	// is_default is carried here rather than fetched separately so a page render
	// costs one query: the nav switcher needs the list, the account setting needs
	// the list plus which entry is pinned, and neither should cost two round trips.
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error)
	// Serializes the setup flow's count-then-create.
	//
	// Both setup surfaces read CountUsers and then, in a separate transaction,
	// register the first user. Nothing held the gap, and the gap is wide: the
	// argon2 hash runs for ~100ms before the transaction even begins. On a fresh
	// closed instance, setup is unauthenticated and only login-rate-limited, so an
	// attacker polling it could have their CountUsers land in the window while the
	// real operator was hashing, and both would be created as "the first user" —
	// each with their own organization, on an instance the operator believes only
	// they can reach.
	//
	// Transaction-scoped, so it releases on commit or rollback with nothing to
	// clean up. The key is the ASCII bytes "lcsetup\0" as a literal, NOT a hash of
	// anything; to inspect it from psql use the value directly:
	//
	//     SELECT pg_advisory_xact_lock(7810213058373316608);
	LockFirstUserSetup(ctx context.Context) error
	// The organization's owner memberships, locked.
	//
	// Organization-wide only: a workspace-scoped owner membership grants ownership
	// of one workspace, not of the organization, so counting it would let the last
	// real owner be removed while a workspace-scoped row stood in for them.
	//
	// Rows rather than a count, because a count cannot be locked. Taken before any
	// removal or demotion of an owner, so two concurrent administrators cannot each
	// observe two owners and each remove one.
	LockOrganizationOwners(ctx context.Context, organizationID uuid.UUID) ([]uuid.UUID, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error)
	// The single-use write. Conditional on the invite still being redeemable, so
	// even without the lock above this could not be spent twice.
	MarkInvitationRedeemed(ctx context.Context, arg MarkInvitationRedeemedParams) (int64, error)
	//
	// Retry exhausted. Terminal, and deliberately not deleted — a row that says
	// what was attempted and why it never arrived is the whole point of an outbox
	// over an in-memory retry loop.
	MarkMailFailed(ctx context.Context, arg MarkMailFailedParams) error
	//
	// A failure that will be tried again. The error is kept verbatim: it is what an
	// operator reads when somebody reports that mail never arrived.
	//
	// Replaces the lease ClaimDueMail set with the real backoff for this attempt,
	// and does not touch attempts — the claim already spent it.
	//
	// Seconds rather than an interval parameter, matching the lockout query in
	// auth.sql: an interval maps to pgtype.Interval, which would put a driver type
	// in the service layer's signature for no benefit.
	MarkMailRetry(ctx context.Context, arg MarkMailRetryParams) error
	//
	// attempts is not touched: ClaimDueMail already spent it.
	MarkMailSent(ctx context.Context, id uuid.UUID) error
	//
	// Scoped by user_id as well as id, so someone else's notification is a
	// zero-row update rather than a 403 that confirms the id exists.
	//
	// read_at is only set once. Marking an already-read notification is a no-op
	// rather than a fresh timestamp, so "when did you first see this" survives a
	// double click.
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	// The same lookup without the lock, for rendering the redemption page.
	//
	// A GET must not take a row lock: the page is served to anybody holding the
	// link, and a locking read there would let a stranger hold a write lock on the
	// row by opening a page.
	PeekInvitationByTokenHash(ctx context.Context, tokenHash []byte) (PeekInvitationByTokenHashRow, error)
	// The end of the trash window: hard-delete links whose purge_after has passed.
	//
	// One statement, so the reservation and the deletion cannot be separated by a
	// crash: an alias that ever received traffic is written to reserved_aliases in
	// the same command that removes its row, and ON CONFLICT makes a retried run
	// converge rather than fail. Aliases that never received a click are released —
	// deliberately, per the reserved_aliases rationale: nothing in the wild points
	// at them, so permanent reservation would only bleed the namespace.
	//
	// SKIP LOCKED so the purge can never block, or be blocked by, a concurrent
	// restore-by-hand of the same row; a skipped row is caught on the next run.
	// Destinations and link_tags follow by ON DELETE CASCADE. click_events rows
	// carry no FK (partitioned) and are dropped by analytics retention instead.
	PurgeExpiredLinks(ctx context.Context, batchSize int32) ([]PurgeExpiredLinksRow, error)
	// The de-identification step. Once the salt is gone the day's hashes cannot be
	// linked back to an address.
	PurgeExpiredSalts(ctx context.Context) (int64, error)
	//
	// Sent and failed rows past the retention window. The outbox is a record of
	// what was attempted, not an archive: without this the table is the one thing
	// in the schema that grows forever with no window and no metric, which is the
	// shape D5 and M21 exist to avoid repeating.
	PurgeFinishedMail(ctx context.Context, maxAgeDays int32) (int64, error)
	// Returns the new count so the caller can apply the lockout policy without a
	// second round trip and without a read-modify-write race between two
	// concurrent attempts.
	//
	// An elapsed lockout starts the count over. Incrementing unconditionally meant
	// the counter only ever went down on a successful sign-in or a password change,
	// so once an account had been locked it sat at the threshold forever: the user
	// waited out the window, got one attempt, and a single wrong guess re-locked
	// them for the full duration. The lockout became permanent for anyone who could
	// not remember their password on the first try — which is the population it
	// applies to.
	RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error)
	// Keeps the watermark where it was: a failed run has not covered its window,
	// and advancing past it would turn one bad run into permanent gaps.
	RecordJobFailure(ctx context.Context, arg RecordJobFailureParams) error
	RecordSuccessfulLogin(ctx context.Context, id uuid.UUID) error
	// Name and slug move together. The slug is derived from the name by the caller
	// rather than kept as a separate field somebody can edit into disagreement with
	// it, and the partial unique index on (organization_id, lower(slug)) is what
	// refuses a collision.
	RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (Workspace, error)
	// Called before purging a link that has clicks. The alias is in the wild — on
	// printed material and in other people's bookmarks — so handing it to a new
	// destination would be a redirect hijack.
	ReserveAlias(ctx context.Context, arg ReserveAliasParams) error
	// The redirect hot path.
	//
	// Everything here runs under a 20ms budget on the dedicated redirect pool.
	// Keep the query set small, index-covered, and free of joins that are not
	// strictly required.
	// Single-row lookup on links_domain_alias_key.
	//
	// primary_url is read from the denormalized column rather than joined from
	// destinations: the join would double the row fetches on the hottest query in
	// the system to retrieve a value a trigger already keeps in step.
	//
	// Status and expiry are returned rather than filtered, so the handler can
	// distinguish 404 (unknown or archived) from 410 (expired) and can cache a
	// negative result. Filtering here would make every non-serving state look
	// identical.
	ResolveAliasForRedirect(ctx context.Context, arg ResolveAliasForRedirectParams) (ResolveAliasForRedirectRow, error)
	// Read once at boot and cached. The default domain is matched on the flag
	// rather than on a hostname string, so it never has to agree with
	// LINKCTRL_BASE_URL.
	ResolveDefaultDomain(ctx context.Context) (ResolveDefaultDomainRow, error)
	// PHASE 2: custom domains. Present now because the cache key is already
	// host-scoped, so enabling it later needs no key change.
	ResolveDomainByHostname(ctx context.Context, lower string) (ResolveDomainByHostnameRow, error)
	// The workspace a request acts in, and the only place that question is
	// answered. Every identity — session, API key, CLI — comes through here.
	//
	// The precedence is the ORDER BY and nothing else, so there is one statement of
	// it rather than one per caller:
	//
	//   1. the session's own current workspace, for a request that has a session
	//   2. the workspace the user pinned as their default
	//   3. the workspace they used last
	//   4. the oldest workspace they are a member of
	//
	// Each rung is a tiebreak on the one above, so a user with a single membership
	// ties on all four and lands where they always did. That is what makes the
	// switcher a no-op for every instance that exists today.
	//
	// Membership is the WHERE clause, not the ordering, so a preference pointing at
	// a workspace the user has been removed from — or one that has been deleted —
	// cannot win. It simply stops matching and the next rung answers.
	//
	// session_id is optional. NULL leaves the LEFT JOIN unmatched and rung 1 dead,
	// which is right for a login (the session does not exist yet), the CLI, and an
	// API key. The join also requires the session to belong to this user, so a
	// borrowed id resolves nothing.
	ResolveWorkspaceForUser(ctx context.Context, arg ResolveWorkspaceForUserParams) (Workspace, error)
	RestoreLink(ctx context.Context, arg RestoreLinkParams) (Link, error)
	// Idempotent: revoking an already-revoked key keeps the original timestamp and
	// still reports one row, so a repeated call is a success rather than a 404
	// while a genuinely unknown id is still distinguishable.
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	// Used on password change. Anyone who had the old password must be logged out,
	// which is the entire point of changing it.
	// keep_session is optional: pass NULL to revoke everything, or the current
	// session's id to leave the browser the user is changing their password in
	// still signed in.
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error
	// Scoped by organization as well as id, so an id from another organization is
	// indistinguishable from one that does not exist: both change zero rows.
	//
	// Already-revoked and already-redeemed are excluded rather than tolerated. A
	// redeemed invite has produced a member, and reporting "revoked" for it would
	// claim something the tree does not support.
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error)
	// Clears an expired invite out of the outstanding slot so a replacement can be
	// issued.
	//
	// The partial unique index cannot exclude expired rows — `now()` is not
	// immutable, so Postgres will not index on it — which means an invite that
	// lapsed still occupies the address. This runs immediately before the insert,
	// in the same transaction, and touches nothing that is still redeemable.
	RevokeLapsedInvitation(ctx context.Context, arg RevokeLapsedInvitationParams) (int64, error)
	RevokeSession(ctx context.Context, id uuid.UUID) error
	// Every dimension in one pass over click_events.
	//
	// This was six UNION ALL branches, one per dimension, reading the same rows six
	// times. Measured on the load-test dataset (5.7M events, ~830k inside the
	// recomputed window), that shape sorted 6.2M rows through an external merge that
	// spilled 471 MB of temp files, every 60 seconds. Reading once and expanding each
	// row with LATERAL VALUES lets the sort use the index's link_id ordering, so it
	// runs incrementally in memory instead — peak 152 kB per group, no temp files.
	//
	// Wall clock is unchanged (~20s either way), and that is the finding rather than a
	// disappointment: the time is in the 553k upserts a whole-day recompute implies,
	// not in reading the events. See docs/slo.md. This version is kept because
	// eliminating half a gigabyte of temp I/O per run is worth having on any host
	// smaller than the one it was measured on; it is not a fix for the job's cost.
	//
	// The output is identical: same grouping keys, same aggregates, same conflict
	// resolution. TestDimensionRollupMatchesAPerDimensionAggregate checks that
	// against a per-dimension aggregate written the other way round.
	RollupDimensionDaily(ctx context.Context, arg RollupDimensionDailyParams) error
	// Recompute per-link daily totals for a window.
	//
	// Idempotent by construction: it recomputes a whole day from the raw events
	// and upserts, so running it twice, or after a crash mid-run, converges to the
	// same numbers. An incremental "add what is new" design would double-count on
	// any retry.
	RollupLinkDaily(ctx context.Context, arg RollupLinkDailyParams) error
	RollupWorkspaceDaily(ctx context.Context, arg RollupWorkspaceDailyParams) error
	// NULL clears it, which restores the 404 the root answered before anyone set
	// anything.
	SetDefaultDomainRootRedirect(ctx context.Context, rootRedirectUrl *string) (SetDefaultDomainRootRedirectRow, error)
	// Pins a workspace as where new sessions start, or clears the pin.
	//
	// NULL is a real value here and means "follow last-used", which is the default
	// the control offers. Clearing therefore needs no membership check; setting
	// needs the same one as above.
	SetDefaultWorkspaceForUser(ctx context.Context, arg SetDefaultWorkspaceForUserParams) (int64, error)
	SetJobWatermark(ctx context.Context, arg SetJobWatermarkParams) error
	// Remembers a selection, and refuses one the user is not entitled to.
	//
	// The membership check is in the statement rather than in a preceding SELECT so
	// there is no window between the two. Zero rows means "not yours or not there",
	// which the caller reports as not-found: a workspace id must not be probeable
	// for existence.
	SetLastWorkspaceForUser(ctx context.Context, arg SetLastWorkspaceForUserParams) (int64, error)
	SetPrimaryDestination(ctx context.Context, arg SetPrimaryDestinationParams) error
	// Moves one session, and only the session that asked.
	//
	// Scoped by user_id as well as id so a session id from elsewhere cannot be
	// repointed, and revoked sessions are excluded because moving one would be
	// writing to a credential that no longer authenticates.
	SetSessionWorkspace(ctx context.Context, arg SetSessionWorkspaceParams) (int64, error)
	// Soft delete with a purge deadline rather than an immediate DELETE. Restoring
	// a link someone deleted by accident is a common request, and the alias stays
	// reserved while the row exists.
	SoftDeleteLink(ctx context.Context, arg SoftDeleteLinkParams) (SoftDeleteLinkRow, error)
	// Batch write of last_used_at, from the coalescing tracker rather than from the
	// request path: authenticating a key must not cost a synchronous write.
	//
	// GREATEST guards against a late batch moving the timestamp backwards, which
	// two processes flushing out of order would otherwise do.
	TouchAPIKeys(ctx context.Context, arg TouchAPIKeysParams) error
	// Idle expiry is measured from last_seen_at. Updated at most once a minute by
	// the caller, because writing on every request would turn a read-mostly path
	// into a write on the hottest authenticated query.
	TouchSession(ctx context.Context, id uuid.UUID) error
	// The trigger on destinations mirrors this into links.primary_url, so the hot
	// path never joins.
	UpdateDestinationURL(ctx context.Context, arg UpdateDestinationURLParams) error
	// COALESCE with sqlc.narg gives partial update: a NULL argument leaves the
	// column alone, so PATCH semantics need no dynamic SQL.
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	// Scoped by organization as well as id, so the authorization decision the
	// service made cannot be applied to a row in another tenant.
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
