// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routing.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRoutingRules = `-- name: CountRoutingRules :one
SELECT count(*) FROM routing_rules WHERE link_id = $1
`

// Read before an insert, to enforce the per-link ceiling. Counts every kind,
// not only 'match': the ceiling exists because the whole list travels inside
// the cached snapshot and is walked in order on the redirect path, and M36's
// rows will be in that list too.
func (q *Queries) CountRoutingRules(ctx context.Context, linkID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutingRules, linkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoutingRule = `-- name: CreateRoutingRule :one

INSERT INTO routing_rules (
    id, link_id, workspace_id, destination_id, priority, conditions, kind, enabled
) VALUES ($1, $2, $3, $4, $5, $6, 'match', $7)
RETURNING id, link_id, workspace_id, destination_id, priority, conditions, kind, enabled, created_at, updated_at
`

type CreateRoutingRuleParams struct {
	ID            uuid.UUID
	LinkID        uuid.UUID
	WorkspaceID   uuid.UUID
	DestinationID *uuid.UUID
	Priority      int32
	Conditions    []byte
	Enabled       bool
}

// Routing rules (M34).
//
// Every query here filters on kind = 'match'. That is not defensive coding: the
// column's CHECK also permits weighted, sequential and fallback, which are
// M36's, and a query that read every kind would start behaving differently the
// day those rows first exist — silently, on the redirect path. The filter means
// M36 has to write its own reads, which is the correct amount of work for a
// milestone that adds a new evaluation model.
//
// Rule *targets* are ordinary `destinations` rows. A rule therefore costs two
// writes and the destination is what carries the URL, its host, and the M30
// tier check the service applied before either row existed.
func (q *Queries) CreateRoutingRule(ctx context.Context, arg CreateRoutingRuleParams) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, createRoutingRule,
		arg.ID,
		arg.LinkID,
		arg.WorkspaceID,
		arg.DestinationID,
		arg.Priority,
		arg.Conditions,
		arg.Enabled,
	)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.DestinationID,
		&i.Priority,
		&i.Conditions,
		&i.Kind,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRuleDestination = `-- name: CreateRuleDestination :one
INSERT INTO destinations (id, link_id, workspace_id, url, url_host, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, link_id, workspace_id, url, url_host, label, weight, position, created_at, updated_at, deleted_at
`

type CreateRuleDestinationParams struct {
	ID          uuid.UUID
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
	Url         string
	UrlHost     string
	Position    int32
}

// A rule's target. Position is above zero so it can never be mistaken for the
// link's own destination, which Phase 1 put at position 0 and which
// `links.primary_destination_id` points at.
func (q *Queries) CreateRuleDestination(ctx context.Context, arg CreateRuleDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createRuleDestination,
		arg.ID,
		arg.LinkID,
		arg.WorkspaceID,
		arg.Url,
		arg.UrlHost,
		arg.Position,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.Url,
		&i.UrlHost,
		&i.Label,
		&i.Weight,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createVariantDestination = `-- name: CreateVariantDestination :one
INSERT INTO destinations (id, link_id, workspace_id, url, url_host, position, weight)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, link_id, workspace_id, url, url_host, label, weight, position, created_at, updated_at, deleted_at
`

type CreateVariantDestinationParams struct {
	ID          uuid.UUID
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
	Url         string
	UrlHost     string
	Position    int32
	Weight      int32
}

// A variant's target, with its weight. The same row CreateRuleDestination
// writes, plus the one column that makes it an arm rather than a target: 00300
// has carried `weight` since Phase 1 with a comment naming this milestone.
func (q *Queries) CreateVariantDestination(ctx context.Context, arg CreateVariantDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createVariantDestination,
		arg.ID,
		arg.LinkID,
		arg.WorkspaceID,
		arg.Url,
		arg.UrlHost,
		arg.Position,
		arg.Weight,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.Url,
		&i.UrlHost,
		&i.Label,
		&i.Weight,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createVariantRule = `-- name: CreateVariantRule :one

INSERT INTO routing_rules (
    id, link_id, workspace_id, destination_id, conditions, kind, enabled
) VALUES ($1, $2, $3, $4, '{}'::jsonb, $6, $5)
RETURNING id, link_id, workspace_id, destination_id, priority, conditions, kind, enabled, created_at, updated_at
`

type CreateVariantRuleParams struct {
	ID            uuid.UUID
	LinkID        uuid.UUID
	WorkspaceID   uuid.UUID
	DestinationID *uuid.UUID
	Enabled       bool
	Kind          string
}

// --- split testing (M36) -----------------------------------------------------
//
// A variant is a rule row of kind weighted, sequential or fallback, pointing at
// its own `destinations` row exactly as a match rule's target does. So the
// writes below are the same two writes, and the M30 tier check the service
// applied before either row existed is the same check.
//
// Every query here excludes `match` for the reason every query above requires
// it: the two management surfaces address disjoint sets of rows, so a rule id
// handed to the wrong endpoint finds nothing rather than editing a rule of a
// kind the caller was not looking at.
// Priority is fixed at the column default and never read for a variant: arms are
// chosen, not matched in order, and a priority on one would be a number the
// dashboard shows and nothing obeys. Creation order is what orders a rotation,
// which is what ListVariantRules sorts by.
func (q *Queries) CreateVariantRule(ctx context.Context, arg CreateVariantRuleParams) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, createVariantRule,
		arg.ID,
		arg.LinkID,
		arg.WorkspaceID,
		arg.DestinationID,
		arg.Enabled,
		arg.Kind,
	)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.DestinationID,
		&i.Priority,
		&i.Conditions,
		&i.Kind,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoutingRule = `-- name: DeleteRoutingRule :one
DELETE FROM routing_rules
WHERE id = $1 AND workspace_id = $2 AND kind = 'match'
RETURNING destination_id
`

type DeleteRoutingRuleParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Returns the destination so the caller can remove it in the same transaction.
// A rule target left behind would be an orphan row nothing reads and nothing
// can reach, accumulating one per deleted rule for the life of the link.
func (q *Queries) DeleteRoutingRule(ctx context.Context, arg DeleteRoutingRuleParams) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteRoutingRule, arg.ID, arg.WorkspaceID)
	var destination_id *uuid.UUID
	err := row.Scan(&destination_id)
	return destination_id, err
}

const deleteRuleDestination = `-- name: DeleteRuleDestination :exec
DELETE FROM destinations d
WHERE d.id = $1 AND d.workspace_id = $2
  AND NOT EXISTS (SELECT 1 FROM links l WHERE l.primary_destination_id = d.id)
`

type DeleteRuleDestinationParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// A hard delete, not the soft delete `deleted_at` exists for. Nothing reports
// on a rule target and nothing can restore a deleted rule, so a tombstone here
// would be a row that only ever grows the table.
// The NOT EXISTS is a guard rather than a branch anything takes: only rule
// targets reach this query. It is here because the one row this must never
// delete is the link's own destination, and the cost of being wrong about that
// is a link that redirects nowhere.
func (q *Queries) DeleteRuleDestination(ctx context.Context, arg DeleteRuleDestinationParams) error {
	_, err := q.db.Exec(ctx, deleteRuleDestination, arg.ID, arg.WorkspaceID)
	return err
}

const deleteVariantRule = `-- name: DeleteVariantRule :one
DELETE FROM routing_rules
WHERE id = $1 AND workspace_id = $2 AND kind <> 'match'
RETURNING destination_id
`

type DeleteVariantRuleParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteVariantRule(ctx context.Context, arg DeleteVariantRuleParams) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteVariantRule, arg.ID, arg.WorkspaceID)
	var destination_id *uuid.UUID
	err := row.Scan(&destination_id)
	return destination_id, err
}

const getRoutingRule = `-- name: GetRoutingRule :one
SELECT rr.id, rr.link_id, rr.workspace_id, rr.destination_id, rr.priority,
       rr.conditions, rr.enabled, rr.created_at, rr.updated_at,
       d.url::text AS url
FROM routing_rules rr
JOIN destinations d ON d.id = rr.destination_id
WHERE rr.id = $1
  AND rr.workspace_id = $2
  AND rr.kind = 'match'
  AND d.deleted_at IS NULL
`

type GetRoutingRuleParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type GetRoutingRuleRow struct {
	ID            uuid.UUID
	LinkID        uuid.UUID
	WorkspaceID   uuid.UUID
	DestinationID *uuid.UUID
	Priority      int32
	Conditions    []byte
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Url           string
}

func (q *Queries) GetRoutingRule(ctx context.Context, arg GetRoutingRuleParams) (GetRoutingRuleRow, error) {
	row := q.db.QueryRow(ctx, getRoutingRule, arg.ID, arg.WorkspaceID)
	var i GetRoutingRuleRow
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.DestinationID,
		&i.Priority,
		&i.Conditions,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
	)
	return i, err
}

const getVariantRule = `-- name: GetVariantRule :one
SELECT rr.id, rr.link_id, rr.workspace_id, rr.destination_id, rr.kind,
       rr.enabled, rr.created_at, rr.updated_at,
       d.url::text AS url, d.weight, d.position
FROM routing_rules rr
JOIN destinations d ON d.id = rr.destination_id
WHERE rr.id = $1
  AND rr.workspace_id = $2
  AND rr.kind <> 'match'
  AND d.deleted_at IS NULL
`

type GetVariantRuleParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type GetVariantRuleRow struct {
	ID            uuid.UUID
	LinkID        uuid.UUID
	WorkspaceID   uuid.UUID
	DestinationID *uuid.UUID
	Kind          string
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Url           string
	Weight        int32
	Position      int32
}

func (q *Queries) GetVariantRule(ctx context.Context, arg GetVariantRuleParams) (GetVariantRuleRow, error) {
	row := q.db.QueryRow(ctx, getVariantRule, arg.ID, arg.WorkspaceID)
	var i GetVariantRuleRow
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.DestinationID,
		&i.Kind,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.Weight,
		&i.Position,
	)
	return i, err
}

const listLinkDestinations = `-- name: ListLinkDestinations :many
SELECT d.id, d.url::text AS url, d.weight, d.position,
       (d.id = l.primary_destination_id) AS is_primary
FROM destinations d
JOIN links l ON l.id = d.link_id
WHERE d.link_id = $1
  AND d.workspace_id = $2
  AND d.deleted_at IS NULL
ORDER BY d.position
`

type ListLinkDestinationsParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
}

type ListLinkDestinationsRow struct {
	ID        uuid.UUID
	Url       string
	Weight    int32
	Position  int32
	IsPrimary bool
}

// Every destination a link has, for the per-destination breakdown to name.
//
// Includes the link's own destination at position 0, because a click recorded
// before the link had a split — or on a link whose split was later removed —
// carries a NULL destination_id and is attributed to exactly that row. A
// breakdown that could not name it would be a chart with an unlabelled bar
// holding most of the traffic.
func (q *Queries) ListLinkDestinations(ctx context.Context, arg ListLinkDestinationsParams) ([]ListLinkDestinationsRow, error) {
	rows, err := q.db.Query(ctx, listLinkDestinations, arg.LinkID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkDestinationsRow{}
	for rows.Next() {
		var i ListLinkDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Weight,
			&i.Position,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutingRules = `-- name: ListRoutingRules :many
SELECT rr.id, rr.link_id, rr.workspace_id, rr.destination_id, rr.priority,
       rr.conditions, rr.enabled, rr.created_at, rr.updated_at,
       d.url::text AS url
FROM routing_rules rr
JOIN destinations d ON d.id = rr.destination_id
WHERE rr.link_id = $1
  AND rr.workspace_id = $2
  AND rr.kind = 'match'
  AND d.deleted_at IS NULL
ORDER BY rr.priority, rr.created_at
`

type ListRoutingRulesParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
}

type ListRoutingRulesRow struct {
	ID            uuid.UUID
	LinkID        uuid.UUID
	WorkspaceID   uuid.UUID
	DestinationID *uuid.UUID
	Priority      int32
	Conditions    []byte
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Url           string
}

// The management list: every rule on a link, enabled or not, in the order the
// redirect path would evaluate them.
//
// Ordered by (priority, created_at) rather than by priority alone. Priority is
// not unique, and two rules that tie have to be evaluated in a defined order or
// the same request resolves differently on two replicas. Creation order is the
// tiebreak because it is the only one a person can predict from the list they
// are looking at.
//
// Workspace-scoped in the WHERE like every other management read, so a rule
// belonging to another tenant returns no rows rather than a row the caller has
// to remember to reject.
func (q *Queries) ListRoutingRules(ctx context.Context, arg ListRoutingRulesParams) ([]ListRoutingRulesRow, error) {
	rows, err := q.db.Query(ctx, listRoutingRules, arg.LinkID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutingRulesRow{}
	for rows.Next() {
		var i ListRoutingRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.WorkspaceID,
			&i.DestinationID,
			&i.Priority,
			&i.Conditions,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantRules = `-- name: ListVariantRules :many
SELECT rr.id, rr.link_id, rr.workspace_id, rr.destination_id, rr.kind,
       rr.enabled, rr.created_at, rr.updated_at,
       d.url::text AS url, d.weight, d.position
FROM routing_rules rr
JOIN destinations d ON d.id = rr.destination_id
WHERE rr.link_id = $1
  AND rr.workspace_id = $2
  AND rr.kind <> 'match'
  AND d.deleted_at IS NULL
ORDER BY d.position
`

type ListVariantRulesParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
}

type ListVariantRulesRow struct {
	ID            uuid.UUID
	LinkID        uuid.UUID
	WorkspaceID   uuid.UUID
	DestinationID *uuid.UUID
	Kind          string
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Url           string
	Weight        int32
	Position      int32
}

// A link's whole split, including the disabled arms and the fallback, in
// rotation order.
//
// Ordered by the destination's position rather than by created_at: position is
// assigned once, from NextRuleDestinationPosition, and is the only ordering that
// a person reading the list can predict and that a rotation can be explained
// against. Two arms created in the same transaction cannot tie on it.
func (q *Queries) ListVariantRules(ctx context.Context, arg ListVariantRulesParams) ([]ListVariantRulesRow, error) {
	rows, err := q.db.Query(ctx, listVariantRules, arg.LinkID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantRulesRow{}
	for rows.Next() {
		var i ListVariantRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.WorkspaceID,
			&i.DestinationID,
			&i.Kind,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.Weight,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRuleDestinationPosition = `-- name: NextRuleDestinationPosition :one
SELECT COALESCE(max(position), 0) + 1 FROM destinations
WHERE link_id = $1 AND deleted_at IS NULL
`

// The next free position above the primary. COALESCE so the first rule on a
// link lands at 1 rather than at NULL.
func (q *Queries) NextRuleDestinationPosition(ctx context.Context, linkID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextRuleDestinationPosition, linkID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateRoutingRule = `-- name: UpdateRoutingRule :one
UPDATE routing_rules
   SET priority   = COALESCE($1, priority),
       conditions = COALESCE($2, conditions),
       enabled    = COALESCE($3, enabled),
       updated_at = now()
 WHERE id = $4
   AND workspace_id = $5
   AND kind = 'match'
RETURNING id, link_id, workspace_id, destination_id, priority, conditions, kind, enabled, created_at, updated_at
`

type UpdateRoutingRuleParams struct {
	Priority    *int32
	Conditions  []byte
	Enabled     *bool
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Partial update, same COALESCE-with-narg shape as UpdateLink. The destination
// is not here: changing where a rule points is a write to its `destinations`
// row, so that the URL, its host and the tier check that accepted it stay in
// one place.
func (q *Queries) UpdateRoutingRule(ctx context.Context, arg UpdateRoutingRuleParams) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, updateRoutingRule,
		arg.Priority,
		arg.Conditions,
		arg.Enabled,
		arg.ID,
		arg.WorkspaceID,
	)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.DestinationID,
		&i.Priority,
		&i.Conditions,
		&i.Kind,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRuleDestinationURL = `-- name: UpdateRuleDestinationURL :exec
UPDATE destinations
   SET url = $2, url_host = $3, updated_at = now()
 WHERE id = $1 AND workspace_id = $4 AND deleted_at IS NULL
`

type UpdateRuleDestinationURLParams struct {
	ID          uuid.UUID
	Url         string
	UrlHost     string
	WorkspaceID uuid.UUID
}

// Scoped to one destination id, unlike UpdateDestinationURL. A rule target and
// the link's own destination are two rows on the same link now, and the wrong
// one of these two queries would move both.
func (q *Queries) UpdateRuleDestinationURL(ctx context.Context, arg UpdateRuleDestinationURLParams) error {
	_, err := q.db.Exec(ctx, updateRuleDestinationURL,
		arg.ID,
		arg.Url,
		arg.UrlHost,
		arg.WorkspaceID,
	)
	return err
}

const updateVariantDestination = `-- name: UpdateVariantDestination :exec
UPDATE destinations
   SET url        = COALESCE($1, url),
       url_host   = COALESCE($2, url_host),
       weight     = COALESCE($3, weight),
       updated_at = now()
 WHERE id = $4 AND workspace_id = $5
   AND deleted_at IS NULL
`

type UpdateVariantDestinationParams struct {
	Url         *string
	UrlHost     *string
	Weight      *int32
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// The URL, the weight, or both. Scoped to one destination id for the reason
// UpdateRuleDestinationURL is: a link's own destination and its arms are rows in
// the same table on the same link.
func (q *Queries) UpdateVariantDestination(ctx context.Context, arg UpdateVariantDestinationParams) error {
	_, err := q.db.Exec(ctx, updateVariantDestination,
		arg.Url,
		arg.UrlHost,
		arg.Weight,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updateVariantRule = `-- name: UpdateVariantRule :one
UPDATE routing_rules
   SET enabled    = COALESCE($1, enabled),
       updated_at = now()
 WHERE id = $2
   AND workspace_id = $3
   AND kind <> 'match'
RETURNING id, link_id, workspace_id, destination_id, priority, conditions, kind, enabled, created_at, updated_at
`

type UpdateVariantRuleParams struct {
	Enabled     *bool
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Only the enabled flag, because that is the only thing on the rule row a
// variant has. A weight is a write to the destination; a kind is not editable at
// all, since changing one arm's kind would mix two kinds on a link and the
// service refuses that outright.
func (q *Queries) UpdateVariantRule(ctx context.Context, arg UpdateVariantRuleParams) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, updateVariantRule, arg.Enabled, arg.ID, arg.WorkspaceID)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.WorkspaceID,
		&i.DestinationID,
		&i.Priority,
		&i.Conditions,
		&i.Kind,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
