// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signup.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePendingRegistration = `-- name: ConsumePendingRegistration :execrows
UPDATE pending_registrations
   SET consumed_at = now()
 WHERE id = $1
   AND consumed_at IS NULL
`

// Spends a registration. Conditional on it still being unspent, so this could
// not succeed twice even without the lock above; zero rows rolls the
// transaction back.
func (q *Queries) ConsumePendingRegistration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumePendingRegistration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT count(*) FROM users WHERE email_lower = lower($1::text) AND deleted_at IS NULL
`

// Whether an address already has an account, for the signup form.
//
// Counted rather than selected: the caller needs the answer and nothing else,
// and returning the row would put somebody else's name and hash in a variable
// that only ever gets compared against zero.
func (q *Queries) CountUsersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :one

INSERT INTO pending_registrations (
    id, email, name, password_hash, token_hash, expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, email_lower, name, password_hash, token_hash, created_at, expires_at, consumed_at
`

type CreatePendingRegistrationParams struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	TokenHash    []byte
	ExpiresAt    time.Time
}

// Self-serve signup: the registrations waiting on an address to be proven
// (M29). The mode itself is `LINKCTRL_SIGNUP_MODE` and is never read from the
// database (D38), so nothing here answers what the instance admits.
func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, createPendingRegistration,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.Name,
		&i.PasswordHash,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const deleteOutstandingRegistration = `-- name: DeleteOutstandingRegistration :execrows
DELETE FROM pending_registrations
 WHERE email_lower = lower($1::text)
   AND consumed_at IS NULL
`

// Clears whatever is outstanding for an address so a fresh attempt can take the
// slot.
//
// Superseding rather than refusing, because the ordinary reason somebody
// registers twice is that the first mail never arrived. The old token stops
// working at the same moment, which is what makes this safe: there is never
// more than one live link per address.
func (q *Queries) DeleteOutstandingRegistration(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOutstandingRegistration, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingRegistrationByTokenHash = `-- name: GetPendingRegistrationByTokenHash :one
SELECT id, email, email_lower, name, password_hash, token_hash, created_at, expires_at, consumed_at FROM pending_registrations
 WHERE token_hash = $1
   FOR UPDATE
`

// Verification's lookup, inside the transaction that spends the row.
//
// FOR UPDATE, so two clicks on the same link serialize and the second sees the
// row the first consumed.
func (q *Queries) GetPendingRegistrationByTokenHash(ctx context.Context, tokenHash []byte) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationByTokenHash, tokenHash)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailLower,
		&i.Name,
		&i.PasswordHash,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const purgeLapsedRegistrations = `-- name: PurgeLapsedRegistrations :execrows
DELETE FROM pending_registrations
 WHERE (consumed_at IS NULL AND expires_at <= now())
    OR (consumed_at IS NOT NULL AND consumed_at <= now() - make_interval(days => $1::int))
`

// The sweep. Removes registrations nobody completed, and consumed rows whose
// account has long since been created.
//
// Both, because neither is a record of anything: an account that exists is
// evidence enough that its address was proven, and the audit log carries what
// happened. This table is a waiting room, not an archive — the one shape it
// must not have is the unbounded growth D5 and M21 exist to stop repeating.
func (q *Queries) PurgeLapsedRegistrations(ctx context.Context, keepDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgeLapsedRegistrations, keepDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
