// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces
 WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type DeleteWorkspaceParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// A real delete, not a soft one, and that is the decision D32 guards.
//
// `links`, `tags` and `folders` cascade from here (00300_links.sql). Soft
// deleting instead would leave those rows behind and their aliases still
// serving redirects out of a workspace the dashboard says is gone, which is a
// worse outcome than the cascade — so the guard goes in front of the delete and
// the delete is honest about what it does.
func (q *Queries) DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspace, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceInOrganization = `-- name: GetWorkspaceInOrganization :one
SELECT id, organization_id, name, slug, analytics_retention_days, created_at, updated_at, deleted_at FROM workspaces
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetWorkspaceInOrganizationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// One workspace, scoped by organization so an id belonging to another tenant is
// indistinguishable from one that does not exist.
//
// FOR UPDATE: both callers — rename and delete — are about to write this row or
// the rows that cascade from it, and delete reads a link count that must not
// change underneath the decision.
func (q *Queries) GetWorkspaceInOrganization(ctx context.Context, arg GetWorkspaceInOrganizationParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInOrganization, arg.ID, arg.OrganizationID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.AnalyticsRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many

SELECT DISTINCT
    w.id,
    w.name,
    w.slug,
    w.organization_id,
    o.name AS organization_name,
    o.is_personal,
    (w.id IS NOT DISTINCT FROM u.default_workspace_id) AS is_default
FROM workspaces w
JOIN organizations o ON o.id = w.organization_id
JOIN memberships m   ON m.organization_id = w.organization_id
JOIN users u         ON u.id = m.user_id
WHERE m.user_id = $1
  AND w.deleted_at IS NULL
  AND o.deleted_at IS NULL
  AND (m.workspace_id IS NULL OR m.workspace_id = w.id)
ORDER BY o.name, w.name, w.id
`

type ListWorkspacesForUserRow struct {
	ID               uuid.UUID
	Name             string
	Slug             string
	OrganizationID   uuid.UUID
	OrganizationName string
	IsPersonal       bool
	IsDefault        bool
}

// The workspace switcher: what a user may act in, and what they have chosen.
//
// Resolution itself is in auth.sql, because it is identity, not a feature.
// These are the reads and writes the switcher and its account setting need.
// Every workspace a user may act in, with the organization it belongs to.
//
// DISTINCT because a user can hold both an organization-wide membership and a
// workspace-scoped one in the same organization, which the unique index
// permits; without it the switcher would list a workspace twice.
//
// is_default is carried here rather than fetched separately so a page render
// costs one query: the nav switcher needs the list, the account setting needs
// the list plus which entry is pinned, and neither should cost two round trips.
func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.IsPersonal,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameWorkspace = `-- name: RenameWorkspace :one
UPDATE workspaces
   SET name = $3,
       slug = $4,
       updated_at = now()
 WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
RETURNING id, organization_id, name, slug, analytics_retention_days, created_at, updated_at, deleted_at
`

type RenameWorkspaceParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Slug           string
}

// Name and slug move together. The slug is derived from the name by the caller
// rather than kept as a separate field somebody can edit into disagreement with
// it, and the partial unique index on (organization_id, lower(slug)) is what
// refuses a collision.
func (q *Queries) RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, renameWorkspace,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.AnalyticsRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setDefaultWorkspaceForUser = `-- name: SetDefaultWorkspaceForUser :execrows
UPDATE users
   SET default_workspace_id = $1,
       updated_at = now()
 WHERE users.id = $2
   AND ($1::uuid IS NULL OR EXISTS (
       SELECT 1
       FROM workspaces w
       JOIN memberships m ON m.organization_id = w.organization_id
       WHERE w.id = $1::uuid
         AND m.user_id = $2
         AND w.deleted_at IS NULL
         AND (m.workspace_id IS NULL OR m.workspace_id = w.id)))
`

type SetDefaultWorkspaceForUserParams struct {
	WorkspaceID *uuid.UUID
	UserID      uuid.UUID
}

// Pins a workspace as where new sessions start, or clears the pin.
//
// NULL is a real value here and means "follow last-used", which is the default
// the control offers. Clearing therefore needs no membership check; setting
// needs the same one as above.
func (q *Queries) SetDefaultWorkspaceForUser(ctx context.Context, arg SetDefaultWorkspaceForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDefaultWorkspaceForUser, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLastWorkspaceForUser = `-- name: SetLastWorkspaceForUser :execrows
UPDATE users
   SET last_workspace_id = $1::uuid,
       updated_at = now()
 WHERE users.id = $2
   AND EXISTS (
       SELECT 1
       FROM workspaces w
       JOIN memberships m ON m.organization_id = w.organization_id
       WHERE w.id = $1::uuid
         AND m.user_id = $2
         AND w.deleted_at IS NULL
         AND (m.workspace_id IS NULL OR m.workspace_id = w.id))
`

type SetLastWorkspaceForUserParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

// Remembers a selection, and refuses one the user is not entitled to.
//
// The membership check is in the statement rather than in a preceding SELECT so
// there is no window between the two. Zero rows means "not yours or not there",
// which the caller reports as not-found: a workspace id must not be probeable
// for existence.
func (q *Queries) SetLastWorkspaceForUser(ctx context.Context, arg SetLastWorkspaceForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLastWorkspaceForUser, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionWorkspace = `-- name: SetSessionWorkspace :execrows
UPDATE sessions
   SET workspace_id = $1::uuid
 WHERE sessions.id = $2
   AND sessions.user_id = $3
   AND revoked_at IS NULL
`

type SetSessionWorkspaceParams struct {
	WorkspaceID uuid.UUID
	SessionID   uuid.UUID
	UserID      uuid.UUID
}

// Moves one session, and only the session that asked.
//
// Scoped by user_id as well as id so a session id from elsewhere cannot be
// repointed, and revoked sessions are excluded because moving one would be
// writing to a credential that no longer authenticates.
func (q *Queries) SetSessionWorkspace(ctx context.Context, arg SetSessionWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionWorkspace, arg.WorkspaceID, arg.SessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
